### ISSUE TITLE
ec_deployment_elasticsearch_keystore: Add new resource

### ISSUE THREAD

**Issue by marclop** [elastic/terraform-provider-ec#100]
## Overview

Add a new resource which allows the management of Elasticsearch keystore secrets on an Elasticsearch hosted in Elastic Cloud.

## Possible Implementation

Allowing to set raw values and encrypted with a key?

**Comment by karencfv** [comment]
There are several issues with this adding this resource which make it a bit more complex to implement.

- There is no `DELETE` method, so `PATCH` is needed for all delete actions.

- As the value of the secret is never returned on a read, every time you run `terraform apply`, even if there are no changes to your `.tf` file, there will be a diff. It will appear as you are making changes. This is not great UX.

- The above point makes it tricky to delete secrets based on a diff.

We have decided to delay working on this until after the 0.1.0 release

**Comment by cvanhalt** [comment]
Hi, is this feature still on any roadmap?

**Comment by rhollins** [comment]
this would be very useful

**Comment by marclop** [comment]
This issue is still blocked since there aren't any GET / SET / DELETE primitives in our API to allow proper control of the Elasticsearch secrets through the provider. I've labeled this issue as `blocked` since we can't make any progress until the underlying issues that prevent us from adding this feature are addressed.

**Comment by simon-schneider-gcx** [comment]
Hi @xeraa ,

could you help here, please? 
This needs to be implemented on the elastic cloud side and it seems this issue has no or low priority there...

**Comment by xeraa** [comment]
I'm afraid [the API still only supports `PATCH`](https://www.elastic.co/guide/en/cloud/current/Deployment_Resources_-_CRUD.html#set-deployment-es-resource-keystore). And the Cloud backlog is pretty deep, so any promises or predictions are hard to make.

If I'm not mistaken using the keystore is generally tricky (what is allowed, what is potentially harmful for the cluster), so I'm not sure if this will "just" be the API or might need to wait for a bigger refactoring — sorry.

**Comment by Crazybus** [comment]
Note: I'm not very experienced with Terraform provider development but thought I'd drop some thoughts in case they inspire any potential solutions with the current limitations.

If you are willing to accept drift (or at least until the API supports returning the value) it should be possible to implement this in the same way that the Vault provider does for the generic secret resource. Instead it reads from state because not all paths can be read:

https://github.com/hashicorp/terraform-provider-vault/blob/865bc2ac7be3abb47998225a5a4b6cdcde4ae28b/vault/resource_generic_secret.go#L57-L62

https://github.com/hashicorp/terraform-provider-vault/blob/865bc2ac7be3abb47998225a5a4b6cdcde4ae28b/vault/resource_generic_secret.go#L200-L206

As for implementing deletes I think it might work if each keystore entry is treated as a single resource instead of trying to combine them all into a single resource. So something like:

```tf
resource "ec_deployment_elasticsearch_keystore" "slack" {
  deployment_id = ec_deployment.cluster.id
  setting_name  = "xpack.notification.slack.account.monitoring.secure_url"
  value         = data.vault_generic_secret.slack_webhook.data.slack_url
}

resource "ec_deployment_elasticsearch_keystore" "pagerduty" {
  deployment_id = ec_deployment.cluster.id
  setting_name  = "xpack.notification.pagerduty.account.my_pagerduty_account.secure_service_api_key"
  value         = data.vault_generic_secret.pagerduty.data.api_key
}
```

Having them like this will give each entry a stable id instead of having to diff. That way the delete function would now just be patching that keystore property to empty like in the example here: https://www.elastic.co/guide/en/cloud-enterprise/2.4/set-es-cluster-keystore.html#ece_request_example_65

This approach also has the added bonus of being able to define dependencies on single keystore items. For example having a Watcher alert that needs the Slack keystore item to be present before being created.

**Comment by Crazybus** [comment]
I took a go at making the chances necessary to implement the approach I described above in :point_up: https://github.com/elastic/terraform-provider-ec/issues/100#issuecomment-893297457. I made the changes based on the previous branch submitted initially:

https://github.com/elastic/terraform-provider-ec/compare/master...Crazybus:resource-es-keystore?expand=1

My changes are in commit https://github.com/elastic/terraform-provider-ec/commit/3eb41fdfda7b4992d679ed40dd157e1937d4c81c. It looks like the idea should work as I was able able to get everything working as expected:

* Supports renaming of keystore items (properly destroys the old one and creates the new path)
* Detects keystore items that are deleted in Cloud (closest thing we can get to drift detection)
* Deletes the resource when it is removed

If the direction looks good I can polish things up to make it PR worthy. If Elastic Cloud APIs were to be updated to return the secret values it would be a single line change to also detect drift on the value.

**Comment by simon-schneider-gcx** [comment]
It would be nice to have a force update flag, which ensures the resource gets updated everytime terraform plan/apply is executed. This would allow to update the value "manually" when needed.

**Comment by Crazybus** [comment]
> It would be nice to have a force update flag, which ensures the resource gets updated everytime terraform plan/apply is executed. This would allow to update the value "manually" when needed.

Do you have any examples of how other providers supporting this? I would have thought that this is something Terraform core generally handles. So instead I think you should be force updating using `terraform taint` and in the latest version `terraform apply -replace="ec_deployment_elasticsearch_keystore.slack[0]"`. https://www.terraform.io/docs/cli/commands/taint.html

> I think @Crazybus Idea is the best solution which can currently be implemented, without changing the API.

Thanks! I think so as well. The previous attempt of of managing all keystore items under a single resource would only work nicely with Terraform if the API was updated to be fully authoritative/idempotent. If the approach looks good to the maintainers I'll work on submitting a proper PR :)

**Comment by marclop** [comment]
@Crazybus your proposal sounds good, I do not see any downsides to managing each individual secret as its own and it would alleviate this pain point. I'm happy to review your PR once you've polished the approach and help you in any way I can.

@AlexP-Elastic mentioned that we might add the ability to specify keystore secrets on the create / update deployment API call, no harm adding this resource but we might also add the ability to set secrets on creation / update directly without needing additional API calls.

**Comment by AlexP-Elastic** [comment]
@marclop thanks for the ping - so if something like https://github.com/elastic/terraform-provider-ec/issues/100#issuecomment-893297457 was implemented, at what point in the deployment lifecycle would it be applied? (One of the drivers - maybe the only one? - for potentially adding keystore entries on create was to have a single declaration for an ES cluster including their snapshot repo)

**Comment by marclop** [comment]
@AlexP-Elastic the secrets would be created after the deployment has been created so it doesn't apply to the conversation we had on slack about having the secrets created as part of the deployment creation.

**Comment by AlexP-Elastic** [comment]
@marclop excuse my terraform ignorance .. would you have a single declaration like:

```
deployment {
   elasticsearch {
      //size etc
   }

  my_keystore_entry {
     //value
  }
}
```

And then the sequence of events would be:
* creates deployment + ES
* once ES is up, updates keystore

If so, could the Elastic Cloud terraform be combined with something like: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/snapshot_repository (or we could add a few extra primitives)

And then the combo of keystore + ES + snapshot would mean that once the terraform reconciliation was complete the terraform user would have everything they wanted?

**Comment by marclop** [comment]
We're not going after the single declaration under the `ec_deployment` resource, but rather we are opting in favor of creating a new resource named `ec_deployment_elasticsearch_keystore `, like @Crazybus specified in [his comment](https://github.com/elastic/terraform-provider-ec/issues/100#issuecomment-893297457).

We'd only opt to add a block into the deployment itself if the deployment request / response models were updated to include Elasticsearch keystore secrets.

**Comment by AlexP-Elastic** [comment]
@marclop how does the dependency management work, eg the `ec_deployment_elasticsearch_keystore` references `ec_deployment.cluster.id`, which presumably gets filled in when a resource called `ec_deployment` is created, but what is the mechnanism for knowing its API is available?

**Comment by marclop** [comment]
@AlexP-Elastic we do not use the Elasticsearch API directly but rather the V1 Deployment API that exposes the Elasticsearch Keystore calls. The `ec_deployment_elasticsearch_keystore ` resource references the Deployment ID (`ec_deployment.my_deployment.id`) rather than the Elasticsearch Resource ID.

So whenever a deployment change (plan) finishes, then the `ec_deployment_elasticsearch_keystore ` will do the relevant work and call the relevant APIs.

**Comment by marclop** [comment]
@Crazybus I'll take your initial implementation, update some details and create a PR if you don't mind.

**Comment by Crazybus** [comment]
@marclop go for it! One small known issue is that the state ID I was using won't be unique if there are multiple deployments in the same Terraform environment.

Talking about here:
[`master...Crazybus:resource-es-keystore?expand=1`#diff-f94523fee8](https://github.com/elastic/terraform-provider-ec/compare/master...Crazybus:resource-es-keystore?expand=1#diff-f94523fee8ab437f9c35f35ca08a3e068eaa756e9a77bdc57b1ae0915bef5fcfR45)

This line should be more along the lines of `d.SetId(deploymentID + settingName)`.

**Comment by marclop** [comment]
@Crazybus got it, will take a look and fix what's needed, in the past we've resorted to hashing the deployment and rule that's being associated and storing that: https://github.com/elastic/terraform-provider-ec/blob/016ff5c0ec82b5343a9525b50d46b9146a698836/ec/ecresource/trafficfilterassocresource/create.go
