### ISSUE TITLE
ec_deployment: Make acceptance test fields dynamic

### ISSUE THREAD

**Issue by marclop** [elastic/terraform-provider-ec#11]
## Description

Currently the acceptance tests for `ec_deployment` uses hardcoded  fields like:

* version (`7.6.2`)
* region (`us-east-1`)
* deployment_template_id (`aws-io-optimized`) and their instance configurations, Elasticsearch, Kibana and APM.

It would be best to make these parameters more dynamic depending on which region the tests are run in, and if run against an ECE environment should also work.

**Comment by karencfv** [comment]
Putting this on hold until https://github.com/elastic/terraform-provider-ec/pull/98 is merged as there are a few changes that impact the work being done here :)

**Comment by marclop** [comment]
Also reading the issue again, I think we shouldn't make the version too dynamic, what we're doing works pretty well, but we could use the `ec_stack` data source to get the stack version.
