### ISSUE TITLE
ec_deployment/ec_deployment_traffic_filters not being re-created after resource id missing

### ISSUE THREAD

**Issue by Kushmaro** [elastic/terraform-provider-ec#123]
In common terraform providers (mainly looked at the AWS one), when a resource is missing from the cloud provider, but exists in the tfstate files, that resource would be recreated upon re-applying the TF configuration, so that state is consistent.

The flow goes something like this:
- terraform creates a resource (terraform apply was run)
- Resource gets deleted in the cloud provider (manually, for example)
- when terraform apply runs again, detects missing resource
- terraform re-creates the resource

This is the case with our provider:
- I terraform applied a deployment
- deleted it in the cloud console manually
- re-applying the configuration outputs this plan:
```
  # ec_deployment.example_minimal will be updated in-place
  ~ resource "ec_deployment" "example_minimal" {
        deployment_template_id = "aws-io-optimized-v2"
        elasticsearch_password = (sensitive value)
        elasticsearch_username = "elastic"
        id                     = "6c070ebed1c7166b9f287f76d2805889"
        name                   = "my_example_deployment"
        region                 = "us-east-1"
        traffic_filter         = [
            "2269062245fd430eb8d07d538a4255b7",
        ]
        version                = "7.9.2"

      + elasticsearch {
          + ref_id = "main-elasticsearch"

          + topology {
              + instance_configuration_id = "aws.data.highio.i3"
              + size                      = "8g"
              + size_resource             = "memory"
            }
        }

      + kibana {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + ref_id                       = "main-kibana"

          + topology {
              + instance_configuration_id = "aws.kibana.r5d"
              + size                      = "1g"
              + size_resource             = "memory"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
I'm guessing this is due to the object still being available (in terms of ID) but in a shutoff state?
In any case, we should treat this case.

When re-applying the file, it says its modifying the resource, but nothing seems to happen.
cloud UI doesn't present the original deployment again.

resulting TF error after the second apply:
![image](https://user-images.githubusercontent.com/10343929/95855024-766fec00-0d60-11eb-9fde-a5426769dfb7.png)

Seems this is also the case with ec_deployment_traffic_filters

## Expected Behavior
Either the original deployment should be 'restored' (i.e, turned on) or be re-created if it's ID doesn't exist anymore.

## Use case
The use case where fixing this behaviour would be super useful is with disaster recovery for ECE.
importing a deployment & its configuration, then recreating it in a different ECE environment since it's missing.

**Comment by marclop** [comment]
This was actually fixed as part of #194
