### ISSUE TITLE
Placeholder in Elastic docs for provider documentation

### ISSUE THREAD

**Issue by karencfv** [elastic/terraform-provider-ec#145]
## Description
Create a placeholder in the official Elastic docs containing contextual 
info for the new Terraform functionality, and a link pointing to the official
Terraform providers registry docs.

**Comment by karencfv** [comment]
cc @nrichers @alaudazzi

**Comment by nrichers** [comment]
OK, so there will be two things we need before I can open a PR to add a new book to our docs: 

1. A link to our docs on the Terraform providers site from @karencfv once you have sorted that out with Hashicorp.
2. A @Kushmaro-approved blurb we can use as introductory text for our new Terraform Provider for Elastic Cloud.

When you are ready with these things, please add them to this issue.

**Comment by nrichers** [comment]
In terms of placement, we could add the new book here: 

![image](https://user-images.githubusercontent.com/15148011/96756143-7edfac80-1388-11eb-9479-ba336c8aa566.png)

**Comment by karencfv** [comment]
Thanks @nrichers ! We'll let you know about the link to the registry once we have it, but looking at other self hosted providers, it looks like our link will be https://registry.terraform.io/providers/elastic/ec/latest/docs .

I think when you wrote "@Kushmaro-approved" it didn't ping @Kushmaro , so I'm pinging him now 😄 . @nrichers when you say the blurb should be approved by Omer, do you mean the cloud writers will write the blurb and have it approved by him? Or do you need one of us to write it?

**Comment by karencfv** [comment]
🔔 Ping! @nrichers

**Comment by alaudazzi** [comment]
@karencfv is there anything I can help with? @nrichers is out this week.

**Comment by nrichers** [comment]
> @nrichers when you say the blurb should be approved by Omer, do you mean the cloud writers will write the blurb and have it approved by him?

The messaging should match what the PMs would like to see for the new Terraform provider. So the basic text or talking points should come from @Kushmaro, unless you want us to make something up. 

(As @alaudazzi says, I'm out this week moving house; if you need something this week, just work with her, but I can pick this up again when I'm back Monday.)

**Comment by karencfv** [comment]
Thanks @alaudazzi and @nrichers! No rush on this issue at the moment. :) 

I'll keep an eye out on this, and I can write up something if everyone is super busy. I'll confirm with @Kushmaro.

**Comment by alaudazzi** [comment]
Thank you @karencfv! That would be great. I'll be happy to review.

**Comment by nrichers** [comment]
I opened a couple of related PRs and tagged folks for review:

* https://github.com/elastic/terraform-provider-ec/pull/163—add the content we need to build
* https://github.com/elastic/docs/pull/1995—build the content as a new book published on elastic.co
