### ISSUE TITLE
ec_deployments: Add a deployment status filter

### ISSUE THREAD

**Issue by ggsood** [elastic/terraform-provider-ec#164]
Hi all

the terraform data resource "ec_deployments" is not returning the deployments if 
- the deployment is healthy but with warning
- has last configuration change failed.

- [x] I am running different versions of Elasticstack on cloud
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
data "ec_deployments"  should have a filter to return all the running deployments even if there are warnings.

## Current Behavior
In case of CCS clusters, data "ec_deployments" is used to fetch all the deployment ids, the issue arises if deployment has some warning, the resource will not return that id and and subsequent consumers of the data will be updated which may lead to disruption

## Possible Solution
Add a stopped/running filter to ec_deployments resource similar to the UI console to return all the deployments.

## Steps to Reproduce
1. Have a deployment with healthy but with warnings status
2. Run data ec_deployments resource
3. List does not contain the deployment id.

## Context
CCS clusters are affected which rely on this data source to get the deployment ids.

**Comment by karencfv** [comment]
Thanks for the issue, this is a really good idea @ggsood. I've added it to our backlog.

**Comment by karencfv** [comment]
@ggsood Thinking about it a bit more we already have the `status` checks for each of the resource kinds. So if, for example, you wish to filter deployments based on `running` status you can do the following:

```
data "ec_deployments" "example" {
  elasticsearch {
    status = "running"
  }

  kibana {
    status = "running"
  }
}
```

Is this enough for your use case?

**Comment by ggsood** [comment]
Hi @karencfv thanks for providing the suggestion, unfortunately i have tested this filter and it returned me only the healthy clusters, also please can you suggest how i can apply these filters in the UI console, can't find the filter 😭

**Comment by karencfv** [comment]
No worries :) In the "Possible solution" section for this issue you mention:

> Add a stopped/running filter to ec_deployments resource similar to the UI console to return all the deployments.

This "filter" already exists within each of the resource kind blocks (`elasticsearch`, `kibana`, `apm` and `enterprise_search`). It's the `status` field. You can filter based on all the different statuses of each resource kind (`initializing`, `stopping`, `stopped`, `rebooting`, `restarting`, `reconfiguring` and `started`). In the example I gave you, you would get a list of deployments that have both Elasticsearch and Kibana in a "running" state. 

If, for example, you wish to filter based on Elasticsearch clusters being in a `stopped` state you would do the following:
```
data "ec_deployments" "example" {
  elasticsearch {
    status = "stopped"
  }
}
```

The UI has filters set a bit differently than the provider, bout you can find them here 
![Screen Shot 2020-11-04 at 4 58 58 PM](https://user-images.githubusercontent.com/7670244/98067745-20094f80-1ebf-11eb-8123-c58da3d2b655.png)

**Comment by ggsood** [comment]
Thanks @karencfv this helps 🥇

**Comment by karencfv** [comment]
Glad that helped! I'll be closing this issue then, as the solution to the issue already exists.
