### ISSUE TITLE
ec_deployment_traffic_filter_association is not reflecting in ec_deployment

### ISSUE THREAD

**Issue by wgebis** [elastic/terraform-provider-ec#204]
## Expected Behavior
After `ec_deployment_traffic_filter_association` creation is expecting that `ec_deployment.traffic_filter` will be reflected by the associations.

## Current Behavior
After `ec_deployment_traffic_filter_association` another `terraform plan/apply` detects changes at `ec_deployment.traffic_filter` as follows:
```
traffic_filter         = [
          - "7e47c1313c174e0ea93a98bf80dbff80",
          - "a8c1134a5bc24fd6a06b43ad7c7eb45c",
        ]
```
Applying above removes associations and it's continuing endlessly.  

## Possible Solution
Proper handling of `ec_deployment.traffic_filter` presence.

## Steps to Reproduce
1. Create any `ec_deployment_traffic_filter_association`
2. Run `terraform plan/apply` 
3. Change is detecting as above.

## Your Environment
* Version used: 0.1.0-beta
* Operating System and version: macOS

**Comment by marclop** [comment]
Hi @wgebis have you read the documentation for the [`ec_deployment_traffic_filter_association`](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment_traffic_filter_association). There it states:

```
Note on traffic filters

If you use traffic_filter on an ec_deployment, Terraform will manage the full set of traffic rules for the deployment, and treat additional traffic filters as drift. For this reason, traffic_filter cannot be mixed with the ec_deployment_traffic_filter_association resource for a given deployment.
```

Additionally, on the [`ec_deployment`](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment) resource documentation, it states the following:

```
Note on traffic filters

If you use traffic_filter on an ec_deployment, Terraform will manage the full set of traffic rules for the deployment, and treat additional traffic filters as drift. For this reason, traffic_filter cannot be mixed with the ec_deployment_traffic_filter_association resource for a given deployment.
```

Using a `ec_deployment_traffic_filter_association` should only be used for deployments outside of the scope of the Terraform Provider.

I hope this clarifies what you're seeing.

**Comment by marclop** [comment]
@wgebis Did you have a chance to take a look at my comment'

**Comment by wgebis** [comment]
Yeah, thanks @marclop fof clarification. So it case of handling ec deployment entirely in TF matching filters shroud be done as a part of ec deployment resource 👍. Makes sense.

**Comment by marclop** [comment]
Great, I'm closing this issue then if there aren't any more concerns or questions.
