### ISSUE TITLE
ec_deployment: Add support for newly added tags

### ISSUE THREAD

**Issue by marclop** [elastic/terraform-provider-ec#213]
## Overview

Tagging deployments is now possible with the addition of the `metadata.tags` list which allows us to specify an arbitrary list of k/v tags.

## Possible Implementation

Two possible implementations come to mind, either implementing this feature as a list of tags or as maps.

### Implement as map (abstracted from the API)

```hcl
resource "ec_deployment" "example" {
  # ... config [..]

  tags = {
    key   = "value"
    owner = "marc"
    team  = "my-team"
  }
}
```

### Implement as tag list (closer to the API)

```hcl
resource "ec_deployment" "example" {
  # ... config [..]

  tag {
    key   = "owner"
    value = "marc"
  }

  tag {
    key   = "team"
    value = "my-team"
  }
}
```

The map implementation has an advantage over the list of tags since it's more compact and less verbose.

**Comment by Kushmaro** [comment]
IMHO, impl #1 would be best in this case since its very intuitive. The latter reminds me of how AWS implements tags in their API which is, IMHO, one of the most annoying things in their API 😅
