### ISSUE TITLE
Creating multiple nodes on multiple zones

### ISSUE THREAD

**Issue by renatosis** [elastic/terraform-provider-ec#222]
## Question

Hi, We're planning on using the ec_provisioner to create our Elastic Cluster on Elastic Cloud but we're experiencing some "possible" problems when executing terraform apply. We have configured the terraform as follows:

```
resource "ec_deployment" "homolog_terraform" {
  name = "homolog_terraform"
  region                 = "us-east-1"
  version                = "7.10.1"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      zone_count                = 2
      size                      = "1g"
      instance_configuration_id = "aws.data.highio.i3"
      node_type_master          = true
      node_type_ingest          = false
      node_type_data            = true
    }
    topology {
      zone_count                = 2
      size                      = "1g"
      instance_configuration_id = "aws.data.highio.i3"
      node_type_master          = false
      node_type_ingest          = false
      node_type_data            = true
    }
  }

  kibana {
    topology {
      zone_count                = 1
      size                      = "1g"
      instance_configuration_id = "aws.kibana.r5d"
    }
  }
}
```

We noticed this error:

Error: failed updating deployment: 1 error occurred:
	* api error: clusters.cluster_invalid_plan: Cluster must contain at least a master topology element and a data topology element. 'master' node type is missing,'master' node type exists in more than one topology element (resources.elasticsearch[0].cluster_topology)

1- Is this the correct way to create multiple nodes on multiple zones?
2- In this doc (https://www.elastic.co/guide/en/cloud-enterprise/2.1/ElasticsearchClusterTopologyElement.html) we've noticed that it's possible to create more than one node per zone (node_count_per_zone) but it isn't available using provider-ec, correct?

Thank you very much

Kind regards

Renato Isidio

**Comment by karencfv** [comment]
Thank you for opening up this issue and the great detail @renatosis 🙂. For the time being the provider does not support `node_count_per_zone`, which means you cannot use other values other than the default. I will add this issue to the backlog.

**Comment by karencfv** [comment]
Ah! so looking further into this I realised the `node_count_per_zone` field is only editable for our Elastic Cloud Enterprise users. On our hosted Elastic Cloud the only way to have several nodes per zone is done automatically if the size you have defined is larger that the largest available memory size for the `instance_configuration_id` you have set (available sizes for each instance ID can be found [here](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html)).

Using your example which uses `aws.data.highio.i3`, you can see on the list of available instances the the available sizes are 1g, 2g, 4g, 8g, 15g, 29g and 58g. This means that in order to have 2 nodes in each zone you would have to set the `size` value to `116g`.

```hcl
resource "ec_deployment" "example_minimal" {
  region                 = "us-east-1"
  version                = "7.10.1"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      size = "6g"
    }
  }

  kibana {}
}
```

The documentation link you posted is for the Elastic Cloud Enterprise documentation. The hosted Elastic Cloud API is a little different, the documentation for the API you need can be found here https://www.elastic.co/guide/en/cloud/current/ec-restful-api.html

**Comment by renatosis** [comment]
Hi Karen,

Firstly I want to thank you for your quick answer. I really appreciated it! =)
I did some tests here and it worked configuring the way you recommended us! How could we create different topologies to different node types. 
E.g.: 
2 masters with 1gb mem
3 data with 58gb mem

I tried applying the configuration I've sent you before but the error I got was that "master node type exists in more than one topology element" which was not true given the different parameters for each topology.

Again, thank you so much

**Comment by karencfv** [comment]
Glad the information helped @renatosis :)

I am assuming what you want is to have 2 1gb masters and 3 58gb data for **each zone**.

For the masters: Since 2gb (the sum of the two master nodes you wish to have) is not larger that the largest available memory size for the `instance_configuration_id`, you cannot have more than one node. In this case you would need to have a single 2gb master.

For the data node types: The sum of 3 58gb nodes is 174gb so this is the value you would use.

```hcl
resource "ec_deployment" "example" {
  region                 = "us-east-1"
  version                = "7.10.1"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      instance_configuration_id = "aws.master.r5d"
      size = "2g"
      node_type_master          = true
      node_type_ingest          = false
      node_type_data            = false
    }

    topology {
      instance_configuration_id = "aws.data.highio.i3"
      size = "174g"
      node_type_master          = false
      node_type_ingest          = true
      node_type_data            = true
    }
  }

  kibana {}
}
```

I've found that a good way to figure these values out is to use our [UI](https://cloud.elastic.co/deployments/create) as reference. You can use the `Customize` button at the bottom of the page to visualize your cluster and then click on the `Equivalent API request` link below the `Create deployment` button to see how the values are defined.

I hope this helps!

**Comment by renatosis** [comment]
Hi @karencfv,

thank you for your quick reply and all your help! I've been trying to apply this configuration but I always get this error: "master node type exists in more than one topology element".

Kind regards

**Comment by renatosis** [comment]
```
Error: failed updating deployment: 1 error occurred:
	* api error: clusters.cluster_invalid_plan: Cluster must contain at least a master topology element and a data topology element. 'master' node type is missing,'master' node type exists in more than one topology element (resources.elasticsearch[0].cluster_topology)
```

**Comment by karencfv** [comment]
Happy to help @renatosis :) 

hmm 🤔 I have just created a deployment with what I sent earlier as an example and it worked fine.

```shell
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ec_deployment.example_minimal will be created
  + resource "ec_deployment" "example_minimal" {
      + apm_secret_token       = (sensitive value)
      + deployment_template_id = "aws-io-optimized-v2"
      + elasticsearch_password = (sensitive value)
      + elasticsearch_username = (known after apply)
      + id                     = (known after apply)
      + region                 = "us-east-1"
      + version                = "7.10.1"

      + elasticsearch {
          + cloud_id       = (known after apply)
          + http_endpoint  = (known after apply)
          + https_endpoint = (known after apply)
          + ref_id         = "main-elasticsearch"
          + region         = (known after apply)
          + resource_id    = (known after apply)
          + version        = (known after apply)

          + topology {
              + instance_configuration_id = "aws.master.r5d"
              + node_type_data            = "false"
              + node_type_ingest          = "false"
              + node_type_master          = "true"
              + node_type_ml              = (known after apply)
              + size                      = "2g"
              + size_resource             = "memory"
              + zone_count                = (known after apply)
            }
          + topology {
              + instance_configuration_id = "aws.data.highio.i3"
              + node_type_data            = "true"
              + node_type_ingest          = "true"
              + node_type_master          = "false"
              + node_type_ml              = (known after apply)
              + size                      = "174g"
              + size_resource             = "memory"
              + zone_count                = (known after apply)
            }
        }

      + kibana {
          + elasticsearch_cluster_ref_id = "main-elasticsearch"
          + http_endpoint                = (known after apply)
          + https_endpoint               = (known after apply)
          + ref_id                       = "main-kibana"
          + region                       = (known after apply)
          + resource_id                  = (known after apply)
          + version                      = (known after apply)

          + topology {
              + instance_configuration_id = (known after apply)
              + size                      = (known after apply)
              + size_resource             = (known after apply)
              + zone_count                = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ec_deployment.example_minimal: Creating...
ec_deployment.example_minimal: Still creating... [10s elapsed]
<...>
ec_deployment.example_minimal: Creation complete after 3m58s [id=4f110411fe6da4d8b075e9a0c7f41163]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Could you paste the contents of your .tf file here so we can further debug?

**Comment by renatosis** [comment]
Hi @karencfv ,

I really appreciate your help! Thank you.
In fact, when applying our configuration we noticed that error and we thought that it would be the master/data configuration. Actually, when applying your config it worked. Then we noticed that the only thing that was different was the node type (instance_configuration_id). After changing our master topology to "aws.master.r5d" we had success.
I think it's important for the project to change the error message when the incorrect type is set.
Can we use the provider-ec to create ILM policies, templates, kibana settings?

Thank you

**Comment by karencfv** [comment]
Glad it worked @renatosis :) 

I can see why the error message could be confusing. Unfortunately this error message is directly from the API so we cannot change it within the TF provider. I will pass on this feedback to the relevant team.

Creating deployment templates is not an action that is available to our hosted Elastic Cloud customers but you can definitely edit your settings through the `config` block in each of the deployment resource kinds (`elasticsearch`, `kibana`, `apm` and `enterprise_search`). You can find the information on how to use those `config` blocks in our `ec_deployment` resource [documentation](https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment.md).

I will close this issue now as the initial question has been resolved. Thanks again for providing feedback!
