### ISSUE TITLE
ec_deployment: Support elasticsearch user_bundles and user_plugins

### ISSUE THREAD

**Issue by marclop** [elastic/terraform-provider-ec#224]
## Overview

After #216 is merged, some work needs to be done on the `ec_deployment` resource to allow users to specify `user_bundles` and `user_plugins` in the API calls.

## Possible Implementation

There's two ways that we can implement this as part of our provider schema, keeping the schema close to our API models or diverge to provide a more generic "extension" abstraction.

### Copying what our API does

```hcl
resource "ec_deployment" "plugins" {
  name                   = "user-plugins"
  region                 = "us-east-1"
  version                = "7.10.1"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      size = "2g"
    }

    user_plugin {
        version = "7.10.1"
        name    = "my_plugin"
        url     = "some-url"
    }

    user_plugin {
        version = "7.10.1"
        name    = "my_second_plugin"
        url     = "some-second-url"
    }

    user_bundles {
        version = "7.10.1"
        name    = "my_bundle"
        url     = "some-url"
    }

    user_bundles {
        version = "7.10.1"
        name    = "my_second_bundle"
        url     = "some-second-url"
    }
  }
}
```

### API Diversion

Instead of creating two different fields in the schema and mapping them to the exact API field, we could just add a single field `extension` with a `type` string field which can be set to `plugin` or `bundle`.

```hcl
resource "ec_deployment" "plugins" {
  name                   = "user-plugins"
  region                 = "us-east-1"
  version                = "7.10.1"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      size = "2g"
    }

    extension {
        type    = "plugin"
        version = "7.10.1"
        name    = "my_plugin"
        url     = "some-url"
    }

    extension {
        type    = "plugin"
        version = "7.10.1"
        name    = "my_second_plugin"
        url     = "some-second-url"
    }

    extension {
        type    = "bundle"
        version = "7.10.1"
        name    = "my_bundle"
        url     = "some-url"
    }

    extension {
        type    = "bundle"
        version = "7.10.1"
        name    = "my_second_bundle"
        url     = "some-second-url"
    }
  }
}
```

**Comment by Kushmaro** [comment]
++ looks  great.
Just want to verify a question I have though: 
- If a user doesn't enter a URL, will the URL be automatically be generated and returned? (i.e computed?)

**Comment by marclop** [comment]
@Kushmaro the URL will be required, to create the extension and upload the bundle or plugin the `ec_deployment_extension` can be used and the [`url` attribute](https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment_extension.md#attributes-reference) can be used.
