### ISSUE TITLE
Region [ca-central-1] was not found

### ISSUE THREAD

**Issue by molodchenko** [elastic/terraform-provider-ec#227]
## Current Behavior
After terraform apply got the error:

Error: api error: 1 error occurred:
	* templates.region_not_found: Region [ca-central-1] was not found

## Terraform definition
```
resource "ec_deployment" "my_deployment" {
  name = "my_deployment"

  version                = "7.10.1"
  region                 = "ca-central-1"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      instance_configuration_id = "aws.data.highio.i3"
      size = "2g"
    }
  }

  kibana {
    topology {
      instance_configuration_id = "aws.kibana.r5d"
      size = "1g"
    }
  }

  apm {
    topology {
      instance_configuration_id = "aws.apm.r5d"
    }
  }
}
```

## Steps to Reproduce

terraform apply

## Context
The current provider version doesn't support  [ca-central-1] region in AWS

## Your Environment
* Terraform: v0.13.6
* provider : "0.1.0-beta"

**Comment by karencfv** [comment]
Hi @molodchenko! 

The region name in Elastic Cloud for that region is `aws-ca-central-1`. You can find all of our available regions, deployment templates and instance configurations in this page https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html
