### ISSUE TITLE
`elasticsearch.config.plugins` does not work

### ISSUE THREAD

**Issue by arbourd** [elastic/terraform-provider-ec#230]
example.tf
```hcl
  elasticsearch {
    config {
      plugins = ["analysis-icu"]
    }

    topology {
      size       = "1g"
      zone_count = 2
    }
  }
```

terrform diff
```diff
~ elasticsearch {
      # (7 unchanged attributes hidden)

    + config {
        + plugins = [
            + "analysis-icu",
          ]
      }

      # (1 unchanged block hidden)
  }
```

## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Adds analysis-icu like it says it does.

## Current Behavior

Doesn't add analysis-icu, and if it already is present on the cluster, **it will remove it**.

<img width="539" alt="Screen Shot 2021-01-18 at 4 28 21 PM" src="https://user-images.githubusercontent.com/7211830/104964339-39904280-59aa-11eb-9010-e9dd174f4b17.png">

## Your Environment

* Version used: 0.1.0-beta
I did not build from source, this is your binary running in Terraform Cloud.

**Comment by arbourd** [comment]
It seems that the **topology** specific option is not being set, but the overall stack option is. How do we set the topology specific option?

**Comment by arbourd** [comment]
Actually, it appears that after _recreating the topology_, `analysis-icu` is there but not in the GUI. I imagine because the frontend looks at a different chunk of the API response.

**Comment by wouter-toppy** [comment]
@arbourd i have the same issue, its not setting it on the the instance. how did you solve this?

**Comment by arbourd** [comment]
@wouter-toppy are you using the Terraform provider?

If you create a new instance with the TF provider and it is properly set _it will work_ but it won't appear on the web UI.

**Comment by wouter-toppy** [comment]
@arbourd 

im using this:

```tf
terraform {
  required_version = ">= 0.13"
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.1.0-beta"
    }
  }
}

provider "ec" {}

resource "ec_deployment" "elastic_search" {
  name      = "${local.prefix}-${lower(var.environment)}-deployment"

  version                 = var.elasticsearch_version
  region                  = var.elasticsearch_region
  deployment_template_id  = var.elasticsearch_deployment_template_id

  elasticsearch {
    topology {
      instance_configuration_id = var.elasticsearch_instance_configuration_id
      size                      = var.elasticsearch_size
      zone_count                = var.elasticsearch_zone_count
    }

    config {
      plugins = var.elasticsearch_plugins
    }
  }
}

```

where my vars are these:
```tf
  elasticsearch_version                   = "7.11.0"

  elasticsearch_region                    = "gcp-europe-west4"
  elasticsearch_deployment_template_id    = "gcp-io-optimized"
  elasticsearch_instance_configuration_id = "gcp.data.highio.1"

  elasticsearch_size                      = "2g"
  elasticsearch_zone_count                = "1"
  elasticsearch_plugins                   = [
    "analysis-icu",
    "analysis-phonetic",
    "ingest-geoip",
    "ingest-user-agent",
  ]
```

but if its true what you said that the plugins are enables but not visible in the GUI its fine for now. is there any way to verify that the plugins are actually enabled?

**Comment by arbourd** [comment]
> is there any way to verify that the plugins are actually enabled?

you can make an API call directly to get the settings. the easiest way i found to do this is the **Equivalent API request** button when editing a deployment. It will show you a JSON blob with the current settings. In our case:

```json
"elasticsearch": {
  "version": "6.8.14",
  "enabled_built_in_plugins": [
    "analysis-icu"
  ]
}
```

**Comment by wouter-toppy** [comment]
@arbourd yeah, I already saw that entry there, but when I set the plugins via the GUI is see the plugin namens on more places in the json, but I guess than its working propertly ;-) 

Thanks for the explaination ;-)

**Comment by arbourd** [comment]
According to [this comment](https://github.com/elastic/terraform-provider-ec/issues/214#issuecomment-763525721) the provider sets configuration at a global space, but the UI does it per instance.

I think the fix they might do is improve the UI so our changes are reflected.
