### ISSUE TITLE
https_endpoint port selection 9243 vs 443

### ISSUE THREAD

**Issue by wimo7083** [elastic/terraform-provider-ec#233]
## Question

I'm not sure if this is a feature request or a question. This is regarding the response of the resources when trying to access the https_endpoint attribute- `ec_deployment.my_deployment.elasticsearch.#.https_endpoint`

When creating a cluster the provision actions allow connecting to multiple ports.
- `https://<INSTANCE>.us-central1.gcp.cloud.es.io:443`
- `https://<INSTANCE>.us-central1.gcp.cloud.es.io:9243`

You have unit tests verifying both exist, and that the response is one or the other.

```bash
ec/ecresource/deploymentresource/flatteners_test.go
61:                             "https_endpoint":               "https://1235d8c911b74dd6a03c2a7b37fd68ab.apm.eastus2.azure.elastic-cloud.com:443",
72:                             "https_endpoint": "https://1238f19957874af69306787dca662154.eastus2.azure.elastic-cloud.com:9243",
95:                             "https_endpoint":               "https://1235cd4a4c7f464bbcfd795f3638b769.eastus2.azure.elastic-cloud.com:9243",
125:                            "https_endpoint":               "https://12328579b3bf40c8b58c1a0ed5a4bd8b.apm.eu-central-1.aws.cloud.es.io:443",
....
```

Does the https_endpoint always return 9243 or does it sometimes return 443 in the data or resource?

Is there a way to have this port be configurable (not necessarily the port that is created) but specify which of the two is always returned?

I practice very restrictive firewall rules and restrict all access but what is necessary. In this case, If port 443 suffices and I'd prefer to use that rather than have to manage both 443 and 9243.

**Comment by marclop** [comment]
Hi @wimo7083 theet are indeed two ports that can be used to access _different_ applications of a deployment. `443` maps to APM server of a deployment while `9243` maps to the SSL socket of the Elasticsearch cluster instances of a deployment.

The ports aren't configurable since it relies on a layer of proxies that sit in front of our deployments and route requests to these instances.

I hope this answers your question.

**Comment by wimo7083** [comment]
Understood, thank you for the clarification.
