### ISSUE TITLE
Add new resource to manage x_pack watcher

### ISSUE THREAD

**Issue by nathaliaceballoshurtado** [elastic/terraform-provider-ec#234]
## Overview

We currently have a lot of watchers configure in ElasticSearch, we dont have a way to track this without developers help, so we want a way to manage using serverless.

## Possible Implementation

We' re currently working on it

Adding a new resource 

## Testing

Unit tests are going to be implement 

## Context

We considered using phillbaker/elasticsearch but we work directly with Elastic Cloud and phillbaker is based authentication with aws credentials.

**Comment by marclop** [comment]
Hi @nathaliaceballoshurtado, unfortunately that feature that you're looking to add is outside of the scope and the context of this provider, let me explain why.

The Elastic Cloud Terraform provider will provide and maintain a contract (and expose Terraform resources) with the established Elastic Cloud API. Elasticsearch, Kibana and or APM (or any other Elastic applications) configurations are outside of what is available to configure through the Elastic Cloud API and should not and will not be exposed as Elastic Cloud Terraform resources.

For the purposes of what you'd like to do, it'd be better to use a dedicated Elasticsearch Terraform provider, unfortunately
we do not have an official Elasticsearch Terraform provider at the moment but are looking into what the best path forward is for these cases.

**Comment by phillbaker** [comment]
> We considered using phillbaker/elasticsearch but we work directly with Elastic Cloud and phillbaker is based authentication with aws credentials.

👋 I happened to see this, as a contributor to that package, the two providers should be complementary @nathaliaceballoshurtado. This provider can be used to manage the underlying cluster in elastic cloud (authentication using APIKEY). The [generated user/password](https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment.md#attributes-reference) is used to access the cluster itself using phillbaker/terraform-provider-elasticsearch with basic auth, [see the docs here](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs#username).
