### ISSUE TITLE
Elastic Cloud now supporting Data tiers for storage

### ISSUE THREAD

**Issue by ggsood** [elastic/terraform-provider-ec#240]
Hello all

With the recent changes in the Elastic cloud, there was introduction to data tiers in 7.11.

With this change, the hot warm template is now no longer a valid template.

How does it affect - The provider currently support hot warm deployments.

Hence raising a request for upgrading the provider to support data tiers as per the UI.

**Comment by marclop** [comment]
We're on it, we'll update the provider soon.

**Comment by marclop** [comment]
This is a dup of #212
