### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by w0ut0** [elastic/terraform-provider-ec#246]
## Overview
When can we expect a new release? There are some issues that have been fixed (thanks for that), but the last version was published 2 months ago.

## Possible Implementation
n/a

## Context
We are missing some bugfixes, like [this one](https://github.com/elastic/terraform-provider-ec/issues/203).

## Your Environment
We pull the provider from the [Terraform registry](https://registry.terraform.io/providers/elastic/ec/latest)

**Comment by marclop** [comment]
Hi @w0ut0,

We're working on a few more issues before we release a new version. We don't have a release date yet, but create a new release as soon as we're done with the issues in the `0.1.0-beta2` milestone.

**Comment by wgebis** [comment]
@marclop would you split the milestone into smaller ones? It's really needed...

**Comment by karencfv** [comment]
Hi @wgebis 👋 We also have the option to build the provider from source if you need the latest features/fixes. Check out  our [CONTRIBUTING.md doc](https://github.com/elastic/terraform-provider-ec/blob/master/CONTRIBUTING.md#build-terraform-provider-ec-locally-with-your-changes).

**Comment by wgebis** [comment]
@karencfv Yeah, it works locally, but put it in CI environment is not elegant 😞. 
BTW: Delivering new releases in smart portion of features/bugfixes is also better for getting a feedback from from community👍

**Comment by wgebis** [comment]
@marclop means that the new release is coming? 🤩 
<img width="1280" alt="Screenshot 2021-03-25 at 12 45 49" src="https://user-images.githubusercontent.com/32294473/112468018-0f6f4e00-8d68-11eb-8362-4938e0eeee79.png">

**Comment by marclop** [comment]
We're aiming to release next week, we still have a few things to draft on our end before we can release to the public.
