### ISSUE TITLE
Adding extension 

### ISSUE THREAD

**Issue by tallakh** [elastic/terraform-provider-ec#250]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

According to https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment_extension.md#attributes-reference, it should be possible to add a bundle to elastic cloud.

## Current Behavior

```
Error: Invalid resource type

  on searchplatform-elasticsearch.tf line 56, in resource "ec_deployment_extension" "dictionary_extension":
  56: resource "ec_deployment_extension" "dictionary_extension" {

The provider provider.ec does not support resource type
"ec_deployment_extension".
```

## Terraform definition

```
locals {
  file_path = "./files/dictionaries.zip"
}

resource "ec_deployment_extension" "dictionary_extension" {
  name           = "Dictionaries"
  description    = "File with dictionaries"
  version        = "*"
  extension_type = "bundle"

  file_path = local.file_path
  file_hash = filebase64sha256(local.file_path)
}
```

**Comment by karencfv** [comment]
Hi @tallakh 👋 Thanks for opening up this issue. This feature will be available in the next release :) For the current release it's best to check out the docs on the [`v0.1.0-beta` branch](https://github.com/elastic/terraform-provider-ec/tree/v0.1.0-beta).

If you want to use what's on master, you can use [these instructions](https://github.com/elastic/terraform-provider-ec/blob/master/CONTRIBUTING.md#build-terraform-provider-ec-locally-with-your-changes) to build the provider locally.

**Comment by marclop** [comment]
@tallakh I would also recommend using the documentation [published in the Terraform registry](https://registry.terraform.io/providers/elastic/ec/latest/docs) instead of what's in the `master` branch, as it contains changes which haven't yet been released and might be confusing to consume documentation this way.

**Comment by tallakh** [comment]
Thanks @karencfv and @marclop!

Do you have a time frame on when this functionality will be available in the released version?

**Comment by marclop** [comment]
We do not have an accurate timeframe yet for the next release, although we're to release it in the next month.

**Comment by tallakh** [comment]
Thanks for the update.
