### ISSUE TITLE
Error when upgrading a deployment without Kibana

### ISSUE THREAD

**Issue by Nighthawk14** [elastic/terraform-provider-ec#276]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Rolling upgrade should be performed

## Current Behavior

When updating an `ec_deployment` version number from `7.11.2` to `7.12.0` on a deployment without `kibana {}` object, Terraform fails to apply with this error message:
```
The [kibana] resource [main-kibana] requires SSO SAML realm configuration to be modified and must be included in the deployment payload
```

I have done the same update on a deployment that has a `kibana {}` object and the update was successful.

## Terraform definition

```
resource "ec_deployment" "elasticsearch" {
  name = "a name"

  region                 = var.region
  version                = "7.11.2"
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {
    topology {
      zone_count = 1
      size = "1g"
    }
  }

  enterprise_search {
    topology {
      zone_count = 1
    }
  }
}
```

## Steps to Reproduce

1. Create a deployment without kibana in version 7.11.2
2. Update the version number of that deployment to 7.12.0
3.
4.

## Context

Just trying to update one of my deployment to the latest version

## Your Environment

* Version used: 7.11.2 / 7.12.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by marclop** [comment]
That's a strange message, did you have a `kibana {}` block and removed it on the same apply as the upgrade? The error is coming back from the API and it might be a bug on our platform. Could you open a support ticket to get to the bottom of it?

**Comment by Nighthawk14** [comment]
Thanks @marclop .

The output of this command is `tolist([])`.
I used to have a Kibana instance but removed it a month ago and the deployment was updated multiple times between the removal of the Kibana instance and the version upgrade. I will open a support ticket with a link to that issue 👍🏻

**Comment by marclop** [comment]
@Nighthawk14 from what you describe, it is a strange error indeed, I'm not sure what happened there without having access to the deployment itself.

I only asked for the output of that command and the state contents to make sure that Terraform wasn't somehow creating a Kibana instance and persisting it to the state even when not explicitly set to do so

**Comment by Nighthawk14** [comment]
@marclop No worries and thanks for having a look at it. Let's see what's the outcome of the support ticket, I'll make sure to update this issue as well 👍🏻

**Comment by marclop** [comment]
@Nighthawk14 no worries, if you don't mind, I'll close this issue for now since there doesn't seem to be anything wrong with the provider itself, but do feel free to post updates or reopen if relevant.

**Comment by Nighthawk14** [comment]
@marclop So looks like disabling the Kibana instance completely should not be allowed as it is required to perform some Elasticsearch administrative functions (according to the Documentation https://www.elastic.co/guide/en/cloud/current/Deployment_-_Commands.html#shutdown-deployment-stateless-resource). So I guess it is an issue with the API allowing us to disable the Kibana instance completely. The person managing the case said that she will get in touch with the Cloud dev team to discuss it.

From the provider point of view, the `kibana {}` object should probably be mandatory then as that would also prevent users from disabling the Kibana instance.

**Comment by marclop** [comment]
We're going to discuss at length how to offer a more consistent experience across clients, meanwhile I've opened a PR (linked) that adds a word of caution to our public documentation.
