### ISSUE TITLE
when extension support will be released?

### ISSUE THREAD

**Issue by milesqi** [elastic/terraform-provider-ec#280]
Hi, we need to upload extension by using terraform, just wondering when this can be used? 
https://github.com/elastic/terraform-provider-ec/blob/master/examples/extension_bundle/extension.tf

**Comment by marclop** [comment]
You'll be able to use it with the upcoming `0.1.0` later this week.

**Comment by marclop** [comment]
[`v0.1.0`](https://github.com/elastic/terraform-provider-ec/releases/tag/v0.1.0) has been released and available for everyone to use.
