### ISSUE TITLE
Using v0.1.0 over v0.1.0-beta

### ISSUE THREAD

**Issue by RobDTech** [elastic/terraform-provider-ec#285]
Hi, how do we force the use of v0.1.0 instead of the beta? 
I've tried 
` version = "~>0.1.0"`
` version = "!= 0.1.0-beta"`
` version = "0.1.0, != 0.1.0-beta"`

With `terraform init -upgrade` but it always selects the beta.

Many thanks

**Comment by marclop** [comment]
Could you please post what version of Terraform you're using? I'm on `0.14.9` and it works just fine:

```console
$ terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding elastic/ec versions matching "~> 0.1.0"...
- Installing elastic/ec v0.1.0...
- Installed elastic/ec v0.1.0 (self-signed, key ID 7FE579EDEC6DAA7B)
```

you might have a `.terraform.lock.hcl` file which might somehow be fixing the version to `v0.1.0-beta`.

**Comment by RobDTech** [comment]
Thanks @marclop I've just found the issue. One of the modules was still referencing the beta.
