### ISSUE TITLE
Update an existing Elastic Cloud deployment

### ISSUE THREAD

**Issue by abbanabennanih** [elastic/terraform-provider-ec#292]
Hi,

I would like to know if it's possible to update an existing deployment on Elastic Cloud with Terraform Provider. When I set the cloud ID in my Terraform configuration, I have the following error:

> Computed attribute cannot be set
> 
> on deployment.tf line 14, in resource "ec_deployment" "cluster":
> 14: cloud_id = "*********"

The Terraform configuration:

```
resource "ec_deployment" "cluster" {
  name = var.cluster_name
  region                 = var.gcp_region
  version                = var.es_version
  deployment_template_id = var.deplyment_template_id
  elasticsearch {
    cloud_id = var.cluster_id
    topology {
      size = var.es_topology_size
      zone_count = var.es_topology_zone_count
    }
  }
}
```
Thank you

**Comment by karencfv** [comment]
Hi @abbanabennanih 👋  , you'll need to [import](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#import) the resource first, before updating it.

**Comment by Kushmaro** [comment]
@abbanabennanih , as mentioned above, you'll need to import the resource first.
This is how terraform works, it is not a bug with the Elastic Cloud provider.
