### ISSUE TITLE
Add App Search as manageable resource

### ISSUE THREAD

**Issue by Chanonry** [elastic/terraform-provider-ec#302]
Overview

Create terraform resource/s to replicate the App Search abstraction 

Context

The App Search abstraction is very effective in getting new users building powerful autoscaling search functionality. The console driven approach is great when prototyping but is has its dangers as replicating resources is a manual process.

We are building a web app and want to be able to innovate with search as the technology develops, particularly the web crawler functionality. As we progress through dev, test, stage, prod we want to be able to reproduce immutable resources accurately and rollback instantly.

We could probably do this (?) if we build our own cluster from available terraform resources but this implies a learning curve starting from zero and loses the benefit of the App Search abstraction for us, and presumably for elastic.co in terms of making it easy for new users to adopt the technology?

We need an IaaC approach that offers the power and the speed of the abstraction with the ability to reproduce the exact tuning of the resource. I am specifically thinking of synonyms, weights, bias etc. Autoscaling is a big attraction when starting out.

Environment

Currently we are building out stacks with Terraform through a GitHub Action workflow and want the ability to control all of our app resources in the same workflow.

**Comment by marclop** [comment]
hi @Chanonry,

AppSearch as an application has been superseded by Enterprise Search, which we fully support in the Terraform provider, I'm not sure I understand if there are any blockers to using the Terraform provider as is with an `enterprise_search` resource set.

**Comment by Kushmaro** [comment]
@Chanonry , If  I understand you correctly, what you're looking for is a terraform provider that configures appsearch / ent. search itself (like crawlers, etc), as code.

Is such a depiction correct?

**Comment by Chanonry** [comment]
Yes, spot on

**Comment by Chanonry** [comment]
Superseded ? Didn’t I watch a webinar a couple of weeks ago on the “new” service ?? Very good it was too.

I raised a query in the forum on whether I could create an AppSearch stack at that level of abstraction with IaaC plus use IaaC to capture synonyms, web crawling, weights etc etc. The suggestion was that there this was possible in part not full. so I should raise a feature request.  I am not sure what the position is, I like the product and want to get going as fast and as productively as possible. Struck me that would be a common view.

What I want to avoid is having to regress to a much lower level of abstraction to build a stack akin to what I can create with AppSearch through the console, ie I want to get going without having to learn how to expertly configure the stack etc.

If that is currently possible, can you point me at the resources which help me set it up?  Maybe that’s all it needs, dunno.

As I said the AppSearch abstraction is attractive as it takes away much of the learning curve for new customers like me and gets us into your eco system. If we want to get clever later on we can, but the initial barrier to entry has gone benefiting us both.
