### ISSUE TITLE
Multiple Kibana deployment support

### ISSUE THREAD

**Issue by milesqi** [elastic/terraform-provider-ec#303]
Hi, we're thinking to create two kibana instances within one cluster. I was trying to have two kibana sections in resource "ec_deployment" but it says only one is allowed. is multiple kibana instances supported by ec provider?

**Comment by korcadr** [comment]
increase zone_count in kibana.topology
kibana {
  topology {
    zone_count: 2
  }
}

**Comment by milesqi** [comment]
I meant multiple kibana instances (with different endpoints, not multiple nodes) so that I can apply different kibana_user-settings.yaml.

**Comment by marclop** [comment]
Hi @milesqi, we do not support multiple Kibana instances with different endpoints on Elastic Cloud or the Terraform provider.
