### ISSUE TITLE
Disable default Snapshot policy when creating a new deployment.

### ISSUE THREAD

**Issue by abbanabennanih** [elastic/terraform-provider-ec#306]
Hi,

When creating a new Elastic Cloud deployment, a default Snapshot policy (SLM) is created and enabled. In our development environments we don't need to snapshot data. I would like to know if it's possible to disable this default policy when creating a deployment?

Thank you.

**Comment by artemnikitin** [comment]
Unfortunately, it will not be possible to do through Terraform. Snapshots are configured using Elasticsearch built-in [SLM](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshot-lifecycle-management.html) feature. After deployment is created, you can configure it via UI (in Kibana) or directly via Elasticsearch [SLM API](https://www.elastic.co/guide/en/elasticsearch/reference/master/snapshot-lifecycle-management-api.html)
