### ISSUE TITLE
Published documentation for 0.1.1 is not up to date

### ISSUE THREAD

**Issue by andrey-dubnik** [elastic/terraform-provider-ec#310]
Hi

Out team is planing to enable the autoscaling and we have discovered the published doc in the registry and ec_deployment resource is missing the autoscaling feature documentation where it was actually delivered with 0.11 accordingly to the release commits

Documentation: https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment

Will there be a fix for that before the next release?

**Comment by marclop** [comment]
Hi Audrey, Autoscaling is still not released and will be the main feature added in `0.2.0`. The documentation is up to date with the last release (`0.1.1`) which didn't have any autoscaling.

We're planning to release `0.2.0` by the end of the month.

**Comment by andrey-dubnik** [comment]
Sorry, my bad. Thanks for the info, looking forward to 0.2.0
