### ISSUE TITLE
Document adding ML nodes

### ISSUE THREAD

**Issue by AntonChernysh** [elastic/terraform-provider-ec#317]
Looks like adding ML nodes is missing in the [documentation](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#topology).
I could only figure the right value when tried deployment with some dummy value for topology id, Terraform threw the list of  acceptable values: 
`'valid topology IDs are "coordinating", "hot_content", "warm", "cold", "frozen", "master", "ml"`
Whereas documentation says the following topology ids are supported :
`hot_content`, `warm`, `cold`, `coordinating` or `master`

**Comment by karencfv** [comment]
Thanks @AntonChernysh for catching this and letting us know! 🙇‍♀️ I've opened up the above PR to fix this.
