### ISSUE TITLE
Consistent sort order in datasource

### ISSUE THREAD

**Issue by henrikno** [elastic/terraform-provider-ec#320]
We use ec_deployments datasource to populate a list of remote_clusters in a different deployment.

Every time we do a plan/apply it looks like there is a change, but it's not, the list of deployments is just in a different order.

I think it can be fixed by specifying the sort parameter in the request
https://github.com/elastic/terraform-provider-ec/blob/2473642a2fc5c51f2e27b98f7699145734fbf0e6/ec/ecdatasource/deploymentsdatasource/expanders.go#L94-L95
https://github.com/elastic/cloud-sdk-go/blob/e6d054f02355d17805dd852166082c2b0e322544/pkg/models/search_request.go#L48
If we sort by e.g. deployment_it should make it stable and idempotent.

**Comment by Kushmaro** [comment]
@henrikno , care to open a PR? :) 
We very much welcome all contributions  /cc @marclop @karencfv

**Comment by marclop** [comment]
PR 322 should solve the problem.
