### ISSUE TITLE
Making changes to an `ec_deployment` resource unexpectedly modifies trust relationships

### ISSUE THREAD

**Issue by kenoir** [elastic/terraform-provider-ec#323]
## Expected Behavior

Making changes to a `ec_deployment` resource does not modify trust relationships.

## Current Behavior
When an Elastic Cloud deployment is created using `ec_deployment` it is created with the default trust management setting (in our case trust all other clusters in an account).

When an update is made to a `ec_deployment` resource the trust management setting are set to "Trust no deployment" for that deployment.

## Terraform definition

```tf
resource "ec_deployment" "catalogue_api" {
  name = "catalogue-api"

  region                 = "eu-west-1"
  version                = "7.13.1"
  deployment_template_id = "aws-io-optimized-v2"

  traffic_filter = local.catalogue_ec_traffic_filter

  elasticsearch {
    topology {
      id         = "hot_content"
      size       = "4g"
      zone_count = 1
    }

    remote_cluster {
      deployment_id = local.catalogue_ec_cluster_id
      alias         = local.catalogue_ec_cluster_name
      ref_id        = local.catalogue_ec_cluster_ref_id
    }
  }

  kibana {
    topology {
      zone_count = 1
      size       = "1g"
    }
  }

  // Removing this block when trust management settings are set to "Trust all deployments"
  // and applying causes the settings to change to "Trust no deployment"
  observability {
    deployment_id = data.ec_deployment.logging.id
  }
}
```
## Steps to Reproduce
- Create a new Elastic Cloud SaaS `ec_deployment` resource with an `observability` block
- Trust management will be set to "Trust all deployments".
- Remove the `observability` block and re-apply.
- Trust management will be changed to "Trust **no** deployments".

## Context
When trying to set up cluster replication to separate read / write load on our clusters, we have found that applying terraform changes breaks our trust management settings.

This is an issue for us being able to use cluster replication reliably.

## Your Environment
Elastic Cloud SaaS

Terraform config:
```
Terraform v0.14.8
+ provider registry.terraform.io/elastic/ec v0.1.1
+ provider registry.terraform.io/hashicorp/aws v2.70.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

Our project: https://github.com/wellcomecollection/catalogue-api/blob/main/terraform/shared/elastic.tf#L5

**Comment by jamesgorrie** [comment]
As a note, I have seen this behavior when:

* Create initial deployment without `kibana` block, `terraform apply`
* Deployment is created with "Trust all deployments"
* Add `kibana` block, `terraform apply`
* Deployment trust is set to "Trust no deployment"
* Remove `kibana` block, `terraform apply`
* Deployment trust is set to "Trust no deployment"

The same outcome occurs when you switch out the `kibana` block change to changing the `elasticsearch.topology[0].size` from `1g` => `4g` (hunch is it's something to do with create vs update).

**Comment by marclop** [comment]
Thank you for reporting the bug, and for including all the details and how to reproduce it. I'm working on a fix that will resolve this issue.
