### ISSUE TITLE
Can a deployment use itself for logging?

### ISSUE THREAD

**Issue by milesqi** [elastic/terraform-provider-ec#333]
If do not create a dedicated deployment for logging, is it possible to use itself in the plan. example as below

```tf
resource "ec_deployment" "**example_observability**" {
  name = "my_example_deployment"

  region                 = "us-east-1"
  version                = data.ec_stack.latest.version
  deployment_template_id = "aws-io-optimized-v2"

  elasticsearch {}

  kibana {}

  observability {
    deployment_id = ec_deployment.**example_observability**.id
  }
}
```

**Comment by marclop** [comment]
I believe that terraform resources cannot reference themselves. However, you could hardcode the deployment ID and set it as `observability.deployment_id = "DEPLOYMENT_ID"`.

It is important to note that, while setting up self-monitoring is allowed, **it is not recommended for production workloads** since it can easily cause your deployment to overload itself when the load > than the cluster allows it for and the observability data will only make things worse.

**Comment by marclop** [comment]
I'll also add a little of color on how to go about and create a deployment with self monitoring. The deployment cannot be created with self monitoring enabled, but can be set afterwards, this is a known issue and might be fixed in the future.

**Comment by milesqi** [comment]
that would be great if it gets fixed in future release. for development and testing deployments we do hope it just self-logged. I also found the work around to set it after deployment is created, however, it's not a good way to fit into our deployment pipeline. We will wait for the fix if it can come soon. thank you.

**Comment by marclop** [comment]
@milesqi We currently have no estimated timeline on fixing this issue, I can keep you posted though.

**Comment by scathatheworm** [comment]
I'm running into this problem when trying to configure a monitoring deployment, which has monitoring enabled for itself as well. Any plans for addressing this? Hardcoding the deployment id is really dirty and kinda defeats the purpose of infrastructure as code.

**Comment by JoranDox** [comment]
Not sure if this should be a different issue, but it's very related so I thought I'd ping here first?

Basically I have 2 clusters, one for production, and one for testing, and they already exist so I know the id of the testing one. Then I gave the id of the testing one for both the logging destinations (as you don't want production to log itself to itself), but I get this:
![image](https://github.com/elastic/terraform-provider-ec/assets/7152733/85d46828-d726-4a6a-af68-64055d34176a)
The id is for the testing cluster, which for the testing cluster reverts to "self" instead, and causes the confusion.
I can fix this in the code of course, but it would be nice if those values were considered the same somehow.

**Comment by gigerdo** [comment]
@JoranDox Yeah good point. I think it should still be supported to pass the actual deployment-id instead of 'self'. I would appreciate it if you could open it as a new bug report, thanks.
