### ISSUE TITLE
Support for AZURE Private Link traffic Filter Rule

### ISSUE THREAD

**Issue by tacitus** [elastic/terraform-provider-ec#335]
The API has recently added support for AZURE private link traffic rules, for example:

```json
{
  "name": "",
  "region": "azure-australiaeast",
  "description": "",
  "type": "azure_private_endpoint",
  "rules": [
    {
      "azure_endpoint_name": "",
      "azure_endpoint_guid": ""
    }
  ],
  "include_by_default": false
}
```

This is a request for that functionality.

**Comment by Kushmaro** [comment]
Thanks for opening this (and sorry for the late reply) 
We'll make sure this is supported in an upcoming release.

**Comment by marclop** [comment]
I'll probably be the one to work on this, but we're missing two fields in each of the individual rules and the new `"azure_private_endpoint"` traffic filter `"type"`.
