### ISSUE TITLE
Terraform apply [update] fail when autoscaling set

### ISSUE THREAD

**Issue by guibirow** [elastic/terraform-provider-ec#337]
I have the a terraform provisioning of  a elastic deployment that was working for deploying new resources and updates.
When I enable autoscaling, the deployment fail with following message:

```
ec_deployment.elastic_deployment: Modifying... [id=2681f87cef05697fd4ff2fdb33a43f01]

Error: failed updating deployment: 1 error occurred:
        * api error: deployments.invalid_autoscaling_config: Invalid autoscaling configuration in deployment: [Only autoscaling max property supported and must be defined for topology element [hot_content]] (resources.elasticsearch[0])

  with ec_deployment.elastic_deployment,
  on elastic.tf line 18, in resource "ec_deployment" "elastic_deployment":
  18: resource "ec_deployment" "elastic_deployment" {

```
I've tried removing the  `autoscaling` configuration, changing the values, pass diferent parameters, but there isn't anything I can make it work when I enable the autoscaling.

When autoscaling is disabled, it does accept the `autoscaling` configuration without complaints.

## Expected Behavior

Enable the autoscaling option and have the deployment succeed

## Current Behavior

Terraform fail with message `api error: deployments.invalid_autoscaling_config: Invalid autoscaling configuration in deployment: [Only autoscaling max property supported and must be defined for topology element [hot_content]] (resources.elasticsearch[0])`

## Terraform definition

```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.2.1"
    }
  }
}

locals {
  elastic_deployment_name     = "my_example_deployment"
  elastic_deployment_region   = "gcp-europe-west2"
  elastic_deployment_version  = "7.13.4" # when provisioning new cluster, ensure the version provided is a current version otherwise will fail
  elastic_deployment_template = "gcp-io-optimized"  # https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html
  elastic_search_instance_config     = "gcp.data.highio.1"
  elastic_search_instance_memory_gb = 1
  elastic_search_instance_memory_max_gb = 4
  elastic_search_zone_count = 1
  elastic_search_autoscale_enabled = true
}

resource "ec_deployment" "elastic_deployment" {
  name                   = local.elastic_deployment_name
  region                 = local.elastic_deployment_region
  version                = local.elastic_deployment_version
  deployment_template_id = local.elastic_deployment_template

  elasticsearch {
    autoscale = false #local.elastic_search_autoscale_enabled
    topology {
        id = "hot_content"
        size= "${local.elastic_search_instance_memory_gb}g"
        size_resource= "memory"
        zone_count= local.elastic_search_zone_count
        autoscaling { 
            max_size = "${local.elastic_search_instance_memory_max_gb}g"
        }
    }
  }
}

```

## Steps to Reproduce

- Create the resource using terraform definition above (tf apply)
- change autoscale values to something like 8g without enabling (tf apply)
- enable autoscale (tf apply)

## Context
I suspect it has failed because I possibly did update the `autoscaling {}` block with values like below when autoscaling was disabled

```
        autoscaling { 
            max_size = "${local.elastic_search_instance_memory_max_gb}g"
            max_size_resource =  "memory"
            min_size = "1g"
            min_size_resource = "memory"
        }
```

## Possible Solution
I suspect the terraform provider is caching `min_size` and the other values, even though I've removed it
To make it work again, I had to destroy the resources and re-deploy

## Your Environment
* Version used: 0.2.1
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud v7.13.4
* Environment name and version (e.g. Go 1.9): 
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by marclop** [comment]
Hi @guibirow, thank you for opening this bug report and apologies for the unexpected behavior.

What you are experiencing is currently a Terraform provider SDK limitation that we unfortunately cannot directly solve. Because all the fields in the _autoscaling_ block are both set as _computed_  (since the value can be computed by our API) and _optional_ (since the value can be set in the Terraform configuration), when any of these fields is removed from the Terraform configuration it still has a value set in the state, we informally said that some configuration fields are _"sticky"_.

We've got a disclaimer for the _topology_ blocks, but not for every single _computed_ and _optional_ field.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/7286993/126619425-05075d9c-84a7-4c29-927c-05300bba76ae.png">

What can be done, is setting the fields to the zero value of that type, for example, since both `min_size ` and `min_size_resource` are strings, they can be set to `""`. For example:

```tf
    topology {
      id         = "hot_content"
      zone_count = 1
      size       = "4g"
      autoscaling {
        max_size = "58g"
        max_size_resource = "memory"
        min_size = ""
        min_size_resource = ""
      }
    }
```

**Comment by guibirow** [comment]
Sorry, I didn't notice this warning!
Thanks for the update

I've tried to set the values to empty but didn't solve the problem.
I haven't tried to set as 0 though!

Given the limitation, Ideally the provider should have separate configuration for resources that support these fields, so we don't set them by mistake.

Thanks
