### ISSUE TITLE
ec_deployment alias does not get updated

### ISSUE THREAD

**Issue by guibirow** [elastic/terraform-provider-ec#338]
I have a deployment where I would like to change the Alias after creating the deployment, but the alias does not get updated even though the terraform provider identify the changes and confirm the update is successful.

## Expected Behavior
Alias to be updated for the deployment when alias is changed in terraform definition

## Current Behavior
terraform identify the alias as a change and completes update successfully after `terraform apply` but the alias is not renamed in the cloud portal.

## Terraform definition
```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "0.2.1"
    }
  }
}

provider "ec" {
  #apikey = # set using env var `EC_API_KEY`
}


resource "ec_deployment" "elastic_deployment" {
  name                   = local.elastic_deployment_name
  alias                  = "${local.elastic_deployment_name}-newname"
  region                 = local.elastic_deployment_region
  version                = local.elastic_deployment_version
  deployment_template_id = local.elastic_deployment_template

  elasticsearch {
    autoscale = local.elastic_search_autoscale_enabled
    topology {
      id            = "hot_content"
      size          = "${local.elastic_search_instance_memory_gb}g"
      size_resource = "memory"
      zone_count    = local.elastic_search_zone_count
      autoscaling {
        max_size = "${local.elastic_search_instance_memory_max_gb}g"
      }
    }
  }

  kibana {}
}
```

## Steps to Reproduce

1. Create a deployment and apply the terraform definition
2. Wait the deployment to complete
3. Change the alias to something else and apply the changes
4. Ensure terraform will identify the alias as a change
5. Wait for deployment to complete
6. Check name in the portal to see if it changed
7. Doing terraform apply again will trigger a new update for alias, the apply will complete but the alias won't be updated

## Context
Low impact, but we are unable to use terraform to change alias via terraform

## Possible Solution
Workaround is changing the value in terraform and then change manually via portal to match terraform values

## Your Environment
* Version used:0.2.1
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud
* Environment name and version (e.g. Go 1.9): v7.14
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by marclop** [comment]
@guibirow thanks for reporting the bug, there is indeed a bug in the provider in the update function, the create function does set the alias correctly but not the update:

https://github.com/elastic/terraform-provider-ec/blob/master/ec/ecresource/deploymentresource/expanders.go#L39-L42

vs

https://github.com/elastic/terraform-provider-ec/blob/master/ec/ecresource/deploymentresource/expanders.go#L118-L125
