### ISSUE TITLE
Upgrade EC terraform provider to use latest sdk provider functions

### ISSUE THREAD

**Issue by ggsood** [elastic/terraform-provider-ec#34]
## Overview
Upgrade EC terraform provider to use latest SDKs provider functions introduced as part of SDK2 , which adds diagnosis capabilities during provider initialisation.

## Possible Implementation
Refactor the provider code according to the new SDK schema.

## Testing
the provider works as per the current implementation.

## Context
Using the latest features provided by the sdk2 kit of terrafom. 

## Your Environment
Mac OS-X
Golang version 1.14.6

**Comment by marclop** [comment]
Resolved by #43
