### ISSUE TITLE
Provisioning Elasticsearch role & user resources

### ISSUE THREAD

**Issue by kenoir** [elastic/terraform-provider-ec#344]
## Overview

We'd like to provision Elasticsearch users and roles as part of our infrastructure management. 

We've used local-exec provisioners calling out to scripts to do this for us so far, but understanding when a particular provisioner will be called and ensuring proper resource management using local-exec provisioners is awkward. It would be very useful to have native integration in this provisioner.

I would imagine this implemented as `ec_user` and `ec_role` resources, referencing a particular `ec_deployment`.

Is this something that is on the road map for this project?

**Comment by marclop** [comment]
Hi @kenoir, thanks for opening the issue.

These APIs belong to the Elasticsearch API and are not in scope for the EC Terraform provider, however they are in scope for an Elasticsearch Terraform provider but we do not have one at the moment I'm afraid.

`local-exec` provisioners are not great, but we do not plan to support Elasticsearch APIs through the Elastic Cloud API, which this particular provider uses.

**Comment by kenoir** [comment]
Thanks for clarifying.
