### ISSUE TITLE
Provide the cloud_id as attribute

### ISSUE THREAD

**Issue by simon-schneider-gcx** [elastic/terraform-provider-ec#346]
## Overview
Provide the `cloud_id` for each deployment as an attribute.

## Possible Implementation
Expose the `cloud_id` property from the SDK as an attribute.

## Testing
Should be tested with an unit test, which assures that a given `cloud_id` is exposed to terraform. 

## Context
For the implementation of custom domains, the cloud id is needed.
(See https://xeraa.net/blog/2020_custom-domains-and-anonymous-access-on-elastic-cloud/ )
To enable an automatic reference with terraform the cloud_id should be exposed as an attribute,
so other modules, resources, etc. are able to consume it.

## Your Environment
I want to have my infrastructure managed by terraform, therefore i want to create a custom domain for an elastic cloud deployment with terraform.

**Comment by marclop** [comment]
Hi @simon-schneider-gcx, the `cloud_id` attribute is already exposed under the `elasticsearch` block, see https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#elasticsearch.#.cloud_id for more information.
