### ISSUE TITLE
Remote Cluster Usage, After CCS Depreciation?

### ISSUE THREAD

**Issue by nicholastucker** [elastic/terraform-provider-ec#374]
## Question
Hey,
Following the depreciation of CCS deployments, what's the impact around the usage of the following:
https://github.com/elastic/terraform-provider-ec/blob/master/docs/resources/ec_deployment.md#remote-cluster
Can this work on generic clusters that utilise remote cluster calls, or MUST it be a CCS deployment type?
Thanks

**Comment by marclop** [comment]
Absolutely, any deployment can have Elasticsearch `remote_cluster` blocks configured pointing to another deployment.

**Comment by marclop** [comment]
@nicholastucker I'm going to close this off
