### ISSUE TITLE
Add ref_id output to data.ec_deployments

### ISSUE THREAD

**Issue by Crazybus** [elastic/terraform-provider-ec#379]
## Overview

Add `ref_id` to data.ec_deployments. It is currently only available in data.ec_deployment: https://registry.terraform.io/providers/elastic/ec/latest/docs/data-sources/ec_deployment#elasticsearch.#.ref_id

## Context

When adding remote clusters from data.ec_deployments it isn't possible to add clusters which don't have the current default ref_id of `main-elasticsearch`. Leaving it blanks results in the error message:

```
deployments.deployment_remote_resource_not_found: Invalid Remote Clusters Configuration. The following resource could not be found:(deployment [removed] - ref_id [main-elasticsearch])
```

An example of it being used with data.ec_deployment can be seen here:
https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#with-cross-cluster-search-settings

**Comment by marclop** [comment]
@Crazybus the example uses the `ec_deployment` resource, not any of the data resources.

**Comment by gtback** [comment]
I think this got closed accidentally by a comment that was referring to a workaround for this issue.
