### ISSUE TITLE
[deployment templates] Some AWS regions missing `-aws` prefix

### ISSUE THREAD

**Issue by Bamieh** [elastic/terraform-provider-ec#404]
## Description

All gcp and azure templates are prefixed with `gcp-` and `azure-` respectively.

AWS deployment templates have a few regions that are missing the `aws-` prefix which makes it confusing and requires special handling when wrapping the resource in a module.

This is the [list of regions](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html) missing the `aws-` prefix:
```
Tokyo (ap-northeast-1), ap-northeast-1
Singapore (ap-southeast-1), ap-southeast-1
Sydney (ap-southeast-2), ap-southeast-2
Ireland (eu-west-1), eu-west-1
Sao Paulo (sa-east-1), sa-east-1
N. Virginia (us-east-1), us-east-1
N. California (us-west-1), us-west-1
Oregon (us-west-2), us-west-2
```

## Your Environment

* Version used:
```
ec = {
  source  = "elastic/ec"
  version = "0.3.0"
}
```
* Environment name and version: `Terraform 1.0.10`

**Comment by Kushmaro** [comment]
@Bamieh thanks for opening this one
unfortunately, this issue stems from the Elastic Cloud backend APIs, and not the terraform provider itself.. 
I'll close this one and raise it internally.

**Comment by hamishdh** [comment]
I just lost a bit of time to this mismatch too (trying to provision a cluster in "eu-west-2"). It would be great if the [list of regions](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html) was included in the terraform provider README 🙏.
