### ISSUE TITLE
Feature request: agent deploy

### ISSUE THREAD

**Issue by agomezvidalee** [elastic/terraform-provider-ec#412]
Enable client use terraform to deploy any agent on their infra

The reference on this point me to do via elastic cloud console (UI interface) or via API.

It would be great to keep sticky on usual terraform at that time as a client I deploy my infra (EKS, ec2, ...)

## Context
The racional behind this is to make an easy landing for that new clients that are looking for a solution like this but consider to have not this feature as -1 at evaluation point.

Thank you for having a look on this request, hope it is useful

**Comment by tobio** [comment]
@agomezvidalee is the intention here to use the provider to install the [Elastic Agent](https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation.html)? If so that's outside the scope of this provider, which is solely expected to managed Elastic Cloud resources.

**Comment by Kushmaro** [comment]
closing as per comment above, this is outside the scope of this provider.
