### ISSUE TITLE
Show in Azure Portal

### ISSUE THREAD

**Issue by sven5** [elastic/terraform-provider-ec#413]
Is there a way that the deployment shows up in Azure Portal in a resource group?

Just like when you deploy the ARM template using Azure Marketplace offer **Elasticsearch (Elastic Cloud)** [Link](https://portal.azure.com/#blade/Microsoft_Azure_Marketplace/GalleryItemDetailsBladeNopdl/id/elastic.ec-azure-pp/product/%7B%22displayName%22%3A%22Elasticsearch%20(Elastic%20Cloud)%22%2C%22itemDisplayName%22%3A%22Elasticsearch%20(Elastic%20Cloud)%22%2C%22id%22%3A%22elastic.ec-azure-pp%22%2C%22bigId%22%3A%22DZH318Z08S2B%22%2C%22offerId%22%3A%22ec-azure-pp%22%2C%22publisherId%22%3A%22elastic%22%2C%22publisherDisplayName%22%3A%22Elastic%22%2C%22longSummary%22%3A%22The%20official%20Elasticsearch%20managed%20offering%20-%20integrated%20directly%20in%20the%20Azure%20portal%22%2C%22description%22%3A%22%3Cspan%20id%3D%5C%22docs-internal-guid-140ecb0a-7fff-63b1-dbb2-844df119cecb%5C%22%3E%3Cp%20dir%3D%5C%22ltr%5C%22%3E%3Cspan%20id%3D%5C%22docs-internal-guid-2ac0eb2b-7fff-4fd0-0a79-8aec0f048851%5C%22%3EElastic%20on%20Microsoft%20Azure%20gives%20you%20the%20ability%20to%20deploy%20Elasticsearch%20directly%20within%20the%20Azure%20portal%2C%20allowing%20you%20to%20accelerate%20your%20time%20to%20value%20and%20benefit%20from%20enhanced%20business%20agility.%20Elasticsearch%20resources%20can%20be%20managed%20in%20the%20Azure%20portal%20just%20like%20any%20other%20native%20Azure%20service%20like%20VMs.%26nbsp%3B%3C%2Fspan%3E%3Cb%3ENOTE%3C%2Fb%3E%3A%20You%20need%20to%20be%20configured%20as%20a%26nbsp%3B%3Ca%20href%3D%5C%22https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fcost-management-billing%2Fmanage%2Fadd-change-subscription-administrator%23to-assign-a-user-as-an-administrator%5C%22%3E%3Cb%3ESubscription%20Owner%3C%2Fb%3E%3C%2Fa%3E%26nbsp%3Bin%20order%20to%20deploy%20Elasticsearch.%3C%2Fp%3E%3Cp%20dir%3D%5C%22ltr%5C%22%3E%3Cbr%3E%3C%2Fp%3E%3Cp%20dir%3D%5C%22ltr%5C%22%3EBuild%20modern%20search%20experiences%20across%20your%20organization.%20Gain%20deeper%20insights%20into%20your%20environment%20by%20monitoring%20applications.%20Protect%20your%20technology%20investment%20with%20intelligent%20threat%20protection.%20Take%20advantage%20of%20machine%20learning%20capabilities%20so%20you%E2%80%99re%20always%20future-ready.%20With%20Elastic%20on%20Microsoft%20Azure%20you%E2%80%99re%20able%20to%20reduce%20operational%20complexities%20and%20maximize%20visibility%20into%20the%20health%2C%20performance%2C%20and%20security%20of%20your%20infrastructure%2C%20applications%2C%20and%20data.%20With%20our%20managed%20service%20offering%2C%20deployments%20are%20operated%2C%20patched%2C%20secured%2C%20and%20supported%20by%20the%20experts%20at%20Elastic%2C%20freeing%20you%20to%20focus%20on%20your%20business.%3C%2Fp%3E%3Cp%20dir%3D%5C%22ltr%5C%22%3E%3C%2Fp%3E%3Cul%3E%3Cli%3EView%20and%20manage%20your%20Elasticsearch%20deployments%20directly%20within%20the%20Azure%20portal%20in%20any%20supported%20Azure%20region%3C%2Fli%3E%3Cli%3EAutomate%20ingestion%20of%20Azure%20logs%20and%20metrics%20with%20just%20a%20few%20clicks.%26nbsp%3B%3C%2Fli%3E%3Cli%3EConnect%20Elastic%20Workplace%20Search%20to%20Office%20365%2C%20OneDrive%2C%20and%20SharePoint%20Online%20on%20Azure.%3C%2Fli%3E%3Cli%3EView%20your%20Elastic%20usage%20on%20your%20Azure%20bill.%20In%20addition%2C%20your%20Elastic%20spend%20accrues%20towards%20your%20Azure%20spending%20commitments.%3C%2Fli%3E%3Cli%3EUse%20your%20Azure%20account%20to%20single%20sign-on%20to%20Elastic%20Cloud%20and%20your%20Kibana%20instances.%3C%2Fli%3E%3C%2Ful%3E%3Cdiv%3E%3Cbr%3E%3C%2Fdiv%3E%3Cp%20dir%3D%5C%22ltr%5C%22%3E%3Cb%3EKey%20Features%3C%2Fb%3E%3C%2Fp%3E%3Cp%20dir%3D%5C%22ltr%5C%22%3E%3C%2Fp%3E%3Cul%3E%3Cli%3EElastic%20Enterprise%20Search%3A%20Build%20customized%20search%20experiences%20using%20out-of-the-box%20tools%20or%20your%20own%20APIs%20across%20your%20web%2C%20mobile%2C%20and%20SaaS%20applications.%3C%2Fli%3E%3Cli%3EElastic%20Observability%3A%20Traverse%20your%20application%20and%20see%20how%20every%20interrelates.%20Correlate%2C%20search%2C%20and%20apply%20machine%20learning%20to%20logs%2C%20metrics%2C%20APM%20traces%2C%20uptime%2C%20and%20user%20experience%20monitoring%20%E2%80%94%20all%20within%20a%20single%20user%20interface.%3C%2Fli%3E%3C%2Ful%3E%3Cp%3E%3C%2Fp%3E%3Cul%3E%3Cli%20dir%3D%5C%22ltr%5C%22%20aria-level%3D%5C%221%5C%22%3E%3Cp%20dir%3D%5C%22ltr%5C%22%20role%3D%5C%22presentation%5C%22%3EElastic%20Security%3A%20Use%20the%20same%20Azure%20logs%20and%20metrics%20to%20secure%20your%20technology%20investment.%20Implement%20SIEM%20and%20endpoint%20security%20and%20take%20advantage%20of%20prebuilt%20detection%20rules%20and%20alerts%20made%20specifically%20for%20protecting%20Azure%20environments.%26nbsp%3B%3C%2Fp%3E%3C%2Fli%3E%3Cli%20dir%3D%5C%22ltr%5C%22%20aria-level%3D%5C%221%5C%22%3E%3Cp%20dir%3D%5C%22ltr%5C%22%20role%3D%5C%22presentation%5C%22%3EElastic%20Stack%3A%20Reliably%20and%20securely%20take%20data%20from%20any%20source%2C%20in%20any%20format%2C%20then%20search%2C%20analyze%2C%20and%20visualize%20it%20in%20real%20time.%3C%2Fp%3E%3C%2Fli%3E%3C%2Ful%3E%3C%2Fspan%3E%22%2C%22isPrivate%22%3Afalse%2C%22hasPrivateOffer%22%3Afalse%2C%22isMacc%22%3Atrue%2C%22isPreview%22%3Afalse%2C%22isByol%22%3Afalse%2C%22isCSPEnabled%22%3Atrue%2C%22isCSPSelective%22%3Afalse%2C%22isThirdParty%22%3Atrue%2C%22isReseller%22%3Afalse%2C%22hasFreeTrials%22%3Afalse%2C%22marketingMaterial%22%3A%5B%5D%2C%22legalTermsUri%22%3A%22https%3A%2F%2Fquery.prod.cms.rt.microsoft.com%2Fcms%2Fapi%2Fam%2Fbinary%2FRWQaJk%22%2C%22privacyPolicyUri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Flegal%2Fprivacy-statement%22%2C%22version%22%3A%2259d06237-74f7-4429-b33b-fb93345b655d%22%2C%22metadata%22%3A%7B%22leadGeneration%22%3A%7B%22productId%22%3Anull%7D%2C%22testDrive%22%3Anull%7D%2C%22categoryIds%22%3A%5B%22monitoring-and-diagnostics%22%2C%22other%22%2C%22analytics%22%2C%22data-analytics%22%2C%22visualization-reporting%22%2C%22azureCertified%22%2C%22fromPublishingPortal%22%5D%2C%22screenshotUris%22%3A%5B%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.22169.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.ef029cb3-4757-4dc9-b924-b8225ebc41b6%22%2C%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.35864.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.d5d31311-5746-4ebd-b9cc-f8c0ac65bcee%22%2C%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.24179.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.29ae388d-d041-455c-a853-17820b5b9286%22%2C%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.2517.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.8015ba4c-9334-4ed8-a47d-dbea9303b8fe%22%5D%2C%22videos%22%3A%5B%7B%22caption%22%3A%22The%20Power%20of%20Search%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DmVXJHKmFXts%22%2C%22videoPurpose%22%3A%22trailer%22%2C%22previewImage%22%3A%7B%22caption%22%3A%22The%20Power%20of%20Search%22%2C%22uri%22%3A%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.43546.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.b60b6f62-a602-4db3-8560-346c66797d3f%22%2C%22imagePurpose%22%3A%22trailer%22%7D%7D%5D%2C%22links%22%3A%5B%7B%22id%22%3A%22Elasticsearch%20on%20Azure%20Documentation%22%2C%22displayName%22%3A%22Elasticsearch%20on%20Azure%20Documentation%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Fcloud%2Fcurrent%2Fec-azure-marketplace-native.html%22%7D%2C%7B%22id%22%3A%22Pricing%20FAQ%22%2C%22displayName%22%3A%22Pricing%20FAQ%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Fcloud%2Fcurrent%2Fec-faq-billing.html%22%7D%2C%7B%22id%22%3A%22Getting%20Started%20FAQ%22%2C%22displayName%22%3A%22Getting%20Started%20FAQ%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Felastic-stack-deploy%2Fcurrent%2Fazure-marketplace-getting-started.html%22%7D%2C%7B%22id%22%3A%22Elasticsearch%20Service%20Regions%22%2C%22displayName%22%3A%22Elasticsearch%20Service%20Regions%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Fcloud%2Fcurrent%2Fec-regions-templates-instances.html%23ec-azure_regions%22%7D%2C%7B%22id%22%3A%22Service%20Status%22%2C%22displayName%22%3A%22Service%20Status%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Fcloud%2Fcurrent%2Fec-service-status.html%22%7D%2C%7B%22id%22%3A%22Getting%20help%22%2C%22displayName%22%3A%22Getting%20help%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Fcloud%2Fcurrent%2Fec-get-help.html%22%7D%2C%7B%22id%22%3A%22Community%22%2C%22displayName%22%3A%22Community%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fcommunity%22%7D%2C%7B%22id%22%3A%22Subscription%20Levels%22%2C%22displayName%22%3A%22Subscription%20Levels%22%2C%22uri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fguide%2Fen%2Fcloud%2Fcurrent%2Fec-licensing.html%22%7D%5D%2C%22filters%22%3A%5B%5D%2C%22plans%22%3A%5B%7B%22id%22%3A%220001%22%2C%22displayName%22%3A%22Elastic%20Cloud%20-%20Pay%20as%20you%20Go%22%2C%22description%22%3A%22Use%20Elasticsearch%20and%20pay%20as%20you%20go%22%2C%22restrictedAudience%22%3A%7B%7D%2C%22skuId%22%3A%220001%22%2C%22planId%22%3A%22ess-monthly-consumption%22%2C%22legacyPlanId%22%3A%22elastic.ec-azure-ppess-monthly-consumption%22%2C%22keywords%22%3A%5B%5D%2C%22type%22%3A%22SaaS%22%2C%22leadGeneration%22%3A%7B%22productId%22%3A%22elastic.ec-azure-pp%22%7D%2C%22testDrive%22%3Anull%2C%22availabilities%22%3A%5B%5D%2C%22categoryIds%22%3A%5B%5D%2C%22conversionPaths%22%3A%5B%220002%22%5D%2C%22metadata%22%3A%7B%7D%2C%22uiDefinitionUri%22%3A%22https%3A%2F%2Fquery.prod.cms.rt.microsoft.com%2Fcms%2Fapi%2Fam%2Fbinary%2FRWQaJg%22%2C%22artifacts%22%3A%5B%7B%22name%22%3A%22UiDefinition.json%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FUiDefinition.json%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22DefaultTemplate%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FmainTemplate.json%22%2C%22type%22%3A%22Template%22%7D%2C%7B%22name%22%3A%22Documents_cloud-solution-brief.pdf%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FDocuments%2Fcloud-solution-brief.pdf%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22Documents_Elasticsearch_ElasticCloud_on_Azure_MP.pdf%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FDocuments%2FElasticsearch_ElasticCloud_on_Azure_MP.pdf%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22SampleImage_apps.22169.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.ef029cb3-4757-4dc9-b924-b8225ebc41b6%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FSampleImage%2Fapps.22169.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.ef029cb3-4757-4dc9-b924-b8225ebc41b6%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22SampleImage_apps.35864.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.d5d31311-5746-4ebd-b9cc-f8c0ac65bcee%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FSampleImage%2Fapps.35864.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.d5d31311-5746-4ebd-b9cc-f8c0ac65bcee%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22SampleImage_apps.24179.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.29ae388d-d041-455c-a853-17820b5b9286%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FSampleImage%2Fapps.24179.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.29ae388d-d041-455c-a853-17820b5b9286%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22SampleImage_apps.2517.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.8015ba4c-9334-4ed8-a47d-dbea9303b8fe%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FSampleImage%2Fapps.2517.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.8015ba4c-9334-4ed8-a47d-dbea9303b8fe%22%2C%22type%22%3A%22Custom%22%7D%2C%7B%22name%22%3A%22Thumbnails_apps.43546.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.b60b6f62-a602-4db3-8560-346c66797d3f%22%2C%22uri%22%3A%22https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2Felastic.ec-azure-pp-59d06237-74f7-4429-b33b-fb93345b655d%2FArtifacts%2FThumbnails%2Fapps.43546.5e790067-73cc-4997-9c81-c3995641d5db.49eb4c79-affb-4907-8ce2-0945faa25585.b60b6f62-a602-4db3-8560-346c66797d3f%22%2C%22type%22%3A%22Custom%22%7D%5D%2C%22isPrivate%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22hasFreeTrials%22%3Afalse%2C%22isByol%22%3Afalse%2C%22isFree%22%3Atrue%2C%22isPayg%22%3Afalse%2C%22isStopSell%22%3Afalse%2C%22cspState%22%3A%22OptIn%22%2C%22isQuantifiable%22%3Afalse%2C%22stackType%22%3A%22ARM%22%2C%22hasRI%22%3Afalse%7D%5D%2C%22selectedPlanId%22%3A%22ess-monthly-consumption%22%2C%22iconFileUris%22%3A%7B%22wide%22%3A%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.59172.5e790067-73cc-4997-9c81-c3995641d5db.4c798b82-d8ba-4796-9d51-6800073b00bd.96995f33-522f-4740-abc7-9338bffc9b34%22%2C%22small%22%3A%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.2650.5e790067-73cc-4997-9c81-c3995641d5db.4c798b82-d8ba-4796-9d51-6800073b00bd.b235ad25-6770-4f43-bd5f-fb8e29e1deff%22%2C%22medium%22%3A%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.12931.5e790067-73cc-4997-9c81-c3995641d5db.4c798b82-d8ba-4796-9d51-6800073b00bd.1f6088a7-7d60-41c2-a6c0-3e2439e7602b%22%2C%22large%22%3A%22https%3A%2F%2Fstore-images.s-microsoft.com%2Fimage%2Fapps.38134.5e790067-73cc-4997-9c81-c3995641d5db.4c798b82-d8ba-4796-9d51-6800073b00bd.2b403cb4-b46b-475c-abb7-3a74f8617ae8%22%7D%2C%22itemType%22%3A%22Single%22%2C%22hasNoProducts%22%3Afalse%2C%22hasNoPlans%22%3Afalse%2C%22filledHeartIcon%22%3A%7B%22type%22%3A1%2C%22data%22%3A%22%3Csvg%20viewBox%3D'0%200%2016%2015'%20class%3D'msportalfx-svg-placeholder'%20role%3D'presentation'%20focusable%3D'false'%20xmlns%3Asvg%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20xmlns%3Axlink%3D'http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink'%3E%3Cg%3E%3Ctitle%3E%3C%2Ftitle%3E%3Cpath%20d%3D'M14.758%201.242c.276.276.505.578.688.906.188.328.325.669.414%201.024a4.257%204.257%200%200%201-1.103%204.086L8%2014.008l-6.758-6.75a4.269%204.269%200%200%201-.695-.906%204.503%204.503%200%200%201-.414-1.016%204.437%204.437%200%200%201%200-2.164c.094-.354.232-.695.414-1.024A4.302%204.302%200%200%201%202.625.32C3.141.107%203.682%200%204.25%200s1.109.107%201.625.32c.516.214.977.521%201.383.922l.742.75.742-.75A4.292%204.292%200%200%201%2010.125.32C10.641.107%2011.182%200%2011.75%200s1.109.107%201.625.32c.516.214.977.521%201.383.922z'%20class%3D'msportalfx-svg-c19'%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E%22%7D%2C%22emptyHeartIcon%22%3A%7B%22type%22%3A1%2C%22data%22%3A%22%3Csvg%20viewBox%3D'0%200%2016%2015'%20class%3D'msportalfx-svg-placeholder'%20role%3D'presentation'%20focusable%3D'false'%20xmlns%3Asvg%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20xmlns%3Axlink%3D'http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink'%3E%3Cg%3E%3Ctitle%3E%3C%2Ftitle%3E%3Cpath%20d%3D'M11.75%200c.588%200%201.14.112%201.656.336.516.224.966.529%201.352.914.385.38.687.83.906%201.352.224.515.336%201.065.336%201.648%200%20.568-.11%201.112-.328%201.633-.214.52-.518.979-.914%201.375L8%2014.008l-6.758-6.75A4.256%204.256%200%200%201%20.32%205.883%204.263%204.263%200%200%201%200%204.25a4.177%204.177%200%200%201%201.242-3c.386-.385.836-.69%201.352-.914A4.113%204.113%200%200%201%204.25%200c.432%200%20.818.05%201.156.148.339.1.651.237.938.415.291.171.567.38.828.625.266.244.542.513.828.804.286-.291.56-.56.82-.805.266-.244.542-.453.828-.625.292-.177.607-.315.946-.414A4.126%204.126%200%200%201%2011.75%200zm2.297%206.547c.307-.307.541-.659.703-1.055.162-.396.242-.81.242-1.242a3.19%203.19%200%200%200-.25-1.266%203.048%203.048%200%200%200-.695-1.023%203.095%203.095%200%200%200-1.031-.68%203.192%203.192%200%200%200-1.266-.25c-.438%200-.825.07-1.164.211a3.816%203.816%200%200%200-.938.54%207.001%207.001%200%200%200-.828.765c-.26.281-.534.568-.82.86a31.352%2031.352%200%200%201-.82-.852%207.247%207.247%200%200%200-.836-.774%204.017%204.017%200%200%200-.946-.562A2.875%202.875%200%200%200%204.25%201c-.448%200-.87.086-1.266.258A3.222%203.222%200%200%200%201%204.25c0%20.432.08.846.242%201.242.167.396.404.748.711%201.055L8%2012.594l6.047-6.047z'%20class%3D'msportalfx-svg-c19%20msportalfx-svg-c19'%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E%22%7D%2C%22deleteIcon%22%3A%7B%22type%22%3A17%2C%22options%22%3Anull%7D%2C%22searchId%22%3A%221638796740536_marketplaceOffersBladeSearchContext%22%2C%22searchIndex%22%3A0%2C%22searchScore%22%3A316.04117%2C%22privateBadgeText%22%3Anull%2C%22curationCategoryDisplayName%22%3A%22Analytics%22%2C%22menuItemId%22%3A%22home%22%2C%22subMenuItemId%22%3A%22Search%20results%22%2C%22createBladeType%22%3A0%2C%22offerType%22%3A%22SaaS%22%2C%22useEnterpriseContract%22%3Afalse%2C%22hasStandardContractAmendments%22%3Afalse%2C%22standardContractAmendmentsRevisionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22cspLegalTermsUri%22%3A%22https%3A%2F%2Fquery.prod.cms.rt.microsoft.com%2Fcms%2Fapi%2Fam%2Fbinary%2FRWQaJk%22%2C%22supportUri%22%3A%22https%3A%2F%2Fwww.elastic.co%2Fcloud%2Felasticsearch-service%2Fsupport%22%2C%22isMicrosoftProduct%22%3Atrue%2C%22productOwnershipSellingMotion%22%3A%223PPAgency%22%2C%22galleryItemAccess%22%3A0%2C%22privateSubscriptions%22%3A%5B%5D%2C%22isTenantPrivate%22%3Afalse%2C%22hasRIPlans%22%3Afalse%7D/selectionMode//resourceGroupId//resourceGroupLocation//dontDiscardJourney//selectedMenuId/home/launchingContext/%7B%22galleryItemId%22%3A%22elastic.ec-azure-ppess-monthly-consumption%22%2C%22source%22%3A%5B%22GalleryFeaturedMenuItemPart%22%2C%22VirtualizedTileDetails%22%5D%2C%22menuItemId%22%3A%22home%22%2C%22subMenuItemId%22%3A%22Search%20results%22%7D)

**Comment by andres-robinet-sw** [comment]
We are experiencing the same issue. Is there no way to view TF EC deployments in the Azure portal ATM?

**Comment by sven5** [comment]
I've already contacted ES support, and they say currently it's not possible. 😟

**Comment by ThisIsNotTheUserYouAreLookingFor** [comment]
Same issue here, I would like to see this as a feature. Will take this up with ES support as well.

**Comment by Kushmaro** [comment]
@sven5 @andres-robinet-sw @ThisIsNotTheUserYouAreLookingFor , the reason for this is more within how the integration between ESS and Azure is built. We have an internal ticket tracking this. I'm closing this one since its' not really terraform related.

**Comment by sergey-tihon** [comment]
>  We have an internal ticket tracking this.

@Kushmaro is there any way how we can follow the progress of this ticket?

**Comment by mrsymlove** [comment]
what is the state of the integration between ESS and Azure?

is there a possibility to integrate ec_deployment https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/deployment with azurerm_elastic_cloud_elasticsearchhttps://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/elastic_cloud_elasticsearch
?
