### ISSUE TITLE
I'd like to be able to have an `aws_private_endpoint` type in the `ec_deployment_traffic_filter` resource

### ISSUE THREAD

**Issue by BardiaN** [elastic/terraform-provider-ec#417]
## Overview
On Elastic Cloud it is possible to have a traffic filter of type `AWS` which accepts  both `IP filtering rule set` and `Private link endpoint`.
This type is not still supported in this terraform provider, so when you'd want to do that, you'll get this error message from your terraform:

```
JSON request does not comply with schema ([]: [Invalid type [`aws_private_endpoint`], required one of [ip, vpce, azure_private_endpoint, gcp_private_service_connect_endpoint or egress_firewall]])

with ec_deployment_traffic_filter.allow_vpc_<YOUR_VPC>,
│   on terraform.tf line XX, in resource "ec_deployment_traffic_filter" "allow_vpc_<YOUR_VPC>":
│   20: resource "ec_deployment_traffic_filter" "allow_vpc_dev" {
```

Of course this name `aws_private_endpoint` is just a suggestion but could be anything as long as it deploys a filter ressource with required parameters.

## Possible Implementation
- Schema has to change to access this change.
- The schema conversion to the ElasticCloud API to create/update/remove this kind of filter.

## Testing

The schema of course could be refactored in TDD by leveraging unit tests to also accept the aws filter type. It would be also possible to tests the API request when the filter is of `aws` type to make sure that the request goes to ElasticCloud API as it should.

## Context

I have my solution on AWS but I don't use AWS OpenSearch. Instead I have an Elastic Cloud Deployment which must have a firewall that only let our AWS VPC have access to it. Right now we're achieving this requirement by adding the filter manually on ElasticCloud as it let us do so.

## Your Environment

- AWS
   - VPC
   - Lambda

**Comment by codenamekazmi** [comment]
Have you tried using VPCE?

**Comment by kmai** [comment]
This worked for me..

```hcl
resource "ec_deployment_traffic_filter" "aws_vpce_ops_prod" {
  name        = "operations-production"
  description = "Endpoint located in Operations Production account, used by Vector in the EKS cluster."
  region      = "eu-west-1"
  type        = "vpce"

  rule {
    source = "vpce-01062768c6f222697"
  }
}

resource "ec_deployment_traffic_filter_association" "staging_privatelink" {
  traffic_filter_id = ec_deployment_traffic_filter.aws_vpce_ops_prod.id
  deployment_id     = ec_deployment.staging.id
}
```

**Comment by tobio** [comment]
Closing this issue out. As mentioned, this functionality if covered by the existing `vpce` type.
