### ISSUE TITLE
Feature: Provisioning of indexes using terraform

### ISSUE THREAD

**Issue by guibirow** [elastic/terraform-provider-ec#424]
## Overview
In order to reduce the amount of permissions we grant to users in elastic search, we should be provisioning indexes using CI/CD.
Would be convenient to be able to provision clusters and indexes using the official terraform provider 

## Possible Implementation

TBD

## Testing

TBD

## Context

The lack of support for index creation, requires us to use external scripts or providers to provision indexes, increasing the complexity in the setup.

## Your Environment

Elastic Cloud latest version

**Comment by artemnikitin** [comment]
Am I correctly understanding, that you are looking for functionality to manipulate Elasticsearch indices? If yes, then it's out of scope for this Terraform provider. 
Please take a look at https://github.com/elastic/terraform-provider-elasticstack for this goal.

**Comment by tobio** [comment]
Closing this since the functionality is provided by https://github.com/elastic/terraform-provider-elasticstack
