### ISSUE TITLE
Feature request: debug mode

### ISSUE THREAD

**Issue by luigibk** [elastic/terraform-provider-ec#429]
Add option and code to allow debugger-based debugging to use with a  tool like delve to inspect what is happening in a provider as it is happening.

## Overview
A detailed explanation is available in this section of the Terraform plugin sdk documentation:
[debugger-based-debugging](https://www.terraform.io/plugin/sdkv2/debugging#debugger-based-debugging)
This would allow to set breakpoints to pause execution of the provider and examine the values of variables and it would be useful to investigate reproducible bugs

## Possible Implementation
Update main.go + Makefile.build to introduce the command line and compilation options needed.

## Context
I found this feature useful while investigating a SIGSEGV caused by a nil pointer being dereferenced.

## Your Environment
This would be only executed ad-hoc when necessary.

**Comment by tobio** [comment]
Fixed by https://github.com/elastic/terraform-provider-ec/pull/430
