### ISSUE TITLE
Region was not found error

### ISSUE THREAD

**Issue by ndemeshchenko** [elastic/terraform-provider-ec#439]
## Readiness Checklist

- [x] I am running the latest version (0.4.0)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Current Behavior
│ Error: api error: 1 error occurred:
│ 	* templates.region_not_found: Region [eu-west-2] was not found

## Terraform definition
```
resource "ec_deployment" "cluster" {
  name                   = "name123"

  region                 = "eu-west-2"
  version                = "7.17.0"
  deployment_template_id = "aws-io-optimized-v2"

  # The deployment will contain Elasticsearch and Kibana resources with default configurations.
  elasticsearch {}
  kibana {}
}
```

## Your Environment

* Version used: 4.0.4
* Running against Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): go version go1.17.6 darwin/arm64
* Operating System and version: mac os

**Comment by tobio** [comment]
@ndemeshchenko you'll have to use `aws-eu-west-2` as the region for this resource. 

It looks like we can improve our documentation around what to use for the region name. Are you able to let me know where you got the `us-west-2` name from so we don't miss anything?

**Comment by ndemeshchenko** [comment]
then it might be inconsistent naming for the regions. in the terraform documentation for provider in examples given aws region naming schema (e.g `us-east-1`) and it's actually working, I can provision a cluster using aws schema in eu-west-1 but not it eu-west-2

**Comment by tobio** [comment]
> then it might be inconsistent naming for the regions.

This is sadly correct, there are 8 AWS regions which don't include the `aws-` prefix. These are the original Elastic Cloud regions and have a legacy name.

**Comment by ndemeshchenko** [comment]
I'm a bit puzzled now, trying `aws-eu-west-1`  and got an error 
```
Region [aws-eu-west-1] was not found
```

**Comment by ndemeshchenko** [comment]
I'm a bit puzzled. Since it's fine to provision a cluster in aws-

```
│ Error: api error: 1 error occurred:
│ 	* traffic_filter.region_not_found: Region [aws-eu-west-1] was not found

**Comment by tobio** [comment]
> Since it's fine to provision a cluster in `aws-eu-west-1`

It shouldn't be, `eu-west-1` is a legacy region without the provider prefix. `eu-west-2` and `eu-west-3` are both newer regions which include the provider prefix. 

> I can provision a cluster using aws schema in eu-west-1 but not it eu-west-2

Based on this, is there are typo in your Terraform resources, where the region for this filter should be updated to either `aws-eu-west-2` or `eu-west-1`? 

[<img width="425" alt="image" src="https://user-images.githubusercontent.com/444668/154368983-a1615507-5095-4c41-b911-278f13af9417.png">](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html)
