### ISSUE TITLE
Publishing EC Terraform Provider to https://registry.terraform.io/

### ISSUE THREAD

**Issue by ggsood** [elastic/terraform-provider-ec#44]
Plan to publish EC Terraform Provider to terraform registry.

As with Terraform 0.13 release providers can be downloaded directly from terraform registry.
Publishing the provider there will get more community visibility.

## Action items

- [x] Add `goreleaser` config and GitHub action to the project (#196).
- [x] Create a GitHub account to to release the provider on the Terraform Registry.
- [x] Create a GPG key to sign the release.
- [x] Add required secrets to GitHub secrets.
- [x] Push `v0.1.0-beta`
- [x] Publish the provider to the Terraform Registry.

**Comment by marclop** [comment]
Thanks for opening this issue, we already had it on our radar and will work with Hashicorp to publish our provider

**Comment by alejandrod** [comment]
This is a must :-) I hope it gets sorted out soon

**Comment by akovtun-extenda** [comment]
Hello, @marclop. Any updates on this one?

**Comment by marclop** [comment]
@akovtun-extenda we're busy working on having the first shippable version of the provider and publish it before the year closes, we're still uncertain on the exact release date.

**Comment by arbourd** [comment]
@alejandrod has forked and published this package directly to the registry (very easy to do). This means you may have customers (I see 1000+ downloads) that are using an outdated fork instead of the official provider.

Would love to see the official source on the registry. 😬

**Comment by marclop** [comment]
The terraform provider has been released and is available in the Terraform Registry as `0.1.0-beta`: https://registry.terraform.io/providers/elastic/ec/latest

**Comment by tcarrondo** [comment]
@marclop  I'm getting:
`Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider elastic/ec: no
available releases match the given constraints 0.1.0-beta`

Something as changed?
