### ISSUE TITLE
ec_deployment doesn't have attributes references: username and password

### ISSUE THREAD

**Issue by paivin-dn** [elastic/terraform-provider-ec#459]
## Readiness Checklist

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

After import ec_deployment to the terraform resource I want to use `ec_deployment.cluster.elasticsearch_username` and `ec_deployment.cluster.elasticsearch_password` in other resources(e.x. as a connection credentials in a `elasticstack_elasticsearch_index_lifecycle` ). 

## Current Behavior

But I've got the next error message: 
```json
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\"
│ charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic
│ realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}`
```
when I try to use it in the following code:
```
resource "elasticstack_elasticsearch_index_lifecycle" "test-ilm1 {
  name = "test-ilm1"
    elasticsearch_connection {
    endpoints = [ec_deployment.cluster.elasticsearch[0].https_endpoint]
    username  = ec_deployment.cluster.elasticsearch_username
    password  = ec_deployment.cluster.elasticsearch_password
  }
....
}
```

## Steps to Reproduce

1. Import ec_deployment from elastic.co
2. Use ec_deployment.cluster.elasticsearch_username and ec_deployment.cluster.elasticsearch_password in other resources
## Terraform definition
```
terraform {
  required_version = "~> 1.1"
  backend "s3" {
    ....
  }
  required_providers {
    ec = {
      source = "elastic/ec"
      version = "0.4.0"
    }
    elasticstack = {
      source = "elastic/elasticstack"
      version = "0.3.3"
    }
  }
}
provider "ec" {
  apikey = var.ec_api_key
}
provider "elasticstack" {
  elasticsearch {}
}
# Have been imported from elastic.co
resource "ec_deployment" "cluster" {
  region = "aws-eu-central-1"
  version = "7.12.1"
  elasticsearch {}
}
resource "elasticstack_elasticsearch_index_lifecycle" "test-ilm1" {
  name = "test-ilm1"
    elasticsearch_connection {
    endpoints = [ec_deployment.cluster.elasticsearch[0].https_endpoint]
    username  = ec_deployment.cluster.elasticsearch_username
    password  = ec_deployment.cluster.elasticsearch_password
  }
}
```

## Your Environment

* Version used:  0.4.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic cloud.
* Elastic version: 7.12.1

**Comment by tobio** [comment]
From the [docs](https://www.elastic.co/guide/en/cloud/current/definitions.html#DeploymentResource) the `elastic` password is only provided during deployment creation. Unfortunately there's no workaround outside of manually editing state or recreating the deployment. 

I'll update the docs to make this behaviour clearer.
