### ISSUE TITLE
Upgrade from v7.17.1 APM Server to v8.1.1 Integration Server

### ISSUE THREAD

**Issue by RobDTech** [elastic/terraform-provider-ec#460]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
Given I have a deployment at version 7.17.1 with APM server
When I change my Terraform config to 8.1.1 with Interaction server
Then I expect the apply to succeed. 

## Current Behavior
We get an error 
Error: failed updating deployment: 1 error occurred:
	* api error: clusters.cluster_plan_state_error: Integrations Server requires version 8.0.0 or greater (resources.integrations_server[0])
Some of the deployment is upgraded to 8.1.1 but APM/Integration server is in a bad state. 
We've tried various routes, like removing APM first then adding as Integration, both via TF and manually.

**Comment by RobDTech** [comment]
Same issue with 8.1.2 of Elastic

**Comment by tobio** [comment]
@RobDTech can I get you to open a [support issue](https://www.elastic.co/guide/en/cloud/current/ec-get-help.html), including the ID of a deployment impacted by this. You can either email support@elastic.co or access the support portal through the Cloud console.
