### ISSUE TITLE
Dedicated masters added automatically

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/terraform-provider-ec#468]
### Context

When you set hot, cold, warm, and ml nodes at some point you have to add master nodes, this is something that autoscaling does for you, and it is a requirement of ESS that you have to include manually when you figure out you will have 6 to more nodes. Most of the time you add master nodes because you executed the `terraform apply` and it fails with an error related to master nodes. This complicated things when you are updating the cluster and autoscaling has added nodes. It is not a good user experience to make try an error configuration to deploy something and complicates making automated deploys.

### Feature

For all the above, we think that it is a good idea to make the tool add those master nodes when they are required and the user should only specify the nodes that really matter for its needs.

**Comment by tobio** [comment]
Duplicates https://github.com/elastic/terraform-provider-ec/issues/635
