### ISSUE TITLE
[Feature] Prevent upgrading when on an unavailable EC version

### ISSUE THREAD

**Issue by jebax** [elastic/terraform-provider-ec#474]
**Is your feature request related to a problem? Please describe.**
We're currently on version 7.17.2, and recently 7.17.3 was released. Because only the latest minor version of the previous major version is available to upgrade to in EC, 7.17.2 is no longer available so we're being forced to upgrade to 7.17.3.

This is particularly frustrating because we use NEST to communicate with EC, which can break if the versions differ too much.

**Describe the resource you would like to have implemented.**
Ideally we'd have some way to prevent automatic upgrades, even when terraform can't find the version you're already on. In EC, our ES clusters are still on 7.17.2 even though that version isn't available to upgrade to anymore, so it makes sense that our TF config should be able to reflect that state. 
Alternatively, is there already a way to configure this that we're missing? The `lock` argument on `ec_stack` is apparently only useful when you have `"latest"` in your `version_regex`. 

Thanks in advance!

**Comment by jebax** [comment]
sorry yeah, thanks!

**Comment by tobio** [comment]
@jebax 

> Ideally we'd have some way to prevent automatic upgrades, even when terraform can't find the version you're already on.

The workaround for this at the moment is to not use the `ec_stack` data source, and instead just set the `version = "7.17.2"`. This is a pretty unfortunate impact of how the Cloud version policy is implemented. We're aware of the impact this issue has on Terraform users and are discussing how we can improve the experience here.
