### ISSUE TITLE
Error: The terraform-provider-ec_v0.4.0 plugin crashed!

### ISSUE THREAD

**Issue by MADHAMHARINATH** [elastic/terraform-provider-ec#489]
Developed code for Elastic Search, when I am trying to apply getting the below error. Please help on this.

module.es_deployment.ec_deployment.elastic_cloud_instances: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with module.es_deployment.ec_deployment.elastic_cloud_instances,
│   on module/main.tf line 11, in resource "ec_deployment" "elastic_cloud_instances":
│   11: resource "ec_deployment" "elastic_cloud_instances" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-ec_v0.4.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 47 [running]:
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandKibanaTopology({0xe967a0, 0xc000126a68}, {0xc000412e20, 0x1, 0x4})
        github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/kibana_expanders.go:102 +0x399
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandKibanaResource({0xf253e0, 0xc0005f25a0}, 0xc000356840)
        github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/kibana_expanders.go:77 +0x2d2
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.expandKibanaResources({0xc0000f4200, 0x1, 0x1}, 0xc000356840)
        github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/kibana_expanders.go:43 +0xff
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResourceToModel(0x40, 0xc00000c5a0)
        github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/expanders.go:77 +0x738
github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource.createResource({0x1229968, 0xc000130e40}, 0xc0006836c0, {0xe7b200, 0xc00000c5a0})
        github.com/elastic/terraform-provider-ec/ec/ecresource/deploymentresource/create.go:36 +0xe7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00053e0e0, {0x12298f8, 0xc0002d4400}, 0x2, {0xe7b200, 0xc00000c5a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00053e0e0, {0x12298f8, 0xc0002d4400}, 0xc0003420d0, 0xc0004b3f80, {0xe7b200, 0xc00000c5a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000502060, {0x12298f8, 0xc0002d4400}, 0xc00039a2d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00031e300, {0x12299a0, 0xc0005501e0}, 0xc00016a070)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10736e0, 0xc00031e300}, {0x12299a0, 0xc0005501e0}, 0xc0000aa600, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d0540, {0x1239968, 0xc000167380}, 0xc000156000, 0xc0000a53e0, 0x1a5d280, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0000d0540, {0x1239968, 0xc000167380}, 0xc000156000, 0x0)
        google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.42.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.42.0/server.go:919 +0x294

Error: The terraform-provider-ec_v0.4.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by tobio** [comment]
Thanks for the report @MADHAMHARINATH ,are you able to share the `ec_deployment` resource definition which triggers this?

**Comment by MADHAMHARINATH** [comment]
resource "ec_deployment" "elastic_cloud_instances" {
  # Optional name.
  name = var.es_deployment_name

  # Mandatory fields
  region                 = var.es_region
  version                = var.es_version
  deployment_template_id = var.es_deployment_template

  elasticsearch {
    autoscale = var.es_deployment_autoscale

    dynamic "topology" {
      for_each = var.elasticsearch_topology
      content {
        id   = var.elasticsearch_topology_id
        size = var.elasticsearch_topology_size
        zone_count = var.elasticsearch_topology_zone_count
      }
    }

    # NOTE: you can pass configuraion files to overwrite default configuraion
     config {
      user_settings_yaml = var.override_user_settings_yaml ? file("${path.module}/settings.yml") : ""
    }
  }

  kibana {
    dynamic "topology" {
      for_each = var.kibana_toplogy
      content {
        size = var.kibana_toplogy_size
        zone_count = var.kibana_topology_zone_count
      }
    }

    # config = var.kibana_config

  }

  # ---------------------------------------------------------------------------------------------------------------------
  # Setting to default values as there is no specific requirement
  # ---------------------------------------------------------------------------------------------------------------------

  # integrations_server {}
  # ---------------------------------------------------------------------------------------------------------------------
  # Setting to default values as there is no specific requirement
  # ---------------------------------------------------------------------------------------------------------------------

  # enterprise_search {}

  tags = var.es_deployment_tags
}

**Comment by tobio** [comment]
Sorry for the back and forth, are you able to include the details of `var.kibana_toplogy` (or all the referenced vars if that's easier) as well?

**Comment by MADHAMHARINATH** [comment]
Which i sent is is the module which we prepared, calling that module and given the following details 
```
es_version              = "8.2.2"
es_deployment_name      = "vmie_Nesa_prod"
es_deployment_template  = "gcp-storage-optimized"
es_region               = "gcp-europe-west3"
es_deployment_autoscale = true
elasticsearch_id = "hot_content"
elasticsearch_size = "180g"
elasticsearch_zone_count = "2"
kibana_size = "4g"
kibana_zone_count = "2"
# elasticsearch_config    = []
# kibana_config           = []
es_deployment_tags = {
  created_by  = "terraform"
  environment = "prod"
}
```
