### ISSUE TITLE
Creating additional config to Elastic Cloud Deployment causes TerraformProvider-EC to error

### ISSUE THREAD

**Issue by davidg-datascene** [elastic/terraform-provider-ec#490]
- [ X] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
I would expect the config to be created as per the specification of the provider

## Current Behavior
When creating config for user settings in Elastic Search and Kibana setting as exampled in the Terraform definition below the provider fails with following error message:

```text
Error: failed tracking create progress: 3 errors occurred:
	* found deployment plan errors: deployment [21218485b2f65898d39d0f1f65cf5a59] - [elasticsearch][13849231a57348fcb3ee45107ed3bab2]: caught error: "Plan change failed: Some instances were not running"
	* found deployment plan errors: deployment [21218485b2f65898d39d0f1f65cf5a59] - [kibana][d5a7f2b891cc43d289ab41ba9dfd8dbf]: caught error: "Plan change failed: Cluster not reachable: [elasticsearch]... Please validate the cluster is in a healthy state and retry."
```

## Terraform definition
```yaml
dynamic "config" {
      for_each = var.es_user_settings_file != "" && try(fileexists("${path.module}/${var.es_user_settings_file}"), "") != "" ? [1] : []
      content {
        user_settings_yaml = templatefile("${path.module}/${var.es_user_settings_file}", { kibana_url = local.kibana_custom_url })
      }
    }
```

## Context
We cannot use the provider if we can't add in additional config to Elastic Seach and Kibana.  For example, sso access.

If I add in the config after the ElasticSeach nodes and Kibana nodes have been created i.e. by modifying the terraform and adding in the config, the config is applied correctly.  

## Possible Solution
Check to ensure nodes are available before applying the config.  Currently it seems the config is applied before the nodes are ready so timeouts as nodes are not present (as per the error message) i.e. a race condition.

## Your Environment
Terraform v0.14.2
Elastic Cloud 7.16.3
ElasticCloud prover 0.4.1

**Comment by tobio** [comment]
@davidg-datascene thanks for the report. We're aware of this issue, currently custom keystore entries can only be added to a running deployment, causing this issue.

Like you've discovered the current workaround is to apply the config on a second apply cycle which obviously isn't ideal.
