### ISSUE TITLE
Update the https://registry.terraform.io/ Documentation to use the latest version of Provider

### ISSUE THREAD

**Issue by hemantmalik** [elastic/terraform-provider-ec#493]
The latest version based on the https://github.com/elastic/terraform-provider-ec appears to be 0.5.0. On https://registry.terraform.io/ the **_User Provider_** snippet is still leveraging 0.4.1 version. 

<img width="331" alt="image" src="https://user-images.githubusercontent.com/26748353/172067635-1912c26f-8579-4be8-9bb4-49d03ea03033.png">

**Comment by tobio** [comment]
The main is forward looking and 0.5.0 will be the next version released. 0.4.1 is the currently released version of the provider.
