### ISSUE TITLE
Add data source for GCP Private Service Connect URIs

### ISSUE THREAD

**Issue by muresan** [elastic/terraform-provider-ec#503]
## Overview
Add a `data` source for the GCP private service connect URIs described in https://www.elastic.co/guide/en/cloud/current/ec-traffic-filtering-psc.html#ec-private-service-connect-uris. This would make terraform code cleaner while automatically making available new regions with the correct data populated, even if this field is static and not looked up via an API (like ec_stack data source)

## Possible Implementation
Static very much possible as long as it tracks the original document, Dynamic might be overkill.

## Testing
Instantiate the data source, compare with the URL above.

## Context
Not having this I've had to define a local or var in terraform and copy it around from module to module. Prone to copy/paste errors and typos.

**Comment by tobio** [comment]
All three providers are being done under https://github.com/elastic/terraform-provider-ec/issues/514
