### ISSUE TITLE
Investigate the effort and benefits of moving to TF Plugin Framework

### ISSUE THREAD

**Issue by d-carmo** [elastic/terraform-provider-ec#506]
## Overview
Terraform suggests the use of the TF Plugin Framework. We are currently using the API V2. 
Lets investigate and see if it is worth to make that move, as well as what is the effort of doing so.

**Comment by pascal-hofmann** [comment]
Is someone working on this?

I'm currently looking on fixing #336 ad #466 so no matter which blocks you add or remove from your config, it'll always just work without any useless diff. But it looks like this won't be possible without switching to [Terraform Plugin Framework](https://www.terraform.io/plugin/framework/).

**Comment by dimuon** [comment]
I've started working on this but had to switch to more urgent tasks. I'll return to the ticket once these tasks are done.

**Comment by pascal-hofmann** [comment]
@dimuon We decided to work on this as the existing bugs block us. Can you share your current progress?

**Comment by dimuon** [comment]
@pascal-hofmann we’re evaluating needed efforts and prioritising it at the moment.

**Comment by pascal-hofmann** [comment]
Great. So no work is being done twice. :)

-> I've started migrating to framework. The first datasource is nearly working. Will keep you posted on the progress.

**Comment by Kushmaro** [comment]
@pascal-hofmann thanks for looking into this!
We're currently also trying to see what's the path to get the provider to use the plugin framework and are also discussing it with Hashicorp. 

If you'd like to contribute work along the lines of this issue - we're happy to get help. 
But we'll need to balance getting such help with moving as quickly as we can, as this issue is obviously a nuisance to a lot of our customers :)

**Comment by pascal-hofmann** [comment]
Quick status update: The three existing datasources(`ec_deployment`, `ec_deployments`, `ec_stack`) are already working, I'm starting to convert the resources now.

**Comment by dimuon** [comment]
@pascal-hofmann , would you mind to share a branch with your changes?

**Comment by pascal-hofmann** [comment]
Of course. I just pushed it and created a draft PR: https://github.com/elastic/terraform-provider-ec/pull/529

I just realized the datasources are not fully done - forgot to work on tests in `ec/ecdatasource/deploymentdatasource/datasource_test.go`. 🙈

**Comment by dimuon** [comment]
Closing as completed. The migration is tracked by #530
