### ISSUE TITLE
Terraform module

### ISSUE THREAD

**Issue by safetylab** [elastic/terraform-provider-ec#511]
Terraform v1.2.4
Doesnt work in module - terraform init
│ Error: Failed to query available provider packages
│ Could not retrieve the list of available versions for provider hashicorp/ec: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/ec
│ Did you intend to use elastic/ec? If so, you must specify that source address in each module which requires that provider. To see which
│ modules are currently depending on hashicorp/ec, run the following command:
│     terraform providers
This is works: main.tf
terraform {
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "~>0.3.0"
    }
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "~>0.3.3"
    }
}
}
provider "ec" {
  apikey = "key"
}
provider "elasticstack" {
  elasticsearch {}
}
data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "gcp-us-central1"
}
But this is doesnt work main.tf
terraform {
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = "~>0.3.0"
    }
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "~>0.3.3"
    }
}                                               
}                                               
provider "ec" {                                 
  apikey = "key"                                
}                                               
provider "elasticstack" {                       
  elasticsearch {}                              
}
module "elasticcloud" {
  source           = "./modules"
}
modules.tf (modules/module.tf)
data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "gcp-us-central1"
}
doesnt work - please fix

**Comment by tobio** [comment]
From the Terraform [docs](https://www.terraform.io/language/modules/develop/providers#provider-version-constraints-in-modules):

> each module must declare its own [provider requirements](https://www.terraform.io/language/providers/requirements), so that Terraform can ensure that there is a single version of the provider that is compatible with all modules in the configuration and to specify the [source address](https://www.terraform.io/language/providers/requirements#source-addresses) that serves as the global (module-agnostic) identifier for a provider

So `modules.tf` needs to define a `required_providers` block as well:


```hcl
terraform {
  required_providers {
    ec = {
      source  = "elastic/ec"
      version = ">0.3.0"
    }
  }
}

data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "gcp-us-central1"
}
```
