### ISSUE TITLE
ec_deployment scaling down (removing masters) terraform bug

### ISSUE THREAD

**Issue by Tom-hon** [elastic/terraform-provider-ec#512]
## Readiness Checklist

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Moving down from 6 nodes allows me to remove Master nodes from the tf config

## Current Behavior

```
resource "ec_deployment" "alerting" {
  name                   = "fixture${random_string.name.result}_alerting"
  region                 = "azure-uksouth"
  version                = data.ec_stack.latest.version
  deployment_template_id = "azure-io-optimized-v2"
  elasticsearch {

   topology {
      id         = "hot_content"
      size       = "8g"
      zone_count = 3
    }
    topology {
      id         = "warm"
      size       = "8g"
      zone_count = 1
    }
    topology {
      id         = "frozen"
       size       = "8g"
      zone_count = 1
    }
     topology {
       id         = "master"
       size       = "8g"
       zone_count = 1
     }}
```

when using this topology and removing the masters & frozen, bringing the total below 6 it wont move the role back to the hot nodes, (manually removing the 6th resource through the portal will remove the masters with no issues when being applied) 
```

│ Error: failed updating deployment: 3 errors occurred:
│       * api error: cluster.dedicated_master_prohibited: Deployment template [I/O Optimized] requires at least [6] nodes before dedicated master can be specified. Found only [4] nodes in the deployment (resources.elasticsearch[0])
│       * api error: deployments.elasticsearch.node_roles_error: Invalid node_roles configuration: The node_roles in the plan contains values not present in the template. [id = hot_content] (resources.elasticsearch[0])
│       * api error: deployments.elasticsearch.node_roles_error: Invalid node_roles configuration: The node_roles in the plan contains values not present in the template. [id = warm] (resources.elasticsearch[0])
│
```

## Terraform definition

Terraform apply

## Steps to Reproduce

1. Deploy a cluster with 3 hot, 2 warm, 1 frozen, 3 masters
2. Remove the 1 frozen and 3 masters

## Context

Currently the only way I've got around this is manually scaling the cluster down through the portal and then applying the Terraform aligning it to the topology (I've only seen this when working with the masters no over node type)

## Possible Solution

This would update the deployment manifest stating that the current Hot nodes are master eligible again 

```
topology {
      id         = "hot_content"
      size       = "8g"
      is_master = true
      zone_count = 3
    }
```

## Your Environment

* Version used: 8.3.1
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: ECS
* Environment name and version (e.g. Go 1.9): 
* Server type and version: Azure hosted
* Operating System and version: 
* Link to your project:

**Comment by tobio** [comment]
Hey @Tom-hon there's a warning in the [documentation](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#resources) around removing topology elements. We also currently require those topology elements to the ordered alphabetically by their `id` which is mentioned within that section of the docs. 

Neither of those things are great though, the UX around defining Elasticsearch topology elements is something we're hoping to improve but it's a framework limitation with the Terraform SDK currently in use. There's more details in https://github.com/elastic/terraform-provider-ec/issues/336 around this.
