### ISSUE TITLE
When adding an extension it is not enabled.

### ISSUE THREAD

**Issue by sachin-frayne** [elastic/terraform-provider-ec#518]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

I would expect an extension added to a deployment via the provider to be enabled. And if I enable the extension manually changes to the deployment via terraform should not deactivate my extension.

## Current Behavior

Using the below `terrafrom.tf`, renamed to `terraform.txt` I created the deployment, the plugin is uploaded and available to the deployment, but it is not enabled.

[terraform.txt](https://github.com/elastic/terraform-provider-ec/files/9167081/terraform.txt)

<img width="1141" alt="Screenshot 2022-07-22 at 12 45 38" src="https://user-images.githubusercontent.com/32795683/180423773-20ce24e2-7d20-4286-88b1-b525c4d9ffb8.png">

## Terraform definition

[terraform.txt](https://github.com/elastic/terraform-provider-ec/files/9167081/terraform.txt)

## Steps to Reproduce

1. Add an API Key
2. Run a terraform plan & apply

## Possible Solution

Add a flag to enable the extension after adding it to deployment.

## Your Environment

* Version used: Elasticsearch `8.3.2`, elastic ec `0.4.1`
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): 
* Server type and version: 
* Operating System and version: Macos, N/A
* Link to your project:

**Comment by sachin-frayne** [comment]
This also does not work if I change the type to plugin

**Comment by tobio** [comment]
This is a display issue, and you should see the bundled plugin available in your deployment. This will be fixed in the next Cloud release (i.e sometime in the next 2 weeks). 

@sachin-frayne I've linked the Cloud issue here if you want any further context.
