### ISSUE TITLE
root.permission_denied: To access the resource the user must have the required authorization.

### ISSUE THREAD

**Issue by HarshaPradeep** [elastic/terraform-provider-ec#526]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Success API output. 

## Current Behavior

```
 Error: api error: 1 error occurred:
│       * root.permission_denied: To access the resource [r:/deployments/traffic-filter/rulesets/16161146846464684561468], the user must have the required authorization.
│ 
│ 
│   with module.deployment_traffic_filter_association.ec_deployment_traffic_filter_association.aws_private_link_endpoint_association,
│   on ../modules/deployment_traffic_filter_association/main.tf line 13, in resource "ec_deployment_traffic_filter_association" "aws_private_link_endpoint_association":
│   13: resource "ec_deployment_traffic_filter_association" "aws_private_link_endpoint_association" {

```
## Steps to Reproduce

1. Create a deployment.
2. Create a traffic rule.
3. Attach the traffic rule to the deployment. 
4.

## Context

Trying to attache the traffic rule to the deployment. However, attachment fails for terraform apply but in the elastic cloud UI, I can see the attachment has been success. I am using an API key for authorization.

## Your Environment

* Version used: TF version - 1.2.7 | EC provider version - 0.4.1
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): ES version - 7.17.6
* Server type and version: 
* Operating System and version: MAC M1

**Module**
```
terraform {
  required_providers {

    ec = {
        
      source  = "elastic/ec"
      version = "0.4.1"
    }
  }
}

#### Elastic Cluster Traffic Filter Association####
resource "ec_deployment_traffic_filter_association" "aws_private_link_endpoint_association" {

  deployment_id     = var.es_cluster_deployment_id
  traffic_filter_id = var.traffic_filter_id
}
```

**Main TF**
```
#### Elastic Cluster Traffic Rule Association ####
module "deployment_traffic_filter_association" {

  source                   = "../modules/deployment_traffic_filter_association"

  traffic_filter_id        = module.deployment.elastic_cluster_id
  es_cluster_deployment_id = module.deployment_traffic_filter.elastic_cluster_traffic_filter_id

  depends_on = [
    module.deployment,
    module.deployment_traffic_filter
  ]
}
```

**Comment by nikhil-joshi-pst** [comment]
Hello, is this issue resolved? I am also facing the same issue.If it is resolved please LMK how can I get rid of it.

**Comment by tobio** [comment]
In the original issue it looks like the `deployment_id` and `traffic_filter_id` variables are reversed, i.e the `traffic_filter_id` is being set to the Deployment ID. 

```
  traffic_filter_id        = module.deployment.elastic_cluster_id
  es_cluster_deployment_id = module.deployment_traffic_filter.elastic_cluster_traffic_filter_id
``` 

@nikhil-joshi-pst I can take a look if you want to include your TF resource definitions.
