### ISSUE TITLE
Migrate to Terraform Plugin Framework

### ISSUE THREAD

**Issue by dimuon** [elastic/terraform-provider-ec#530]
## Overview

Motivation:
- There are few defects, most notably #336, that we hope to fix once we move to the Plugin Framework
- The framework is t[he official future way](https://www.terraform.io/plugin/which-sdk) of Terraform plugin development

**Comment by d-carmo** [comment]
@dimuon is there anything pending here?

**Comment by dimuon** [comment]
@d-carmo , I'm going to release a new version of the provider soon, after this the ticket can be closed I believe.

**Comment by dimuon** [comment]
Closed by https://github.com/elastic/terraform-provider-ec/pull/567
