### ISSUE TITLE
Integrations server can't be upgraded via TF

### ISSUE THREAD

**Issue by andrewnazarov** [elastic/terraform-provider-ec#535]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

All EC components are upgraded.

## Current Behavior

During the upgrade to 8.4.1 via TF an integration server hasn't been upgraded and the warning was shown in the UI:
>Deployment upgrade failed. Could not upgrade Integrations Server to 8.4.1.

The subsequent upgrade from UI works. An interesting thing is that in Activity it says that there are no configuration changes for the integration server.
<img width="757" alt="Screenshot 2022-09-14 at 12 10 23" src="https://user-images.githubusercontent.com/11255710/190113694-c57bf47c-8f2f-417c-bfa8-ceaab4788f27.png">

## Terraform definition

```
resource "ec_deployment" "default" {
  name                   = var.deployment_name
  alias                    = var.deployment_alias
  region                 = "gcp-${var.gcp_region}"
  version                = var.ec_version != "" ? var.ec_version : data.ec_stack.latest.version
  deployment_template_id = var.deployment_template_id

  elasticsearch {

    autoscale = var.autoscale_enabled

    dynamic "config" {
      for_each = var.user_settings_enabled ? toset([1]) : toset([])
      content {
        user_settings_yaml = var.user_settings_yaml_elasticsearch
      }
    }

    topology {
      id         = "hot_content"
      size       = var.memory_hot_content
      zone_count = var.zone_count
    }

    topology {
      id   = "ml"
      size = var.memory_ml
    }

    topology {
      id         = "warm"
      size       = var.memory_warm
      zone_count = var.zone_count
    }
  }

  kibana {
    dynamic "config" {
      for_each = var.user_settings_enabled ? toset([1]) : toset([])
      content {
        user_settings_yaml = var.user_settings_yaml_kibana
      }
    }
  }

  integrations_server {}

  lifecycle {
    ignore_changes = [
      elasticsearch[0].topology[0].size,
      elasticsearch[0].topology[1].size,
      elasticsearch[0].topology[2].size,
    ]
  }
}

```

## Steps to Reproduce

1. Apply the TF code
2. Go to the EC UI
3. See the warning

## Your Environment

Elastic Cloud SaaS

**Comment by tobio** [comment]
@andrewnazarov can you confirm you're running 0.4.1, upgrading integration server should have been supported in that version.

**Comment by andrewnazarov** [comment]
@tobio, ah, my bad. We are on 0.4.0. We use Renovate to update stuff and I checked that there were no open merge requests for this provider. But it seems something got broken with our auto-update process. Will close this then. Thanx!
