### ISSUE TITLE
observability deployment_id self

### ISSUE THREAD

**Issue by jonnymccullagh** [elastic/terraform-provider-ec#570]
I am following the documentation here: https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment

It says that I can use:
```
observability {
  deployment_id = "self"
}
```
To store the observability data in the current deployment. However I get an error in terraform using that:
```
│ Error: observability ref_id auto discovery: deployment get: 1 error occurred:
│       * id "self" is invalid
```
Maybe I have this block in the wrong place?

**Comment by jonnymccullagh** [comment]
No I actually gave up on using terraform for elastic. The resources that can be managed feel very limited so not any huge benefits from managing the cluster setup from TF rather than the UI. I had been hoping to manage dashboards, indexes etc but I don't think it supports all the resources.

**Comment by andrea-berling** [comment]
Btw, the solution turned out to be to bump the provider version up to the latest version (v0.5.0)

**Comment by tobio** [comment]
@jonnymccullagh @andrea-berling fwiw the [Elastic Stack](https://github.com/elastic/terraform-provider-elasticstack) provider supports managing Elasticsearch resources and we're working on supporting Kibana (specifically alerts and dashboards) now.

**Comment by Kushmaro** [comment]
@andrea-berling @jonnymccullagh as mentioned - you need to update the provider for the functionality to be available :) 
and as @tobio mentioned, the Elastic Stack provider supports Elastic stack object configuration.

Closing this issue for now.
