### ISSUE TITLE
What's advised guideline to update Advanced settings - Kibana custom configuration?

### ISSUE THREAD

**Issue by LeaNemec** [elastic/terraform-provider-ec#572]
Hello, 

I've applied successfully custom changes to the Kibana default configuration via curl command.
I'd like to replace id of saved object to be dynamic in curl, so it always takes latest version of Kibana on terraform apply step. 
My attempts using following documentation were not successful. Perhaps I am taking wrong approach entirely or I missed out something? https://registry.terraform.io/providers/elastic/ec/latest/docs/data-sources/ec_deployments#argument-reference

I'd like to replace "8.5.3" to be dynamic, so it always takes latest version of Kibana on terraform apply step
```
curl .../api/saved_objects/config/`8.5.3`
# I replaced it with parameter but getting error on terraform apply:
# This object has no argument, nested block, or exported attribute named "version".
curl .../api/saved_objects/config/$1
```

outputs.tf
```
 output "kibana_version" {
   value = ec_deployment.example.kibana[0].version
 }
```

provisioner includes:
```
${ec_deployment.example.kibana[0].version}
```

**Comment by tobio** [comment]
```hcl 
output "kibana_version" {
   value = ec_deployment.example.kibana[0].version
}
```
It looks like this code is refering to an `ec_deployment` resource, not an `ec_deployment` data source. The [version attribute](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#version) exists at the deployment level on the resource. 

The intended behaviour is that all components of a deployment are running a consistent stack version, however issues encountered during upgrades may result mixed versions. Having deployment level versions for the resource, and component level versions on the data sources best represents this reality.

**Comment by LeaNemec** [comment]
Thank you very much tobio 🙏🏻 , indeed I was attempting at the wrong source.
I had a better look now, scrapped output and set provisioner attribute to point at `${data*.*.version}`, first attempt with your correction worked 👍🏻
