### ISSUE TITLE
Deployment creation failure

### ISSUE THREAD

**Issue by Lagoran** [elastic/terraform-provider-ec#585]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Current Behavior

When trying to create ES and observability clusters using the elastic ec TF provider in ES Cloud SaaS, I am getting following error:
Error: failed creating deployment: 2 errors occurred: * api error: deployment_alias.alias_unavailable: This alias is not available. * set "request_id" to "<64 symbol hash string>" to recreate the deployment resources

## Steps to Reproduce

1.
2.
3.
4.

## Context

I am trying to create a new ES cluster using existing configuration from already created deployments.

## Possible Solution

I guess issue is related to those code blocks:

https://github.com/elastic/terraform-provider-ec/blob/2ee0f61c5d63fdb63a7185f39a6434f531a50735/ec/ecresource/deploymentresource/schema.go
https://github.com/elastic/terraform-provider-ec/blob/9438c65eda962409493de4ae55be6953bdebd952/ec/ecresource/deploymentresource/create.go

## Your Environment

* Version used: TF 1.3.0; ES 8.6.2
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version:Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9):
* Server type and version:AWS based EC2
* Operating System and version:
* Link to your project:

**Comment by tobio** [comment]
@Lagoran This error indicates that the generated alias for this deployment has already been taken. Try either re-naming your deployment or setting the [`alias`](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#alias) to something unique.

For example, the [Configuring an SSO provider](https://registry.terraform.io/providers/elastic/ec/latest/docs/guides/configuring-sso-ec-deployment) guide appends a 6 character random string to the deployment alias.
