### ISSUE TITLE
Integrations_Server terraform block

### ISSUE THREAD

**Issue by arul24ar** [elastic/terraform-provider-ec#594]
1) Using es_stack version 8.6.1
2) Trying to create Integration_Servers via terraform - using azure provider.
3) When I try to use the integrations_server block as defined in the docs, I get an error with terraform plan, refer below : 
docs reference:   https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#integrations_server
4) Hardware used : **azure-storage-optimized**

Error: Unsupported block type
│ 
│   on main.tf line 56, in resource "ec_deployment" "elasticsearch":
│   56:   integrations_server {
│ 
│ Blocks of type "integrations_server" are not expected here.
------------------------------
I using the block type as defined in the latest docs. Kindly let me know if I am missing anything.

**Comment by tobio** [comment]
@arul24ar which version of the provider are you using here?

**Comment by arul24ar** [comment]
data "ec_stack" "latest" {
  version_regex = "latest"
  region        = "us-east-1"
}

resource "ec_deployment" "example_minimal" {
  count = var.es_cluster ? 1:0
  name = var.es_deployment_name
  deployment_template_id = var.es_template_id
  region = data.es_stack.latest.region
  version = data.es_stack.latest.version_regex
  tags = var.resource_tags

  elasticsearch = {
    autoscale = var.auto_scale
    topology {
      id = var.es_topology_id[0]
    }
    topology {
      id = var.es_topology_id[1]
    }
    topology {
      id = var.es_topology_id[2]
    }
    topology {
      id = var.es_topology_id[3]
      size = var.ml_instance_size
      autoscaling {
         = var.ml_instance_size
      }
    }
     topology {
      id = var.es_topology_id[4]
     }
    }
  kibana = {
    topology {
       size = var.ki_instance_size
    }
  }

  integrations_server = {
    topology {
      zone_count = 1
       size = '1g'
    }
  }
  enterprise_search = {}
}

**Comment by arul24ar** [comment]
Using the latest version 8.6.2

**Comment by pascal-hofmann** [comment]
@arul24ar Can you post the full output of `terraform -version`?

I guess you are using terraform-provider-ec 0.6.0 which has a different syntax than the previous version.

**Comment by arul24ar** [comment]
@pascal-hofmann - I am able to deploy with version 0.6.0. Earlier I was using the very old version 0.2.0. 
Thank you for the support.
