### ISSUE TITLE
Add monitoring via log delivery APIs

### ISSUE THREAD

**Issue by marclop** [elastic/terraform-provider-ec#60]
## Overview

Add monitoring object which uses the "log delivery" mechanism.

## Possible Implementation

Use the new Log delivery APIs available after MS46 is deployed.

**Comment by karencfv** [comment]
Blocked until MS46 is released

**Comment by marclop** [comment]
@Kushmaro how similar do should we make this to our UI?

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/7286993/95852716-dd8ba180-0d5c-11eb-8c7a-90074e5e4189.png">

```hcl
resource "ec_deployment" "lnm" {
  ...
  observability {
    deployment_id = "some target deployment id"
    logs          = true
    metrics       = true
  }
}
```

The API accepts 2 different destinations (maybe you want to send logs to a deployment and metrics to another). So technically we could send to different destinations, that would look like:

```hcl
resource "ec_deployment" "lnm" {
  ...
  observability {
    logs    = "some target deployment id"
    metrics = "some target deployment id"
  }
}
```

I'll also let @karencfv chime in since she's assigned this issue to herself, maybe she's got some good ideas here too.

**Comment by ggsood** [comment]
I think we also need to update elastic cloud sdk version for it

**Comment by marclop** [comment]
> I think we also need to update elastic cloud sdk version for it

It's already up to date, no need to update it.

**Comment by Kushmaro** [comment]
@marclop the API accepting two locations is for flexibility / later API expansion if needed.
we shouldn't need to this at this time.
I'm ++ on
observability {
    deployment_id = "some target deployment id"
    logs          = true
    metrics       = true
 }

can we default for both being true?

**Comment by marclop** [comment]
Yes, we can set both to true by default, as long as we document it properly I don't see any problem with that.

**Comment by karencfv** [comment]
Ha! Good thing you asked @marclop, I had already thought of using

```tf
resource "ec_deployment" "lnm" {
  ...
  observability {
    logs    = "some target deployment id"
    metrics = "some target deployment id"
  }
}
```

Although...

> the API accepting two locations is for flexibility  / later API expansion. We shouldn't need to this at this time.

The difference from the UI and the provider, is that with the former one day you'll find a new button that gives you the option to have 2 destinations which doesn't disrupt anyone, but with the provider this would be somewhat annoying for our users to change if we want to give them the option later on. When they update to a newer version their configurations will break and they'll have to change them. 

Might it not make sense for the provider to allow 2 destinations from the beginning?

**Comment by Kushmaro** [comment]
@karencfv I understand, but be aware that I'm not sure if currently this option had been thoroughly tested as of now. So I'm wondering how badly we'd want to expose it externally.. so I'd personally prefer all clients to behave in a single fashion, even if the API allows for some extended functionality.

@s-nel , any thoughts on this?

**Comment by s-nel** [comment]
I agree with @Kushmaro. Would prefer to keep one destination for now

**Comment by ggsood** [comment]
I think we should follow the same functionality as UI, for consistent experience.
