### ISSUE TITLE
Consider updating dependencies to Plugin Framework v1.1.1

### ISSUE THREAD

**Issue by AaronFriel** [elastic/terraform-provider-ec#607]
## Description

Hey folks, my team at Pulumi maintains an Elastic Cloud provider and we're currently blocked due to the pre-release version of the Terraform Plugin Framework used in this repository.

See: 
- https://github.com/pulumi/pulumi-ec/issues/56

Would it be possible to update the Go dependencies and implementation to the GA version of the TF Plugin Framework?

**Comment by pascal-hofmann** [comment]
Updating to 1.1.1. is not possible. See https://github.com/elastic/terraform-provider-ec/pull/567#issuecomment-1443540314.

[1.2.0 was released recently](https://github.com/hashicorp/terraform-plugin-framework/releases/tag/v1.2.0). Upgrading to this might work.

CC @dimuon.

**Comment by dimuon** [comment]
Pinging @Kushmaro for sorting out priorities.

**Comment by Kushmaro** [comment]
@dimuon this is currently not a priority for us, unfortunately. 

@AaronFriel , do you have some stats on how many Pulumi users utilize the pulumi Elasitc Cloud Provider?

**Comment by AaronFriel** [comment]
We expect to support 1.20, if that's a viable upgrade using the existing PR, that's a good path for us.

@Kushmaro I don't think I can share here, of course. I know we have mutual customers.

**Comment by brucetan-displayr** [comment]
We are customer of elastic and use Pulumi to provision elastic infrastructure. We are getting blocked to update our infrastructure due to this issue. It would be much appreciated if this is prioritized @Kushmaro 

CC: @yuft
