### ISSUE TITLE
Add resource ec_snapshot_repository

### ISSUE THREAD

**Issue by pascal-hofmann** [elastic/terraform-provider-ec#608]
## Overview
There is currently no way to create snapshot repositories via terraform. 

## Possible Implementation
The ECE UI currently only shows fields for S3 and has an advanced edit for other types. To get a working MVP I think it makes sense to only add S3 for now and add the rest as the need arises.

```
resource "ec_snapshot_repository" "this" {
  name = "my-snapshot-repository" 
  s3 = {
    region     = "eu-central-1",
    bucket     = "my-bucket",
    access_key = "my-access-key",
    secret_key = "my-secret-key"
  }
}
```

## Testing
- Create snapshot repository.
- Change snapshot repository and verify it was changed.
- Delete snapshot repository.

## Your Environment
ECE 3.5.1

## API documentation
- [Platform - Repository - CRUD](https://www.elastic.co/guide/en/cloud-enterprise/current/Platform_-_Repository_-_CRUD.html)
- [SnapshotRepositoryConfiguration](https://www.elastic.co/guide/en/cloud-enterprise/current/SnapshotRepositoryConfiguration.html)
- [S3 repository](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#repository-s3-repository)

# Related links
- [elasticsearch_snapshot_repository](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_snapshot_repository) resource from terraform-provider-elasticstack

# Screenshots
![Bildschirm­foto 2023-03-23 um 08 42 09](https://user-images.githubusercontent.com/2102878/227135945-fe8d0e4a-ca22-47e0-bd0a-03bd636d12de.png)
![Bildschirm­foto 2023-03-23 um 08 42 57](https://user-images.githubusercontent.com/2102878/227136106-d80c5a77-3547-48c4-bfc5-3be049954f59.png)

**Comment by pascal-hofmann** [comment]
@Kushmaro I want to work on this and #602. Can you please extend my trial (org ID 4184822784)?

As both are things which are available in the ECE UI I do think they also should be part of the provider.

**Comment by Kushmaro** [comment]
Hey @pascal-hofmann , for the delays on this one, few weeks have been busy.
I can't extend that specific org any longer, so I suggest you - 
1. Remove all deployments / resources in that org
2. Go to the org screen and leave the org
3. Login back to Elastic Cloud and create a new org, you should be able to create a new Trial period that way.

I'm ok with adding this specific s3 ece repository functionality lets please indeed limit it only to s3 at this point in time.

**Comment by Kushmaro** [comment]
@pascal-hofmann , this specific functionality is blocked for ESS customers, its only available against ECE, as the permission / role required for doing this on ECE is admin-leveled. ESS users do not have this permission
