### ISSUE TITLE
Importing existing ec_deployment resources for 0.6.0 upgrade elasticsearch credentials

### ISSUE THREAD

**Issue by ssaitta** [elastic/terraform-provider-ec#615]
# Overview
I'm updating the provider to 0.6.0 on an existing project. I have reimported my ec_deployment resources, however, I see in your docs that `Importing a deployment will not import the elasticsearch_username or elasticsearch_password attributes.`. 

My project uses these credentials to authenticate the `elasticstack` provider like this:

```
provider "elasticstack" { 
  elasticsearch {
    endpoints = ["${ec_deployment.REOURCE_NAME.elasticsearch.https_endpoint}"]
    username  = ec_deployment.REOURCE_NAME.elasticsearch_username
    password  = ec_deployment.REOURCE_NAME.elasticsearch_password
  }
}
```

The provider is not throwing any errors, but all the resources I have using that provider throw authentication errors.

Do you have any advice on retrieving these credentials from the existing ec_deployment resource and importing them in the state file so that my provider will authenticate again?

**Comment by pascal-hofmann** [comment]
I guess the quickest way to solve this is extracting them from the old state file and pasting them into the new state file. Make sure to increase the `serial` in the state when editing manually.

**Comment by ssaitta** [comment]
> I guess the quickest way to solve this is extracting them from the old state file and pasting them into the new state file. Make sure to increase the `serial` in the state when editing manually.

That's the only solution I've been able to come up with, but I was hoping there was a better way than manually updating the state files.

**Comment by tobio** [comment]
The 0.8.0 provider version adds a [`reset_elasticsearch_password`](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/deployment#reset_elasticsearch_password) attribute which will reset these credentials on the next `terraform apply`. This can be set to `true` for the first apply after an import to have the credentials available.
