### ISSUE TITLE
Provisioning Machine Learning instance

### ISSUE THREAD

**Issue by virtualaidev** [elastic/terraform-provider-ec#627]
going through the documentation, I don't see anything that relates to provisioning a Machine Learning instance. Any workaround to provision this in terraform using ec provider? If not will this be added as a feature?

**Comment by tobio** [comment]
This is possible by adding an `ml` topology block in the existing `ec_deployment` resource. [This](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/ec_deployment#tiered-deployment-with-autoscaling-enabled) example from the docs includes  such a block:

```hcl
    ml = {
      autoscaling = {}
    }
```
