### ISSUE TITLE
Feature Request: Add RBAC support / user management feature 

### ISSUE THREAD

**Issue by pakio** [elastic/terraform-provider-ec#629]
## Overview

This is the feature request for supporting RBAC and user management feature on this provider.

## Context

Recently Elastic announced that [they started providing the RBAC feature on Elasticsearch service](https://www.elastic.co/guide/en/cloud/current/ec-release-notes-2023-04-18.html).
Though this provider is not yet supporting managing the users by code, this is the feature that many users were wanted for a long time and I suppose there are definitely high demand to manage them in a safer way.

**Comment by dimuon** [comment]
@Kushmaro , I guess this requires adding a dedicated resource to the provider.

**Comment by Kushmaro** [comment]
Yes @dimuon

**Comment by gigerdo** [comment]
This functionality will be included in the upcoming 0.12.0 release.
