### ISSUE TITLE
Failed to read ec_deployment data source with 0.6.0

### ISSUE THREAD

**Issue by GopalaDuggina** [elastic/terraform-provider-ec#631]
## Expected Behavior
Terraform should be able to retrieve information about an existing Elastic Cloud deployment using "ec_deployment" data source 
## Current Behavior

I have a TF config file to build the cluster and I am using existing deployment to enable the observability in the new deployment.  

Terraform throwing an error while reading "ec_deployment" data source, I didn't have any issues with older version (0.5.1) of the provider

My current configuration

main.tf

![image](https://user-images.githubusercontent.com/62770568/234922874-e1bb2aae-5ee4-4f79-8aa9-94485ce79d30.png)

deployment.tf

![image](https://user-images.githubusercontent.com/62770568/234920740-663d6be7-9166-4140-9ae6-90f8a8f68337.png)

and this is the TF error message

![image](https://user-images.githubusercontent.com/62770568/234921860-1cd2d837-b3ce-4999-9e34-a6daa2e9a07d.png)

## My Environment

Version used: 

Elastic/ec v0.6.0
Terraform v1.4.2

**Comment by tobio** [comment]
Duplicated by https://github.com/elastic/terraform-provider-ec/issues/649
