### ISSUE TITLE
Version error after upgrade

### ISSUE THREAD

**Issue by anero** [elastic/terraform-provider-ec#633]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Terraform plan does not show any differences with current infrastructure state.

## Current Behavior

Running `terraform plan` shows the following permanent diff on the deployment version:

```
  # ec_deployment.agra_search_deployment will be updated in-place
  ~ resource "ec_deployment" "agra_search_deployment" {
      + apm_secret_token       = (sensitive value)
      ~ elasticsearch          = {
          ~ cloud_id       = <REDACTED> -> (known after apply)
          ~ http_endpoint  = "http://<REDACTED>.eu-central-1.aws.cloud.es.io:9200" -> (known after apply)
          ~ https_endpoint = "https://<REDACTED>.eu-central-1.aws.cloud.es.io:443" -> (known after apply)
          ~ resource_id    = <REDACTED> -> (known after apply)
            # (12 unchanged attributes hidden)
        }
        id                     = <REDACTED>
        name                   = "agra-production-eu-central-1"
      ~ version                = "7.16.2" -> "7.17.9"
        # (6 unchanged attributes hidden)
    }
```

Attempting to apply the changes with `terraform apply` throws the following error:

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to ec_deployment.agra_search_deployment, provider "provider[\"registry.terraform.io/elastic/ec\"]" produced an unexpected new value: .version: was cty.StringVal("7.17.9"), but now cty.StringVal("7.16.2").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

```

## Terraform definition

```
data "ec_stack" "latest_patch" {
  version_regex = "^7.*"
  region        = "eu-central-1"
}

resource "ec_deployment" "agra_search_deployment" {
  # Optional name.
  name = "agra-production-eu-central-1"

  # Mandatory fields
  region                 = "eu-central-1
  version                = data.ec_stack.latest_patch.version
  deployment_template_id = "aws-storage-optimized"

  elasticsearch = {
    cold = {
      autoscaling = {}
    }

    coordinating = {
      autoscaling = {}
    }

    frozen = {
      autoscaling = {}
    }

    hot = {
      autoscaling = {}
      id   = "hot_content"
      size = "1g"
      zone_count = var.app_environment == "staging" ? 1 : 2
    }

    master = {
      autoscaling = {}
    }

    ml = {
      autoscaling = {}
    }

    warm = {
      autoscaling = {}
    }
  }

  traffic_filter = [
    ec_deployment_traffic_filter.deployment_filter.id
  ]
}
```

The problem persist even after having manually updated terraform's `.tfstate` file, replacing all references to 7.16.2 with 7.17.9.

## Steps to Reproduce

1. Create a new elasticsearch deployment on v7.16.2 using terraform
2. Update the terraform template to use v7.17.9
3. Apply terraform changes

## Context

Terraform shouldn't detect any required changes on the deployment's version.

## Possible Solution

--

## Your Environment

* Version used: 0.6.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): `go version go1.20.3 linux/amd64`
* Server type and version: Elasticsearch 7.17.9
* Operating System and version: Ubuntu 23.04
* Link to your project: This is a private project

Our full suite of terraform providers is:

```
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/betterstackhq/better-uptime v0.3.14
+ provider registry.terraform.io/cloudflare/cloudflare v4.4.0
+ provider registry.terraform.io/elastic/ec v0.6.0
+ provider registry.terraform.io/hashicorp/aws v4.65.0
+ provider registry.terraform.io/hashicorp/http v3.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

**Comment by tobio** [comment]
Duplicates #614 
Fixed by https://github.com/elastic/terraform-provider-ec/pull/623

@anero this issue has been fixed in the main branch, and we'll be releasing a 0.7 provider later this week. It's mentioned in #614, but the underlying issue here is that you've previously had Enterprise Search, APM, and Kibana running in this deployment on 7.16.2, those resources were shut down and then later Elasticsearch was upgraded to 7.17.9. The provider is incorrectly using the lowest version across all resources, not just those that are running. To fix this in the meantime, you can restart Enterprise Search, APM, and Kibana (which will upgrade them to 7.17.9), and then shut them back down.

**Comment by anero** [comment]
Great, thanks for the explanation @tobio and apologies for the duplicate issue.
