### ISSUE TITLE
Provider upgrade error

### ISSUE THREAD

**Issue by 80kk** [elastic/terraform-provider-ec#636]
I am trying to upgrade provider from `0.5.0` to `0.7.0` but I am getting following error in Terraform:
```
 Warning: Failed to decode resource from state
 
 Error decoding "ec_deployment.xyz" from prior state:
 missing expected {


 Error: Unable to Upgrade Resource State
 
   with ec_deployment.xyz,
   on xyz.tf line 15, in resource "ec_deployment" "xyz":
   15: resource "ec_deployment" "xyz {
 
 This resource was implemented without an UpgradeState() method, however
 Terraform was expecting an implementation for version 1 upgrade.
 
 This is always an issue with the Terraform Provider and should be reported
 to the provider developer.
```
No matter which Terraform version I am using. I've also tried to upgrade to `0.6.0` first but same error is being presented. How can I upgrade to the latest `0.7.0` provider?

**Comment by tobio** [comment]
This is a [documented limitation](https://github.com/elastic/terraform-provider-ec#moving-to-the-provider-v060) for 0.6 and higher. As per the readme, the current upgrade path is by re-importing existing deployments.
