### ISSUE TITLE
Allow requesting the proper private_connection_resource_alias

### ISSUE THREAD

**Issue by dhilgarth** [elastic/terraform-provider-ec#644]
## Overview

Currently, I have to manually look up the value for private_connection_resource_alias when I want to create a private endpoint between Elastic Cloud and Azure.

It would be helpful if I could just us a new azure_private_connection_resource_alias data source to look this alias up by providing the hyperscaler - azure in this case - and the region. Also, a similar data source for AWS would be needed. GCP doesn't necessarily need one, because it can be constructed.

**Comment by tobio** [comment]
@dhilgarth is this fixed by [azure_privatelink_endpoint](https://registry.terraform.io/providers/elastic/ec/latest/docs/data-sources/azure_privatelink_endpoint) and [aws_privatelink_endpoint](https://registry.terraform.io/providers/elastic/ec/latest/docs/data-sources/aws_privatelink_endpoint)?

**Comment by dhilgarth** [comment]
Yes, it helps. However, the documentation about aws_privatelink_endpoint isn't correct. It uses ec_*azure*_... in the example and also the region name is incorrect, it should be us-east-1 or something like that.
