### ISSUE TITLE
Semantic Versioning Violation | Minor Breaking Changes 0.6 -> 0.7

### ISSUE THREAD

**Issue by cgi-gerlando-caldara** [elastic/terraform-provider-ec#645]
## Readiness Checklist
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
0.6 to 0.7 => MINOR version when you add functionality in a backward compatible manner
Existing Terraform Code must run with the new minor version.
[Semantic Versioning](https://semver.org/)

## Current Behavior
Terraform updated the provider as specified to next minor version and the breaking changes of the terraform provider blocked the productive environment rollout.

Error Message on all terraform applies:

│ Error: Value Conversion Error
│ 
│   with module.ec_deployment.test,
│   on elasticcloud.tf line 11, in resource "ec_deployment" "test":
│   11: resource "ec_deployment" "test" {
│ 
│ An unexpected error was encountered trying to build a value. This is always
│ an error in the provider. Please report the following to the provider
│ developer:
│ 
│ Received unknown value, however the target type cannot handle unknown
│ values. Use the corresponding `types` package type or a custom type that
│ handles unknown values.
│ 
│ Path: repository.reference
│ Target Type: *v2.ElasticsearchSnapshotRepositoryReference
│ Suggested Type: types.Object
╵

## Terraform definition
General Issue of upgraded version.

## Steps to Reproduce
1. Setup terraform provider elatic/ec for version ~> 0.6
2. Wait for the 4.5.2023 new terraform provider minor upgrade 0.7
3. See how your tested and working terraform apply stopped on provider error

## Context
Productive environment was unable to deploy

## Possible Solution
Manually fix terraform version to fix version to exclude minor breaking changes but allow patches.
Because terraform provider violated sematic versioning.
`    ec = {
      source  = "elastic/ec"
      version = "~> 0.6.0"
    }
`

## Your Environment
* Version used: 0.6/0.7
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud
* Environment name and version (e.g. Go 1.9): Universal
* Server type and version: Universal
* Operating System and version: Ubuntu 20.04
* Link to your project: -

**Comment by Kushmaro** [comment]
@cgi-gerlando-caldara , as per semantic versioning rule No. 4 which reads: 
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

There's no violation of semantic versioning here, and that was with intent.
closing this one.

**Comment by Kushmaro** [comment]
@cgi-gerlando-caldara , developing software without breaking changes is tough. Unfortunately, some breakage between 0.5->0.6 and 0.6-0.7, was a must, due to terraform libraries and dependencies.
