### ISSUE TITLE
ec_deployment_extension download fails with redirects

### ISSUE THREAD

**Issue by robmaxwellirl** [elastic/terraform-provider-ec#657]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

When using the ec_deployment_extension and referencing a package from github packages, it should follow any redirects and download the package.

## Current Behavior

When referencing a new extension from github packages to be used in a deployment, because of the nature of github, it will redirect the link to download to a static user endpoint URL instead which is dynamically created on the initial GET request.

As a result of this, when using the resource, it fails as it complains that the HTTP response code is a 302, rather than following the links through and getting the package through.

Error message is as follows from an attempted apply with terraform

```
│ Error: api error: 1 error occurred:
│ 	* extensions.request_execution_failed: Errors: [Cannot download from [https://github.com/medcl/elasticsearch-analysis-stconvert/releases/download/v8.7.0/elasticsearch-analysis-stconvert-8.7.0.zip]. Received HTTP response code [302]]
│ 
```

## Terraform definition

```hcl
resource "ec_deployment_extension" "stconvert_plugin" {
  name           = "analysis-stconvert"
  version        = "8.7.0"
  extension_type = "bundle"
  download_url   = "https://github.com/medcl/elasticsearch-analysis-stconvert/releases/download/v8.7.0/elasticsearch-analysis-stconvert-8.7.0.zip"
}
```

## Steps to Reproduce

1. Setup a new cluster creation, and reference the deployment extension above
2. Try and apply
3. See the error given back.
4. Curl to the package from your local, with verbose enabled and see how the redirect occurs.

## Context

This means some additional steps to download the package, upload it to a static site (s3 bucket) and reference it from there instead.

## Possible Solution

Allow the resource to follow redirects in order to download the package completely

## Your Environment

* Version used: 0.7.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: Elastic Cloud SaaS
* Environment name and version (e.g. Go 1.9): N/A (Cloud)
* Server type and version: N/A
* Operating System and version: N/A (Terraform 1.3.4)
* Link to your project: It's a private repo within our org, can duplicate code if needed.

**Comment by tobio** [comment]
This is a [limitation](https://www.elastic.co/guide/en/cloud/current/ec-plugins-guide.html#ec-extension-guide-create) of the underlying Cloud API. The provider does support uploading a local file, so there's no requirement to upload it to a static site.
