### ISSUE TITLE
Request:  Allow ec_deployment resource to create an optional api key and have its value as a sensitive output

### ISSUE THREAD

**Issue by shermanericts** [elastic/terraform-provider-ec#658]
## Overview

When onboarding new customers, we instantiate an Elastic Deployment.  The idea is that we can onboard in one step (I know there's some limitations such as https://github.com/elastic/terraform-provider-ec/issues/433).  That withstanding, in a perfect word I would love the ability to.

1.  Create an elastic deployment using `ec_deployment` + pass in an api_key request (see below).
2.  Elastic creates the deployment first then the API key as apart of the same resource.
3.  That output can be used by the `ec.apikey` provider value for all future auth requests.

It might be that this feature somehow already exists.  I tried using a series of external data resources and local_exec resources, but I couldn't get things to work the way I wanted.

## Possible Implementation

Have the ability (not required) to specify an api_key akin to [ElasticSearch Params](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html)
```
resource "ec_deployment" "customer" {
  name                   = local.deployment_name
  alias                  = local.elastic_deployment_alias
  region                 = "gcp-${var.region}"
  ...
  api_key = {
      name = "mykey"
      role_descriptors = {
         role_a = {
         ....
    

  elasticsearch = {
    autoscale = "true"
    hot = {
      autoscaling = {
        max_size          = local.elastic_hot_max_size
        max_size_resource = "memory"
      }
      size          = local.elastic_hot_size
      size_resource = "memory"
      zone_count    = 2
    }
```

## Testing
Verify that the correct API key is created with correct params.
Verify that removing the ec_deployment resource deletes the API key first.

## Context
As mentioned above, it makes us either have to do multiple steps in our customer onboarding process and/or use the elastic username and password combination for Auth which is dissuaded by Elastic whenever possible.

## Your Environment
This could be run under automation or ad hoc.

**Comment by tobio** [comment]
This is possible, but combining both `terraform-provider-ec` and `terraform-provider-elasticstack`. There's an [example](https://github.com/elastic/terraform-provider-elasticstack/tree/main/examples/cloud) of doing so in the Elastic Stack provider repo. 

Where that example sets up users and index templates, you would instead create an [elasticstack_elasticsearch_api_key](https://github.com/elastic/terraform-provider-elasticstack/blob/main/examples/resources/elasticstack_elasticsearch_security_api_key/resource.tf) resource and use the result of that throughout the rest of your onboarding process.

**Comment by shermanericts** [comment]
Thank you @tobio

**Comment by shermanericts** [comment]
@tobio I noticed this in https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_index_lifecycle#nestedblock--elasticsearch_connection where I would chain/send up the apiKey created.  Is this approach deprecated?


[elasticsearch_connection](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_index_lifecycle#elasticsearch_connection) (Block List, Max: 1, Deprecated) Elasticsearch connection configuration block. This property will be removed in a future provider version. Configure the Elasticsearch connection via the provider configuration instead. (see [below for nested schema](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/elasticsearch_index_lifecycle#nestedblock--elasticsearch_connection))

**Comment by tobio** [comment]
Yep, as per the docs resource level connection properties are deprecated. They can lead to confusing behaviour on import. If you're working with multiple instances of the stack provider within the module you should instead use an [aliased provider instance](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations)

**Comment by shermanericts** [comment]
Thanks @tobio. Unfortunately for our use case, we leverage multiple GCP projects with 1 elastic deployment per each.  I can't see how having aliased providers would help in this case. 
All the same no worry, I have a workaround.  Appreciate the time!
