### ISSUE TITLE
Please re-add Private Connect datasource

### ISSUE THREAD

**Issue by joelsdc** [elastic/terraform-provider-ec#668]
## Overview
Private Connect datasources are missing from the latest v0.7.0 release.

## Possible Implementation
They existed and worked in v0.5.1
They existed but were broken in v0.6.0 (due to the migration to TF plugin framework)
They don't exist anymore in v0.7.0.

## Context
See: https://github.com/elastic/terraform-provider-ec/issues/595
And: https://github.com/elastic/terraform-provider-ec/issues/595#issuecomment-1451188464

**Comment by tobio** [comment]
They've been made available again in master as part of https://github.com/elastic/terraform-provider-ec/pull/659 and will be available in the next release.
