### ISSUE TITLE
Document configuring GCS/Azure snapshot repositories through the generic repository type. 

### ISSUE THREAD

**Issue by ezienecker** [elastic/terraform-provider-ec#710]
The current docs for `ec_snapshot_repository` only include examples for configuring an S3 style repository. We should detail how to configure the `generic` repository type, including examples for Azure and GCS. 

## Original issue
---------------------------

## Overview
ec_snapshot_repository currently only supports S3. It would be an advantage if the other cloud providers such as Azure were also supported.

## Possible Implementation
```
resource "ec_snapshot_repository" "this" {
  name = "my-snapshot-repository" 
  azure = {
    container = "my-container"
  }
}
```

## Testing
* Create snapshot repository.
* Change snapshot repository and verify it was changed.
* Delete snapshot repository.

## Context
For migrations and backups I need to register in Elastic Cloud Repository.

**Comment by tobio** [comment]
> ec_snapshot_repository currently only supports S3

The resource already supports a `generic` snapshot repository type. [This](https://github.com/elastic/terraform-provider-ec/pull/613#discussion_r1165392341) comment can be used as an example of registering an Azure snapshot repository, but in general any both [GCS](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-gcs.html) and [Azure](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-azure.html) repositories can be added through the `generic` block. 

We need to improve the docs here with examples for GCS/Azure though, I'm updating this issue to make those doc improvements.
