### ISSUE TITLE
Region is both required and read-only preventing import

### ISSUE THREAD

**Issue by honzakral** [elastic/terraform-provider-ec#716]
When we try to import existing deployment to a terraform env we are getting an error from the provider saying that we can't set the region attribute because it's a read-only field. However, if we try to remove it, then it fails saying that region is a required parameter.

![image (24)](https://github.com/elastic/terraform-provider-ec/assets/32132/816c2df4-e9c5-4245-89ad-24622f60febc)
![image (25)](https://github.com/elastic/terraform-provider-ec/assets/32132/e5f9226e-5261-4a73-99bd-d5b4d6e63813)

**Comment by mgreenSP23** [comment]
Any update to this issue?  I'm receiving the same error.

**Comment by tobio** [comment]
@mgreenSP23 it's possible this is related to using the provider with an older TF CLI version. Are you able to share which CLI version you're using, and try again with a later version as well?

**Comment by tobio** [comment]
@mgreenSP23 if you're still having issues are you able to provide a minimal repro, or just:

* The output of `terraform version` from where you're managing these resources
* The `ec_deployment` resource definition, including the values of any referenced variables.

**Comment by mgreenSP23** [comment]
Hello @tobio, thanks for replying.

terraform version => Terraform v1.5.7
terragrunt version => Terraform v1.5.7

`resource "ec_deployment" "elasticcloud_deployment" {
  name                   = var.name
  region                 = var.ec_region
  version                = data.ec_stack.v7.version
  deployment_template_id = var.deployment_template_id

  apm = {
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    ref_id = "main-apm"

    topology = {
      instance_configuration_id = "gcp.apm.n2.68x32x45"
      size = "1g"
      size_resource = "memory"
      zone_count = "1"
    }
  }

  elasticsearch = {
    autoscale = "true"
    trategy  = "grow_and_shrink"

    hot = {
      id         = "hot_content"
      zone_count = 2
      instance_configuration_id = "gcp.es.datahot.n2.68x10x95"

      node_roles = [
        "master",
        "ingest",
        "transform",
        "data_hot",
        "remote_cluster_client",
        "data_content"
      ]

      topology = {
        size = "8g"
        size_resource = "memory"
      }
      
      autoscaling = {
        max_size = "131g"
        max_size_resource = "memory"
      }
    }

    warm = {
      id            = "warm"

      node_roles = [
        "data_warm",
        "remote_cluster_client"
      ]
      size = "0"
      size_resource = "memory"
      zone_count = 2
      instance_configuration_id = "gcp.es.datawarm.n2.68x10x190"
      autoscaling = {
        max_size = "131072"
        max_size_resource = "memory"
      }
    }

    cold = {
      id = "cold"
      zone_count = 1
      instance_configuration_id = "gcp.es.datacold.n2.68x10x190"
      
      size = 0
      size_resource = "memory"

      node_roles = [
        "data_cold",
        "remote_cluster_client"
      ]

      autoscaling = {
        max_size = "0"
        resource = "memory"
      }
    }

    frozen = {
      id = "frozen"
      zone_count = 1
      instance_configuration_id = "gcp.es.datafrozen.n2.68x10x95"

      size = 0
      size_resource = "memory"

      node_roles = [
        "data_frozen"
      ]

      autoscaling = {
        max_size = "131072"
        resource = "memory"
      }
    }

    ml = {
      id = "ml"
      zone_count = 1
      instance_configuration_id = "gcp.es.ml.n2.68x32x45"

      size = 0
      size_resource = "memory"

      node_roles = [
        "ml",
        "remote_cluster_client"
      ]

      autoscaling = {
        max_size = "65536"
        max_size_resource = "memory"
        min_size = 0
        min_size_resource = "memory"
      }
    }

    master = {
      id = "master"
      zone_count = 3
      instance_configuration_id = "gcp.es.master.n2.68x32x45"

      size = 0
      size_resource = "memory"

      node_roles = [
        "master",
        "remote_cluster_client"
      ]

      autoscaling = {}
    }

    coordinating = {
      id = "coordinating"
      zone_count = 2
      instance_configuration_id = "gcp.es.coordinating.n2.68x16x45"

      size = 0
      size_resource = "memory"

      node_roles = [
        "ingest",
        "remote_cluster_client"
      ]

      autoscaling = {}
    }
  }

  kibana = {
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    ref_id = "main-kibana"
    region = "gcp-us-east1"

    topology = {
      instance_configuration_id = "gcp.kibana.n2.68x32x45"
      size = "1g"
      size_resource = "memory"
      zone_count = "1"
    }
  }

  lifecycle {
    ignore_changes = [
      elasticsearch[0].topology[2].size
    ]
  }

  observability = {
    deployment_id = "self"
  }
}`

**Comment by tobio** [comment]
Thanks for all the details @mgreenSP23, makes it much easier :)

It looks like the actual error message from the Terraform CLI is _very_ misleading on this one sadly. I can see if referencing the `ec_deployment.deployment.region` attribute, when it's actually failing because of `ec_deployment.deployment.kibana.region` being set. There's a couple of other read-only attributes being set in the config you pasted. I've removed those, I believe this is equivalent to what you have above, but is correctly importing/planning/applying etc through TF.

LMK if this fixes the issue for you. 

```hcl
data "ec_stack" "v7" {
  version_regex = "7.17.?"
  region        = var.ec_region
}

resource "ec_deployment" "elasticcloud_deployment" {
  name                   = var.name
  region                 = var.ec_region
  version                = data.ec_stack.v7.version
  deployment_template_id = var.deployment_template_id

  apm = {
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    ref_id                       = "main-apm"
    size                         = "1g"
    size_resource                = "memory"
    zone_count                   = 1
  }

  elasticsearch = {
    autoscale = "true"
    trategy   = "grow_and_shrink"

    hot = {
      zone_count    = 2
      size          = "8g"
      size_resource = "memory"

      autoscaling = {
        max_size          = "131g"
        max_size_resource = "memory"
      }
    }

    warm = {
      id            = "warm"
      size          = "0"
      size_resource = "memory"
      zone_count    = 2

      autoscaling = {
        max_size          = "131072"
        max_size_resource = "memory"
      }
    }

    cold = {
      id            = "cold"
      zone_count    = 1
      size          = 0
      size_resource = "memory"

      autoscaling = {
        max_size = "0"
        resource = "memory"
      }
    }

    frozen = {
      id         = "frozen"
      zone_count = 1

      size          = 0
      size_resource = "memory"

      autoscaling = {
        max_size = "131072"
        resource = "memory"
      }
    }

    ml = {
      id         = "ml"
      zone_count = 1

      size          = 0
      size_resource = "memory"

      autoscaling = {
        max_size          = "65536"
        max_size_resource = "memory"
        min_size          = 0
        min_size_resource = "memory"
      }
    }

    master = {
      id         = "master"
      zone_count = 3

      size          = 0
      size_resource = "memory"

      autoscaling = {}
    }

    coordinating = {
      id         = "coordinating"
      zone_count = 2

      size          = 0
      size_resource = "memory"

      autoscaling = {}
    }
  }

  kibana = {
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    ref_id                       = "main-kibana"
    size                         = "1g"
    size_resource                = "memory"
    zone_count                   = 1
  }

  lifecycle {
    ignore_changes = [
      elasticsearch.hot.size
    ]
  }

  observability = {
    deployment_id = "self"
  }
}
```

**Comment by tobio** [comment]
Closing this issue, it's highly unlikely to be a provider bug.
