### ISSUE TITLE
State Update Progress

### ISSUE THREAD

**Issue by wegrata** [elastic/terraform-provider-ec#732]
## Question
Is there any progress on the `state update` listed in the README for upgrading to `0.6`.    We have a large mono-repo containing a large number (100+) of clusters and manually updating the state is going to be risky.  Can you let us know the status of this issue?

**Comment by tobio** [comment]
IIUC there's no plans to implement state upgrade. @Kushmaro is that still the case?  

> manually updating the state is going to be risky

FWIW there should be no need to manually update state. You would instead need to: 
* Update the resource definition to be compatible with the 0.6+ schema
* Import existing clusters. The exact mechanics here depend on what else is being managed, but some combination of  `terraform import <cluster>` maybe preceded by `terraform state rm <cluster>`
* Optionally run a `terraform apply` with [`reset_elasticsearch_password=true`](https://registry.terraform.io/providers/elastic/ec/latest/docs/resources/deployment#reset_elasticsearch_password) if you're using the `cluster.elasticsearch_password` attribute elsewhere in your TF module.

**Comment by Kushmaro** [comment]
Hi @wegrata , state update is currently not high on our priorities, since we've more important feature work to do. The current best workaround is what @tobio suggested, an import of existing resources using the new syntax.

**Comment by wegrata** [comment]
Thanks for the update, but that's not great to hear.  @tobio manually reimporting and possibly removing items from the state is manually updating the state IMO.  I'll work with our account manager to see if we can get this moved up in the priority list.

**Comment by wegrata** [comment]
It would be a good idea to update your README to reflect that this isn't likely to get done

**Comment by tobio** [comment]
> manually reimporting and possibly removing items from the state is manually updating the state IMO

That's a reasonable position, there's been discussion on other issues of hand editing state files and I wanted to be clear that's not required.

Do reach out, the priorities here reflect what users have been asking for.
