### ISSUE TITLE
Cannot use ec_deployment.mydeployment.elasticsearch_password with elasticstack provider when reset_elasticsearch_password = true

### ISSUE THREAD

**Issue by GeorgeGkinis** [elastic/terraform-provider-ec#779]
Cannot use **ec_deployment.mydeployment.elasticsearch_password** with **elasticstack** provider when **reset_elasticsearch_password = true**

## Readiness Checklist

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Using an import block and setting **reset_elasticsearch_password = true** the **elasticstack** provider should use the new password to perform API calls.

## Current Behavior

I am currently importing existing deployments using an import block.
This goes well and I can perform mutations afterwards to the deployments.

After the **ec_deployment resource** has been updated I want to configure role-mappings using the **elasticstack** provider :

```
provider "elasticstack" {
  elasticsearch {
    username  = "elastic"
    password  = ec_deployment.mydeployment.elasticsearch_password
    # We run ECE behind a reverse proxy
    endpoints = ["https://elasticsearch.es.mydomain.com/${ec_deployment.enterprisesearch.name}/"]
  }
}
```

Because when importing the **elasticsearch_password** is empty I set  **reset_elasticsearch_password = true** to create a new one.

Then I get :
```
╷
│ Error: Unable to connect to the Elasticsearch cluster
│
│   with module.enterprisesearch.elasticstack_elasticsearch_security_role_mapping.admin_mapping,
│   on ..\..\..\modules\enterprisesearch\role-mappings.tf line 1, in resource "elasticstack_elasticsearch_security_role_mapping" "admin_mapping":
│    1: resource "elasticstack_elasticsearch_security_role_mapping" "admin_mapping" {
│
│ Failed with: {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer
│ realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate user [elastic] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer
│ realm=\"security\"","ApiKey"]}},"status":401}
╵

```
If I set **reset_elasticsearch_password = false** then subsequent terraform apply works again.
It seems like the elasticsearch_password does not get updated after completing the **ec_deployment resource** when **reset_elasticsearch_password = true**.

It should be possible to use the latest value of **elasticsearch_password** in my **elasticstack** provider.
Also the **elasticsearch_user** always remains empty.

## Terraform definition

```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    ec = {
      source = "elastic/ec"
    }
    elasticstack = {
      source  = "elastic/elasticstack"
      version = "~>0.11"
    }
  }
}

provider "ec" {
  #   You can fill in your API key here, or use an environment variable TF_VAR_ec_apikey instead
  #   For details on how to generate an API key, see: https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html.
  #  apikey = var.ec_apikey
  endpoint = "https://console.ece.npo.kvk.nl"
  insecure = false
  verbose= true
  apikey = "REDACTED"
}

locals {
  deployment = {
    # Do not change these
    region      = "ece-region"
    template_id = "default.enterprise.search"

    # Configure your deployment
    name    = "enterprisesearch-tf-dev"
    version = "8.11.3"
    ldap-admin-group = "AD_ADMIN_GROUP"
    es      = {
      hot = {
        size       = "4g"
        zone_count = 3
      }
    }
    kb = {
      size       = "1g"
      zone_count = 1
    }
  }
}

data "ec_deployments" "enterprisesearch" {
  name_prefix            = local.deployment.name
}

import {
  # ID of the cloud resource
  # Check provider documentation for importable resources and format
  id = data.ec_deployments.enterprisesearch.deployments[0].deployment_id
  # Resource address
  to = ec_deployment.enterprisesearch
}


resource "ec_deployment" "enterprisesearch" {
  depends_on = [data.ec_deployments.enterprisesearch]
  alias                  = local.deployment.name
  deployment_template_id = local.deployment.template_id
  name                   = local.deployment.name
  region                 = local.deployment.region
  version                = local.deployment.version

  reset_elasticsearch_password = true
  elasticsearch          = {
    autoscale = false
    config    = {}
    hot = {
      autoscaling = {}
      size          = local.deployment.es.hot.size
      size_resource = "memory"
      zone_count    = local.deployment.es.hot.zone_count
    }
    ref_id   = "main-elasticsearch"
  }
    kibana = {
    config = {
      user_settings_yaml = yamlencode({
        "server.basePath" : "/${local.deployment.name}"
        "server.publicBaseUrl" : "https://console.ece.npo.kvk.nl/${local.deployment.name}"
      })
    }
    elasticsearch_cluster_ref_id = "main-elasticsearch"
    instance_configuration_id    = "kibana"
    ref_id                       = "main-kibana"
    size                         = local.deployment.kb.size
    size_resource                = "memory"
    zone_count                   = local.deployment.kb.zone_count
  }
}


provider "elasticstack" {
  elasticsearch {
    username  = "elastic"
    password  = ec_deployment.enterprisesearch.elasticsearch_password
    endpoints = ["https://elasticsearch.ece.npo.kvk.nl/${ec_deployment.enterprisesearch.name}/"]
  }
}

resource "elasticstack_elasticsearch_security_role_mapping" "admin_mapping" {
  depends_on = [ec_deployment.enterprisesearch]
  name    = "admin_mapping"
  enabled = true
  roles = [
    "superuser",
    "kibana_user"
  ]
  rules = jsonencode({
    "all": [
      {
        "field": {
          "groups": "CN=${local.deployment.ldap-admin-group},OU=Application Groups,OU=Groups,OU=blah,DC=win,DC=k94,DC=blah,DC=nl"
        }
      },
      {
        "field": {
          "realm.name": "blah_users"
        }
      }
    ]
  })
}
```

## Steps to Reproduce

1. set **reset_elasticsearch_password = true**
2. terraform apply -> **import** and **ec_deployment** works, **elasticstack_elasticsearch_security_role_mapping** fails
3. set **reset_elasticsearch_password = false**
4.  terraform apply -> **import** and **ec_deployment** works, **elasticstack_elasticsearch_security_role_mapping** also works

## Context

I am trying to import existing deployment resources and update them at the same apply using the **elasticstack** provider
If possible avoid persisting the state.

## Your Environment

* Version used: 
  * ec: 0.9.0
  * elasticstack: 0.11.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version:
  * Elastic Cloud Enterprise on-prem
  * version 3.5.1
* Environment name and version (e.g. Go 1.9):
  * Terraform v1.7.2 on windows_amd64
  * provider registry.terraform.io/elastic/ec v0.9.0
  * provider registry.terraform.io/elastic/elasticstack v0.11.0

**Comment by tobio** [comment]
> It seems like the elasticsearch_password does not get updated after completing the ec_deployment resource when reset_elasticsearch_password = true.
>
> It should be possible to use the latest value of elasticsearch_password in my elasticstack provider.
Also the elasticsearch_user always remains empty.

Resetting the password is asynchronous, and may not have propagated to all cluster nodes by the time the Terraform resource has completed it's update cycle. Unfortunately there's no signal to determine when the updated password is in place across the entire cluster. 

You can use a `terraform_data` resource to add an arbitrary delay into the Terraform process in order to avoid the 401's, for example

```hcl
...
resource "terraform_data" "cluster" {
  triggers_replace = ec_deployment. enterprisesearch.elasticsearch_password

  provisioner "local-exec" {
    command = "sleep 120"
  }
}

provider "elasticstack" {
  elasticsearch {
    username  = "elastic"
    password  = ec_deployment.enterprisesearch.elasticsearch_password
    endpoints = ["https://elasticsearch.ece.npo.kvk.nl/${ec_deployment.enterprisesearch.name}/"]
  }
}

resource "elasticstack_elasticsearch_security_role_mapping" "admin_mapping" {
  depends_on = [terraform_data.cluster]
  name    = "admin_mapping"
  enabled = true
  roles = [
    "superuser",
    "kibana_user"
  ]
  rules = jsonencode({
    "all": [
      {
        "field": {
          "groups": "CN=${local.deployment.ldap-admin-group},OU=Application Groups,OU=Groups,OU=blah,DC=win,DC=k94,DC=blah,DC=nl"
        }
      },
      {
        "field": {
          "realm.name": "blah_users"
        }
      }
    ]
  })
}
```

**Comment by GeorgeGkinis** [comment]
Thanks for your clear explanation @tobio,
It makes sense now.

**Comment by andrewnazarov** [comment]
@GeorgeGkinis I'm wondering how this works for you because the `terraform plan` will fail for the subsequent password reset. It will use the newly generated credentials, but they will not have been set yet for the real ES instance.

We are trying to solve a similar problem, but have only workarounds

**Comment by GeorgeGkinis** [comment]
@andrewnazarov 
I currently do not save the state file, as we are allowing manual actions on our clusters to enable corrective actions during incidents.

To enforce the settings of our deployments we first use an import block to retrieve the actual status of the deployment and the stack config, and terraform deploys the config in our repository.
Something like what Ansible does. Check the actual status and fix the diffs.

**Comment by GeorgeGkinis** [comment]
@tobio 
It would be a good idea to add the delay suggestion on the elasticstack TF provider page example as that would not work.
https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/guides/elasticstack-and-cloud#creating-deployments

**Comment by tobio** [comment]
The Cloud provider will wait for a deployment to be 'healthy' before the creation completes, which would mean the password has been applied to all cluster nodes. The wait should only be required when explicitly resetting the password.
