### ISSUE TITLE
Review documentation to make sure it follows Terraform guidelines

### ISSUE THREAD

**Issue by karencfv** [elastic/terraform-provider-ec#78]
## Description
We need to make sure we are following all conventions in how documentation
is handled in order to show up on the terraform registry correctly.

We can use https://github.com/terraform-providers/terraform-provider-aws/tree/master/website
and  https://www.terraform.io/docs/registry/providers/docs.html as guides. We might use the `guides` section.

**Comment by marclop** [comment]
This is the guide I have been following all along: https://www.terraform.io/docs/registry/providers/docs.html. I think this issue just hasn't been updated after #77

**Comment by karencfv** [comment]
I left this issue open to remind ourselves to go over the documentation before we release. Also in case we want guides or whatever. But if you think it's overkill to have this issue I don't mind if you want to close it :)

**Comment by marclop** [comment]
No it's great! I just meant for us to keep the description updated with what we should do 🙂 . I think we might want to introduce some guides once we've got a couple of available resources and data sources

**Comment by karencfv** [comment]
Ah yeah! I updated that, thanks!

**Comment by nrichers** [comment]
Chatted with @karencfv and the ask is to edit the Terraform provider docs that are being worked before the beta goes live mid-November. Some of this is already in the root comment, but 

* Docs will get published from the docs source repo to the Terraform site, but the actual mechanics are TBD
* The docs source to edit lives in https://github.com/elastic/terraform-provider-ec/tree/master/docs
* The guidelines the docs need to follow are at https://www.terraform.io/docs/registry/providers/docs.html
* The example the current Elastic docs follow is the AWS ones at https://registry.terraform.io/providers/hashicorp/aws/latest/docs, but you can see all provider docs at https://registry.terraform.io/browse/providers
* Whoever edits this should test the steps

Additional content to edit includes the readme for the repo.

**Comment by nrichers** [comment]
@karencfv spoke to @alaudazzi and she has kindly agreed to handle the edit. Let us know when the content is ready, please and we'll do the edit for grammar & style. Thank you!

**Comment by alaudazzi** [comment]
@karencfv happy to help! I'll ping you over Slack to check if there is anything you want to discuss about.

**Comment by karencfv** [comment]
All official docs have been edited now. Thank you @alaudazzi !
