### ISSUE TITLE
Add a guidance to the Readme and docs that the latest provider and TF version should be used before raising issues

### ISSUE THREAD

**Issue by jakommo** [elastic/terraform-provider-ec#784]
Per internal discussion with @Kushmaro and @kunisen we should update the Readme and docs to indicate that the latest provider and TF version should be used before raising issues with support.

**Comment by tobio** [comment]
There's already a checkbox for this on the new issue template (which is either ignored, or checked regardless of the versions being used). I'd argue if that's not enough of a prompt then adding more guidance into README and the docs will be entirely ineffective.

**Comment by kunisen** [comment]
Thanks @tobio for the comment. 
I hope you don't mind that I pulled you into an internal chat for more details.
