### ISSUE TITLE
Example deployment not working with Trial account and eu-central-1 region

### ISSUE THREAD

**Issue by micro23xd** [elastic/terraform-provider-ec#79]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Should deploy example deployment.

## Current Behavior
When applying terraform with changed region to "eu-central-1" it's failing with this error:
`Error: failed creating deployment: 2 errors occurred:
	* api error: clusters.cluster_invalid_plan: Instance configuration [aws.data.highio.i3] does not exist or is not available to you. The instance configuration must be one of the available configurations. Use the Instance Configuration API to get a list of available configurations. (resources.elasticsearch[0].cluster_topology[0].instance_configuration_id)
	* set "request_id" to "aen40sa8eww7wotfyd1wr9rbfkt4dmjr6hfzkawxxxxxxxxxxxxxxxxxxx" to recreate the deployment resources`

Deployment works with us-east-1 (default) and also works with eu-central-1 in the Elastic Cloud UI, just not in terraform.

## Steps to Reproduce

1. Create new account on elastic cloud
2. Create API key in Account settings
3. Download terraform provider and example
4. Change region to `eu-central-1`
5. terraform apply

## Your Environment

* Version used: latest
* Environment name and version (e.g. Go 1.9): Go 1.15
* Operating System and version: macOS Catalina

**Comment by karencfv** [comment]
Thanks for opening up the issue @micro23xd :) 

Our provider takes the names of the regions as they appear on our [regions list](https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html), and they aren't always named exactly as our cloud providers name them. In this case the region is `aws-eu-central-1` instead of `eu-central-1`.

I have applied the example with `aws-eu-central-1` and it works as expected.

**Comment by marclop** [comment]
Looking at this issue again, I think we should probably document a bit more these things on our side so that new users of the API are aware of it.

**Comment by micro23xd** [comment]
Ohh, I see! Thanks for the quick reply and explanation. Just tested and it works.
