### ISSUE TITLE
Is trust external setting a needed thing in v9.0 ?

### ISSUE THREAD

**Issue by gadekishore** [elastic/terraform-provider-ec#794]
No issues when using v5.1 but when we moved to v9.0 the TF code is expecting trust relationship settings. Actually we are not using CCR/CCS in the environment. 

Are the trust settings needed ones ? we even tried to disable it but giving us following error.

Error: attribute “elasticsearch”: attribute “trust_external”: set of object required

>    elasticsearch = {
>     trust_account = [{ 
>         account_id = "xxxxxxxxxx"
>         trust_all = true
>     }]
>     //trust_external = null
>     
>    /* trust_external = [{ 
>         relationship_id = "xxxxxxxxxx"
>         trust_all = true
>     }] */

**Comment by tobio** [comment]
You should just be able to leave `trust_external` unset if you're not explicitly configuring trust.
