### ISSUE TITLE
Inconsistent terraform plan results (provider 0.5.1)

### ISSUE THREAD

**Issue by khtelus** [elastic/terraform-provider-ec#808]
## Readiness Checklist
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

Terraform plan step produces consistent results, based on the code it is run against.

## Current Behavior

* Terraform version: `1.5.2`
* `ec` provider version: `0.5.1` - I understand that we need to upgrade and this is planned. We will accelerate this effort due to what we are seeing today.

One `terraform plan` run to the next produces inconsistent results, sometimes it will error out with an API call failure, others deployments that do exist are marked as having been deleted and subsequent apply operations will then attempt to create.

This behavior has just started within past couple days? We've always had consistent results previously. Nothing else has changed in my overall environment.

Example `terraform plan` executions against same code - nothing has changed:

```
│ Error: failed reading remote clusters: 1 error occurred:
│       * api error: clusters.cluster_not_found: Cluster [xxx] not available
│
│
│
│   with ec_deployment.monitoring[0],
│   on elastic.tf line 105, in resource "ec_deployment" "monitoring":
│  105: resource "ec_deployment" "monitoring" {
│
╵
╷
│ Error: failed to obtain the deployment template id
│
│   with ec_deployment.monitoring[0],
│   on elastic.tf line 105, in resource "ec_deployment" "monitoring":
│  105: resource "ec_deployment" "monitoring" {
│
╵
make: *** [Makefile:27: pr.plan] Error 1
```

Very next run:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # ec_deployment.default has been deleted
  <removed>

  # ec_deployment.monitoring[0] has been deleted
  <removed>


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place
-/+ destroy and then create replacement
+/- create replacement and then destroy

Terraform will perform the following actions:

  # ec_deployment.default will be created
  <removed>

  # ec_deployment.monitoring[0] will be created
  <removed>

  <other plan output>

Plan: 7 to add, 3 to change, 5 to destroy.
```

## Terraform definition
```
resource "ec_deployment" "default" {
  region                 = format("gcp-%s", var.region)
  name                   = "elastic-${var.env}"
  version                = var.elastic.version
  deployment_template_id = var.elastic.deployment_template_id

  traffic_filter = local.traffic_filter[var.env]

  elasticsearch {
    autoscale = var.elastic.elasticsearch.autoscale

    dynamic "config" {
      for_each = var.env == "np" ? { user_settings_yaml = templatefile("./templates/elasticsearch.tftpl", var.elastic.elasticsearch.config.user_settings_yaml) } : {}
      content {
        user_settings_yaml = config.value
      }
    }

    dynamic "topology" {
      for_each = var.elastic.elasticsearch.topologies
      iterator = topo
      content {
        id         = topo.key
        size       = topo.value.size
        zone_count = topo.value.zone_count
      }
    }
  }

  observability {
    deployment_id = var.env == "np" ? "self" : ec_deployment.monitoring[0].id
  }

  kibana {
    topology {
      size       = var.env == "np" ? var.elastic.kibana.topology.size : "0g"
      zone_count = var.env == "np" ? var.elastic.kibana.topology.zone_count : null
    }

    dynamic "config" {
      for_each = var.env == "np" ? { user_settings_yaml = templatefile("./templates/kibana.tftpl", var.elastic.kibana.config.user_settings_yaml) } : {}
      content {
        user_settings_yaml = config.value
      }
    }
  }

  tags = var.labels
}

resource "ec_deployment" "monitoring" {
  count                  = var.env == "pr" ? 1 : 0
  region                 = format("gcp-%s", var.region)
  name                   = "elastic-monitoring-${var.env}"
  version                = var.elastic.version
  deployment_template_id = "gcp-storage-optimized"

  traffic_filter = [for ip in var.telus_ip_ranges : ec_deployment_traffic_filter.telus[ip].id]

  elasticsearch {
    autoscale = var.elastic.elasticsearch.autoscale

    dynamic "config" {
      for_each = var.env == "pr" ? { user_settings_yaml = templatefile("./templates/elasticsearch.tftpl", var.elastic.elasticsearch.config.user_settings_yaml) } : {}
      content {
        user_settings_yaml = config.value
      }
    }

    topology {
      id         = "hot_content"
      size       = "8g"
      zone_count = 2
    }
  }

  kibana {
    config {
      user_settings_yaml = templatefile("./templates/kibana.tftpl", var.elastic.kibana.config.user_settings_yaml)
    }

    topology {
      size       = var.elastic.kibana.topology.size
      zone_count = var.elastic.kibana.topology.zone_count
    }
  }

  tags = var.labels
}
```

## Steps to Reproduce

1. Check out main branch
2. Run `terraform plan`

## Possible Solution

Either fix the provider if indeed a bug/issue and provider is still supported or remove the provider entirely to prevent use/issues. This is especially dangerous where people may have implemented a `-auto-approve` in an apply pipeline.

## Your Environment

* Version used: 0.5.1
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version: cloud SaaS (GCP) - 7.17.11

**Comment by khtelus** [comment]
Tested an upgrade of provider to 0.10.0 with a local copy of state, errors still present. On some runs it cannot read the resources and a `terraform plan` run will fail. Other times, `plan` will succeed, but suggest that the resource was deleted outside of terraform and that the deployment should be created new.

This seems to be an issue with upstream API vs. the provider.

This issue also exists in our build environment (cloud-based) so there should not be anything related to my local developer environment causing this.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # ec_deployment.default has been deleted
```

**Comment by Kushmaro** [comment]
hi @khtelus . Can you please make clear if you tested this with 0.10.0? even if we detect and find the bug in 0.5.1, we will not port over another version of 0.5.x

Please first upgrade the provider to 0.10.0 (which can only be done with import of resources, not state migration) before re-testing the bug.

**Comment by khtelus** [comment]
@Kushmaro thanks, yes this issue occurred with either 0.5.1 and 0.10.0 as I mentioned in my last comment.

My production environment was affected on Apr 4 and I was able to repro this locally easily - most plan runs would either fail with an error or include changes suggesting deployments had been deleted. Since beginning of my day yesterday I have been unable to reproduce this again. However for at least the period of Apr 3 through 9 this issue was present. 

I'll keep an eye on things over next few days and then update this issue accordingly. A ticket has also been opened w Elastic support. 

Thanks!

**Comment by Kushmaro** [comment]
@khtelus understood, but something wasn't quite clear about your comment - 
>... 0.10.0 with a local copy of state 

since copying the state over from 0.5.1 to be used with 0.10.0 would not work AFAIK.

**Comment by khtelus** [comment]
Ah sorry @Kushmaro gotcha - I meant that to test I changed my backed to local and was using a local copy of state while testing both the provider upgrade and the issue itself w 0.10.0.
