### ISSUE TITLE
Error when observability is configured, but not actually enabled

### ISSUE THREAD

**Issue by andycnguyen** [elastic/terraform-provider-ec#825]
The provider returns an error when deployment observability is configured, but explicitly disabled, i.e:

```
  observability = {
    deployment_id = "self"
    logs          = false
    metrics       = false
  }
```

### Original issue 
---------------------------------

I'm running into an error when I try to provision a cluster that configures observability with `deployment_id` equals `self`.

## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

The cluster is provisioned successfully.

## Current Behavior

I get the following error:

> ╷
> │ Error: Provider produced inconsistent result after apply
> │ 
> │ When applying changes to
> │ module.ec_monitoring_deployment.ec_deployment.cluster, provider
> │ "module.ec_monitoring_deployment.provider[\"registry.terraform.io/elastic/ec\"]"
> │ produced an unexpected new value: .observability: was
> │ cty.ObjectVal(map[string]cty.Value{"deployment_id":cty.StringVal("self"),
> │ "logs":cty.False, "metrics":cty.False,
> │ "ref_id":cty.UnknownVal(cty.String)}), but now null.
> │ 
> │ This is a bug in the provider, which should be reported in the provider's
> │ own issue tracker.
> ╵

## Terraform definition

```
module "ec_monitoring_deployment" {
  source                   = "./modules/elasticcloud"
  api_key                  = var.elastic_cloud_api_key
  deployment_name          = "${local.subscription_key}-monitoring"
  deployment_region        = "azure-westus2"
  deployment_version       = "8.12.2"
  monitoring_deployment_id = "self"
}
```

```
resource "ec_deployment" "cluster" {
  name                   = var.deployment_name
  region                 = var.deployment_region
  version                = var.deployment_version
  deployment_template_id = "azure-storage-optimized"

  elasticsearch = {
    autoscale = "true"

    hot = {
      size = "8g"

      autoscaling = {
        max_size          = "120g"
        max_size_resource = "memory"
      }
    }

    warm = {
      autoscaling = {}
    }

    cold = {
      autoscaling = {}
    }

    frozen = {
      autoscaling = {}
    }

    ml = {
      autoscaling = {}
    }
  }

  # ignore changes that can be made by the autoscaler
  lifecycle {
    ignore_changes = [
      elasticsearch.hot.size
    ]
  }

  kibana = {
    topology = {}
  }

  observability = {
    deployment_id = var.monitoring_deployment_id
    logs          = var.logs
    metrics       = var.metrics
  }
}
```
## Steps to Reproduce

Attempt to apply the terraform configuration detailed above.

## Context

I'm trying to setup a monitoring cluster that my other clusters will send their logs to. Whereas those other clusters should have for `observability.deployment_id` the Id of the monitoring cluster, I've configured the monitoring cluster to use `self`.

## Possible Solution

N/A

## Your Environment

* Version used: `v10.0.0`
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version:
* Environment name and version (e.g. Go 1.9):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by tobio** [comment]
> ```
> When applying changes to
> │ module.ec_monitoring_deployment.ec_deployment.cluster, provider
> │ "module.ec_monitoring_deployment.provider["registry.terraform.io/elastic/ec"]"
> │ produced an unexpected new value: .observability: was
> │ cty.ObjectVal(map[string]cty.Value{"deployment_id":cty.StringVal("self"),
> │ "logs":cty.False, "metrics":cty.False,
> │ "ref_id":cty.UnknownVal(cty.String)}), but now null.
> ```

From the output it looks like `var.logs` and `var.metrics` are both `false` which means that observability is completely disabled. Still something the provider should handle more nicely, but it's not related to self monitoring.

**Comment by andycnguyen** [comment]
> From the output it looks like var.logs and var.metrics are both false which means that observability is completely disabled. Still something the provider should handle more nicely, but it's not related to self monitoring.

This was correct. Thanks @tobio
