### ISSUE TITLE
observability config not working 0.10.0

### ISSUE THREAD

**Issue by rstreics-lb** [elastic/terraform-provider-ec#826]
## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
Creating `observability` config  when it's set in terraform

## Current Behavior
When running creating Elastic Instance with `observability` config it doesn't configure instance.
Configuration doesn't work with supply "id" or "self"

## Terraform definition
```
  elasticsearch = {
    autoscale = {}
    hot = {
      autoscaling = {}
    }
    observability = {
      deployment_id = "self"
    }
  }
```

## Steps to Reproduce
Attempt to apply the terraform configuration detailed above.

## Context
Unable to provision our production instance because terraform fails set critical configuration such metrics/logs

## Your Environment
* Version used: 0.10.0
* Running against Elastic Cloud SaaS or Elastic Cloud Enterprise and version:
* Environment name and version (e.g. Go 1.9):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by insukcho** [comment]
Hi, @rstreics-lb 

Thank you for the bug report.

When I checked your script, I could see the `observability` block is inside of the `elasticsearch` block.
Both are sbling block and should have the sane indention depth.
Check the example here: https://github.com/elastic/terraform-provider-ec/blob/6e18a059218406fc56b8a0d93076205b01137e1e/examples/resources/ec_deployment/with-o11y/deployment.tf#L24

The below script is one of the examples that I tested myself.
The self monitoring feature was enabled with `deployment_id = "self"` option.

```
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    ec = {
      source = "elastic/ec"
      version = "0.10.0"
    }
  }
}

resource "ec_deployment" "this" {
  region = "gcp-us-central1"
  version = "8.3.2"
  name = "ec-testing-4"
  deployment_template_id = "gcp-storage-optimized"
  elasticsearch = {
    hot = {
      size = "1g"
      zone_count = 1
      autoscaling = {}
    }
  }

  kibana = {}

  observability = {
    deployment_id = "self"
  }
}
```

If you need more clarification, let us know.
