### ISSUE TITLE
Release timeline

### ISSUE THREAD

**Issue by phumberdroz** [elastic/terraform-provider-ec#84]
## Question

Is there a rough timeline for a first release of this provider available?

Any link or just a rough quarter would be nice to know. :)

**Comment by karencfv** [comment]
Hi @phumberdroz, thanks for the question!

Unfortunately it's still a bit early for us to provide any timeline for a first release. We will, however, definitely keep everyone updated when we have any dates or other news about the provider.

**Comment by marclop** [comment]
Hi Pierre, our rough estimate to ship the first version ([v0.1.0](https://github.com/elastic/terraform-provider-ec/milestone/1)) by the end of the year.

**Comment by marclop** [comment]
The terraform provider has been released and is available in the Terraform Registry as `0.1.0-beta`: https://registry.terraform.io/providers/elastic/ec/latest
