### ISSUE TITLE
Feature Request: Comprehensive Audit Logging for All User and API Actions in Elastic Cloud UI

### ISSUE THREAD

**Issue by crn1239** [elastic/terraform-provider-ec#846]
### Context 
The absence of detailed logging for UI-level actions in Elastic Cloud makes it challenging to track critical actions, such as the creation and deletion of clusters or the management of API keys. This lack of transparency impacts security, compliance, and the ability to audit changes effectively.

### We need to implement comprehensive logging for all API calls made through the Elastic Cloud UI, focusing on user actions such as:

**User Actions:** Details of who created, modified, or deleted clusters, including timestamps and related configurations.
**API Key Management:** Logs for the creation, deletion, and usage of API keys, along with the user responsible and the exact time these actions occurred.
**User Logins:** Tracking of user login events, including the time of login and actions performed during the session.
**Configuration Changes:** Capture all changes made through the UI, including before-and-after states, with clear user attribution.

This feature aims to provide a detailed audit trail, similar to AWS CloudTrail, for all UI-level interactions in Elastic Cloud.

### Testing

Unit Testing: Test each logging component to ensure accurate capture of API actions.
Integration Testing: Validate that all user actions in the UI are logged correctly and stored securely.
Acceptance Testing: Simulate user scenarios to ensure comprehensive logging and retrievability of logs for audit purposes.
Security Testing: Ensure that logs are protected from unauthorized access and tampering.

**Comment by tobio** [comment]
Similarly, there's a larger body of work to have this supported in the UI/API outside of the provider. We're tracking this internally and the provider will be updated to support new audit logging API's when they're available.
