### ISSUE TITLE
Add Feature to Pause and Schedule Start/Stop Times for Clusters in Elastic Clou

### ISSUE THREAD

**Issue by crn1239** [elastic/terraform-provider-ec#847]
## Context

Clusters, whether for production, QA, or development, are not always in use continuously. Currently, the only way to avoid unnecessary costs for idle clusters is to delete them, which results in data loss and requires time-consuming reconfiguration. A feature to pause clusters, along with scheduling when they stop and start, would offer a cost-effective solution. This allows teams to manage resources efficiently without losing important configurations or data. Scheduling stop and start times ensures that resources are only used when needed, further optimizing cost savings.

## Overview

Add a feature that allows pausing any cluster in Elastic Cloud—whether it's for production, QA, or development—to save costs when the cluster isn't in use. Users should also have the ability to schedule automatic pauses and restarts of clusters based on their specific usage patterns, reducing resource consumption and costs while preserving the cluster's state for easy reactivation when needed.

## Possible Implementation

- **Pause/Resume Option:** Include a "Pause" option in the Elastic Cloud UI that lets users suspend a cluster's operations, freeing up resources while keeping all configurations and data intact.
- **Scheduling:** Add a scheduling feature that allows users to set specific times for clusters to automatically pause and restart. For example, a production cluster could be paused during non-peak hours and restarted automatically when needed.
- **Reminders/Notifications:** Provide automated reminders or notifications for paused clusters, giving users the option to resume or delete them based on their needs.

## Testing

- **Unit Testing:** Ensure that the pause, resume, and scheduling functions work correctly without data loss, and that all configurations are preserved.
- **Integration Testing:** Validate that scheduling works as expected, with clusters pausing and resuming automatically according to the user-defined schedule.
- **Acceptance Testing:** Test the feature in various scenarios, such as pausing production, QA, or development clusters, to ensure it effectively reduces costs and meets user needs.

**Comment by tobio** [comment]
@crn1239 thanks for adding this however, the issue has a much bigger scope than just this Terraform provider. We have an internal issue tracking this request (i.e scheduled pause/resume of deployments to minimise cose), and I've added your vote to that issue. That request isn't on the roadmap at the moment though, so there's no time frame to share. 

I'm going to close this out, since it's not really a provider issue. We are tracking it internally, and would aim to add support to the provider once it's implemented in the broader Cloud API.
